### ISSUE TITLE
BUG: Brick-By-Brick mode can't be opened from the hotbar

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1007]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

6d989f3

### Issue Description

Pressing the button for BBB on the hotbar does not select it. BBB can still be entered by double clicking or dragging a brick in the inventory.

### Reproduction Steps

put on the thinking cap and try to press the brick icon on slot three, or pressing the number 3.

### Expected Behavior

Once selected, the outline and cursor should change and left-clicking on the ground will enable BBB mode.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
This is intended.  Wont fix.

**Comment by EmosewaMC** [comment]
show me proof from live that just pushing the bbb button would enter bbb mode and i'll believe you.

**Comment by MustacheMan2** [comment]
> show me proof from live that just pushing the bbb button would enter bbb mode and i'll believe you.

Alright I'm thinking I didn't phrase it clear enough originally.

1. Enter build mode
2. Press 3 or select the brick icon on slot 3
3. left click into the area

There was a time where you couldn't even highlight the button but it is now working fine

https://youtu.be/zfuzC4meEPI?t=790 not latest live game footage but I am not aware of an alternate use for the button had it been changed by 1.10.64

**Comment by EmosewaMC** [comment]
ah I see.  I thought you never had to left click and only pressing 3 would activate bbb mode, which would be very annoying
