### ISSUE TITLE
BUG: Adding an admin user with MasterServer -a fails

### ISSUE THREAD

**Issue by organman91** [DarkflameUniverse/DarkflameServer#1009]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

b6fc959

### Issue Description

The app gives a crash dump, but as far as I can tell this issue is actually SQL related. I enabled the mysql query log and when I try running the command manually, this happens:

```
MariaDB [darkflame]> INSERT INTO accounts (name, password, gm_level) VALUES ('admin', '<REDACTED>', 9);
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`darkflame`.`accounts`, CONSTRAINT `accounts_ibfk_1` FOREIGN KEY (`play_key_id`) REFERENCES `play_keys` (`id`) ON DELETE CASCADE)
```

### Reproduction Steps

Run `MasterServer -a` and try to add a user.

### Expected Behavior

A new admin user is created.

### Environment

Ubuntu 22.04 (on a VM, not WSL)

**Comment by organman91** [comment]
Update: It looks like the issue is that this command doesn't work if the Nexus Dashboard has been started, but works on a clean database. So this might just be a documentation issue.

**Comment by EmosewaMC** [comment]
This looks to be an issue with Nexus Dashboard as Nexus Dashboard modifies the database and produces an incorrect state that is not supported by the correct state of DLU.  I'm not sure what you would want us to do here though since Nexus Dashboard manages its own migrations list so this should, at least in my eyes, be an issue with how Nexus Dashboard modifies the database vs how our sql queries work

**Comment by aronwk-aaron** [comment]
I will take a look into it

**Comment by EmosewaMC** [comment]
After looking at the Nexus Dashboard code, this is an issue with their initial migration process creating tables that do not reflect the expected state of tables supported.
