### ISSUE TITLE
BUILD: make erroring out at hash

### ISSUE THREAD

**Issue by Dal1ster** [DarkflameUniverse/DarkflameServer#1013]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### DarkflameServer Version

e524b86

### Platform

Ubuntu

### Architecture

x86

### Error Logs

<details>

In file included from /home/lego-uni/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/plugins/auth/ref10/crypto_hash_sha512.h:2,
                 from /home/lego-uni/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/plugins/auth/ref10/open.c:3:
/home/lego-uni/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:74:1: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   74 | MA_HASH_CTX *ma_hash_new(unsigned int algorithm, MA_HASH_CTX *ctx);
      | ^~~~~~~~~~~
      | MA_HASH_MD5
/home/lego-uni/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:74:50: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   74 | MA_HASH_CTX *ma_hash_new(unsigned int algorithm, MA_HASH_CTX *ctx);
      |                                                  ^~~~~~~~~~~
      |                                                  MA_HASH_MD5
/home/lego-uni/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:83:19: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   83 | void ma_hash_free(MA_HASH_CTX *ctx);
      |                   ^~~~~~~~~~~
      |                   MA_HASH_MD5
/home/lego-uni/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:96:20: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   96 | void ma_hash_input(MA_HASH_CTX *ctx,
      |                    ^~~~~~~~~~~
      |                    MA_HASH_MD5
/home/lego-uni/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:108:21: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
  108 | void ma_hash_result(MA_HASH_CTX *ctx, unsigned char *digest);
      |                     ^~~~~~~~~~~
      |                     MA_HASH_MD5
/home/lego-uni/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h: In function ‘ma_hash’:
/home/lego-uni/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:155:3: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
  155 |   MA_HASH_CTX *ctx= NULL;
      |   ^~~~~~~~~~~
      |   MA_HASH_MD5
gmake[5]: *** [libmariadb/CMakeFiles/client_ed25519.dir/build.make:160: libmariadb/CMakeFiles/client_ed25519.dir/plugins/auth/ref10/open.c.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:273: libmariadb/CMakeFiles/client_ed25519.dir/all] Error 2
gmake[3]: *** [Makefile:156: all] Error 2
make[2]: *** [thirdparty/CMakeFiles/mariadb_connector_cpp.dir/build.make:86: mariadbcpp/src/mariadb_connector_cpp-stamp/mariadb_connector_cpp-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:2840: thirdparty/CMakeFiles/mariadb_connector_cpp.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

</details>
I have followed the readme fully step by step, but whenever i run make, it errors out with this, no matter what i do. Reinstalled the system, deleted and redid the steps up to that point, yet it still errors out. Even ran as both sudo and regular and it still made no difference.

**Comment by EmosewaMC** [comment]
Delete your entire cloned repository and redo the steps.  This only occurs in misconfigured setups

**Comment by EmosewaMC** [comment]
Run the following commands and you will be up and running
```
sudo apt-get install libssl-dev zlib1g zlib1g-dev

cd DarkflameServer/build

make clean

cd DarkflameServer

git reset --hard

./build.sh
```
