### ISSUE TITLE
BUG: inaccurate behavior with respawn at end of Battle of Nimbus Station

### ISSUE THREAD

**Issue by Terrev** [DarkflameUniverse/DarkflameServer#1016]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

yeah

### Issue Description

https://youtu.be/HAaknVJU3Ew?list=PL9EFB8500E625ADC7&t=2542

when the four horsemen are smashed, only dead players should be respawned, not everyone

ui is also in slightly incorrect state in interim ("29" should remain in place until chest is opened)

### Reproduction Steps

win bons lol

### Expected Behavior

see video

### Environment

look man this is just here to remind emo do i look like i know what a github is

**Comment by EmosewaMC** [comment]
thanks jamie
