### ISSUE TITLE
Some ppl stuck in Survival eventho they replaced the file

### ISSUE THREAD

**Issue by HorizonFade** [DarkflameUniverse/DarkflameServer#102]
![image](https://user-images.githubusercontent.com/16822185/145114633-1db4dee8-3093-4960-8939-79ec34abd495.png)

**Comment by NealSpellman** [comment]
You've included no information here; do you 100% know they've actually updated/replaced the file? Do they have any errors in their client log files? Anything on the server side?

**Comment by HorizonFade** [comment]
sry they were idiots its fixed
