### ISSUE TITLE
BUG: Fitz Vanderbuilt offers his daily missions side by side

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1024]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

a532bc1

### Issue Description

When talking to Fitz Vanderbuilt in Avant Gardens about his daily missions involving repairing the wall, he gives the option to accept both the brick collecting mission and the mission for building the wall at the same time.

### Reproduction Steps

Talk to Fitz Vanderbuilt in the Sentinel Camp in Avant Gardens after you've completed his regular mission to rebuild the camp wall. Both daily missions can be accepted at the same time.

### Expected Behavior

He should only offer the mission to gather the bricks first and once that is completed he should offer the mission to build the wall.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
This is how the mission was in live.  Closing.
