### ISSUE TITLE
BUG: Negative Imagination

### ISSUE THREAD

**Issue by NinjaOfLU** [DarkflameUniverse/DarkflameServer#1027]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

Don't know, I'm afraid - BLU's current version.

### Issue Description

If a boulder from an ape hits the player between them activating the imagination regeneration ability on the pharaoh's hat, and them receiving the first 10 imagination, the client and server will disagree on how much imagination the player has - the server will reset the player's imagination to 0, whilst the client will increase it. Anything which only uses clientside imagination checks will then cause the player to end up with negative imagination on the server (i.e., using an ability). This can persist across sessions, and can be tested by using the pharaoh's hat again, and noting that it will give less than 10 imagination on first use.
This can also be used to complete quickbuilds, such as those on Crux, with insufficient imagination.

### Reproduction Steps

Use all of your imagination.
Equip pharaoh's hat, and an item which will let you use imagination.
Walk up to ape.
Great it cordially, but from a distance, to incite it to throw a boulder.
Activate the pharaoh's hat just before the boulder is thrown, so that it hits the player before imagination has been received.

Then either:
1)
Wait until you have enough imagination to activate your ability.
Activate the ability.
2)
Build a quickbuild.

Then attempt to regen imagination by any means again, soon after, and you'll see you receive less than you should.

### Expected Behavior

The ability from the pharaoh's hat should probably be cancelled, the server could probably check imagination requirements on casting skills.

However, the only really broken thing about this is infinite imagination for quickbuilds, so the server should probably just check the player's imagination is greater than zero before allowing them to begin a quickbuild.

### Environment

BLU Skill Issue.

**Comment by EmosewaMC** [comment]
This is yet another issue with us trusting client comms for skills too much and not verifying them.  Rebuilds do only check for equivalence to zero which should be changed the less than zero
