### ISSUE TITLE
BUG: Monument fans don't turn back on once deactivated

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1028]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

72ca0f1

### Issue Description

After deactivating a monument fan with the red button, it stays shut off permanently until the fan is smashed and then respawns.

### Reproduction Steps

Deactivate a fan on the monument in Avant Gardens with the red floor button. Wait. The fan does not turn back on

### Expected Behavior

The fan should turn back on after a short period.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Resolved with #989
