### ISSUE TITLE
Non GMs cant send messages

### ISSUE THREAD

**Issue by HorizonFade** [DarkflameUniverse/DarkflameServer#103]

**Comment by DarwinAnim8or** [comment]
Please elaborate. Also make sure you copied chatplus_en_us.txt from your client to the server's res folder

**Comment by jelimoore** [comment]
Run `dos2unix chatplus_en_us.txt` in your `res/` folder on your server as well

**Comment by Pr3roxDLC** [comment]
@HorizonFade are you sure youre server is on the latest build? Chat wasnt able to be used by people that were not gm level 2 or higher (iirc) but this was patched in the newer commits

**Comment by HorizonFade** [comment]
latest build i rebuilt the server 8h ago, also i can msg like i said but the other ppl cant

**Comment by Landshark77** [comment]
> latest build i rebuilt the server 8h ago, also i can msg like i said but the other ppl cant

Fix was merged 4 hours ago, so you'll need to recompile.

**Comment by HorizonFade** [comment]
nvm dont want to rebuild
