### ISSUE TITLE
No Mail-items

### ISSUE THREAD

**Issue by HorizonFade** [DarkflameUniverse/DarkflameServer#104]
![image](https://user-images.githubusercontent.com/16822185/145117672-53a6dc9f-0e94-4673-bec8-3a380699d538.png)

**Comment by DarwinAnim8or** [comment]
These warning messages never had mail items? Or is this happening for others too, like the one from Cole?

**Comment by NealSpellman** [comment]
Unless the Cole one had an issue, this is not a bug. The mail mentioned in this picture never includes an item.
