### ISSUE TITLE
BUG: Nexus Tower pipe quickbuilds sometimes don't respawn

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1046]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

5412501

### Issue Description

Sometimes after building an imagination pipe in Nexus Tower, the pipe will despawn after a time as intended but the quickbuild will not respawn.

### Reproduction Steps

Just go around building the pipes and try to rebuild them later. It's not consistent in terms of where and when. The issue seems to resolve itself temporarily on relog.

### Expected Behavior

the quickbuild bricks should respawn when the pipe despawns

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
I am 90% sure this is intentional per the Luz file but we will check anyways.

**Comment by MustacheMan2** [comment]
To clarify, I don't mean the pipes surrounding the imagination nexus. Also, it's not consistent at all as to which one acts up, one time all of them did not respawn, and last time I tested only one did not respawn.

**Comment by EmosewaMC** [comment]
Some are configured with a quicker time to smash but a not as quick time to rebuild.  This is intentional as far as we can tell
