### ISSUE TITLE
BUG: Players can be warped to bone wolves in Frakjaw Battle

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1057]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

4734996

### Issue Description

This is a really weird bug. Sometimes, when a Bone Wolf does its pounce ability, all players are warped to it. Even weirder, this _only_ happens in Frakjaw Battle, and it doesn't always do it. This has been an issue for some time but it's much more noticeable since Bone Wolves have little to no attack delay now.

### Reproduction Steps

Play Frakjaw Battle. Unsure if this can be done solo or not, since I've mostly just played with others, but I think it at least happens more often when there are other players. Observe as the Bone Wolves can literally warp players to them when they pounce, similar to how the Sword of Fire ability works.

### Expected Behavior

Pretty sure this shouldn't happen.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
The reason it only happens in frakjaw is because the enemies in frakjaw are completely different enemies to those in regular ninjago monastery.

**Comment by EmosewaMC** [comment]
This is actually intentional as far as I can tell.  The bone wolves in Frakjaw have a PullToPoint behavior which pulls targets to them
https://explorer.lu/skills/behaviors/39611/39637
The warp itself should be gradual, but the issue here will not be addressed.  Please create a new issue with the pull to point

**Comment by MustacheMan2** [comment]
> This is actually intentional as far as I can tell. The bone wolves in Frakjaw have a PullToPoint behavior which pulls targets to them https://explorer.lu/skills/behaviors/39611/39637 The warp itself should be gradual, but the issue here will not be addressed. Please create a new issue with the pull to point

Certified LU moment. It seems this isn't actually gradual at all however... https://youtu.be/NyBACT6kB3s?t=1336

**Comment by EmosewaMC** [comment]
Woah.  Even i didnt know it was that insane.  I guess this isnt a bug after all?  thats literally crazy lol
