### ISSUE TITLE
Server transfering Data on a low rate

### ISSUE THREAD

**Issue by Mezalion** [DarkflameUniverse/DarkflameServer#106]
Following my other Issue we found out what caused the Crash/Eternal Loading after creating a character. At least we think so. The Server is sending the Client the Data at a very low rate. We dont know why thats the case, but some people reportet something similar. And its not for all users, we had 3 people testing it. everyone was using LCDRs unpacked and the exact same boot.cfg and even the same Account. One person could load into Venture Explorer, the other two, including me, could not. 

Set-Up: Using a VPS, connecting via Windows (LCDRs unpacked and Raines S3 used, same error)

We think a client log would help - any idea on how to create one? Just to figure out whats even going on

**Comment by DarwinAnim8or** [comment]
Do you mean they used the same account while others weren't using it? 
If they were using it at the same time it should be disconnected, but you never know

**Comment by DarwinAnim8or** [comment]
Also please let your server perform a speedtest. Either using speedtest-cli on Linux or speedtest.net on a windows machine

**Comment by Mezalion** [comment]
> Do you mean they used the same account while others weren't using it? If they were using it at the same time it should be disconnected, but you never know

They disconnected before the next person connected

**Comment by Mezalion** [comment]
Speedtest send out more then 200mbit/s

> Also please let your server perform a speedtest. Either using speedtest-cli on Linux or speedtest.net on a windows machine

**Comment by Mezalion** [comment]
> Also please let your server perform a speedtest. Either using speedtest-cli on Linux or speedtest.net on a windows machine

Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Händle & Korte GmbH (Dusseldorf) [0.36 km]: 5.816 ms
Testing download speed................................................................................
Download: 197.93 Mbit/s
Testing upload speed......................................................................................................
Upload: 189.92 Mbit/s

**Comment by Mezalion** [comment]
We figured out how to set the checkmark in the Nexus Launcher for Client Logs. This is the Output while loading to 55% to Venture Explorer before it did not load further.
For InfoType 0
CPUInfo[0] = 0xd
CPUInfo[1] = 0x68747541
CPUInfo[2] = 0x444d4163
CPUInfo[3] = 0x69746e65

For InfoType 1
CPUInfo[0] = 0x810f81
CPUInfo[1] = 0x80800
CPUInfo[2] = 0x7ed8320b
CPUInfo[3] = 0x178bfbff

For InfoType 2
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 3
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 4
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 5
CPUInfo[0] = 0x40
CPUInfo[1] = 0x40
CPUInfo[2] = 0x3
CPUInfo[3] = 0x11

For InfoType 6
CPUInfo[0] = 0x4
CPUInfo[1] = 0x0
CPUInfo[2] = 0x1
CPUInfo[3] = 0x0

For InfoType 7
CPUInfo[0] = 0x0
CPUInfo[1] = 0x209c01a9
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 8
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 9
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 10
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 11
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 12
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 13
CPUInfo[0] = 0x7
CPUInfo[1] = 0x340
CPUInfo[2] = 0x340
CPUInfo[3] = 0x0
2 :Starting client in location C:\Users\mezal\.nlul\Client\legouniverse.exe, currDir(C:\Users\mezal\.nlul\Client)
1 :Network initialized successfully.
3 RESOURCE:ResMgr could not find file: mesh\miscellaneous\Create_Frame1.NIF
3 RESOURCE:ResMgr could not find file: mesh\miscellaneous\Create_Frame2.NIF
3 RESOURCE:ResMgr could not find file: mesh\miscellaneous\Feedback2.NIF
3 RESOURCE:ResMgr could not find file: mesh\miscellaneous\Login.NIF
3 RESOURCE:Warning!  File missing [mesh\miscellaneous\Create_Frame1.NIF]
3 RESOURCE:Warning!  File missing [mesh\miscellaneous\Create_Frame2.NIF]
3 RESOURCE:Warning!  File missing [mesh\miscellaneous\Feedback2.NIF]
3 RESOURCE:Warning!  File missing [mesh\miscellaneous\Login.NIF]
4 :BrickIDTable: LOT 5597 (design ID 64290) is an alias-duplicate of LOT 5308 (design ID 32525)
3 GUI:Error: Second parameter of Object.registerClass(wt, undefined) should be function or null
2 GUI:Using ScrollingList without a movie clip! BAD!
2 GUI:Message 'OnItemRollout' was sent but no listeners were found.
2 GUI:Message 'ToggleToolTipRollover' was sent but no listeners were found.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:WARNING! Using a MovieClipLocation without a valid MovieClip!
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:WARNING! Using a MovieClipLocation without a valid MovieClip!
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 18
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 34
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 24
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 24
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 24
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 24
2 GUI:attempting to set text 'All the Gear' on undefined textField
2 GUI:attempting to set text 'All the Minigames' on undefined textField
2 GUI:attempting to set text 'All the Bricks' on undefined textField
2 GUI:attempting to set text 'All the Action' on undefined textField
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:resetting rename UI
2 GUI:WARNING! Using a MovieClipLocation without a valid MovieClip!
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:Requesting Vignette...
2 GUI:Requesting Vignette...
2 GUI:Requesting Vignette...
2 GUI:Message 'ToggleFriendsList' was sent but no listeners were found.
2 GUI:Message 'ToggleFriendsList' was sent but no listeners were found.
2 :Attempting to connect to Auth...
2 GUI:Sending login request...
2 :RakNet base connection to Auth acquired.  Sending version...
2 :Connection to Auth confirmed. (NetID 0)
2 :Submitting Login info to Auth...
2 :Stamp PASSPORT_AUTH_LEGOINT_RECEIVED(44) at 14000 (start+0, last+0)
1 :Auth response (SUCCESS). Response Code: (1) SessionKey: (d17f8f3488fea9f4c832fa2393756465) GatewayIP: (185.209.230.30) GatewayPort: (12001) ChatIP: () ChatPort: (0)
2 :Attempting to connect to World...
2 :Auth rejected/terminated connection.
2 :RakNet base connection to World acquired.  Sending version...
2 :Connection to World confirmed. (NetID 1)
2 :Submitting Validation to World... (accnt: Mezalion, key: d17f8f3488fea9f4c832fa2393756465)
2 :Received Character List
2 :A camera with ID: 0 already exists
2 :A camera with ID: 8 already exists
2 GUI:Message 'ResetFreeTrialRenameUI' was sent but no listeners were found.
2 GUI:resetting rename UI
2 GUI:Message 'OnItemRollout' was sent but no listeners were found.
2 GUI:login playing roll out
2 GUI:The message sent named "ShowFreeTrialMembershipDialog" had no listeners.
2 :Sending Character Login Request...
2 GUI:Message 'OnItemRollout' was sent but no listeners were found.
2 :Received TransferToWorld (ip 185.209.230.30, port 12004)
2 :Attempting to connect to World...
3 GUI:Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
3 GUI:Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
3 GUI:Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 :Connection to 'Unknown Server' Dropped. (ID 1, IP 185.209.230.30, Port 12001, Reason: 2)
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 :RakNet base connection to World acquired.  Sending version...
2 :Connection to World confirmed. (NetID 2)
2 :Submitting Validation to World... (accnt: Mezalion, key: d17f8f3488fea9f4c832fa2393756465)
2 :Not requesting character list... (accnt: Mezalion, key: d17f8f3488fea9f4c832fa2393756465)
2 :Received Load Zone, ID (1000:1:0)
2 RESOURCE:LoadThread_Run: MSG_LOAD_ZONE: (zone 1000:1:0, manual file {(invalid)})
2 RESOURCE:LoadThread_DoZoneLoadPart2: (zone 1000:1:0, file {maps/01_Live_Maps/Space_Ship/nd_space_ship.luz} {maps/01_Live_Maps/Space_Ship/nd_space_ship.luz})
3 R

**Comment by NealSpellman** [comment]
Your IP is contained in these log files; I've edited them out of this comment for now, but please delete and repost with it properly removed.

**Comment by Mezalion** [comment]
We figured out how to set the Checkmark in the Nexus Launcher. This is what we got after we let the client load to 55% for about 45 minutes and then closing it. 
Note: This Raines Client. We also used LCDR unpacked, but no logs there since we couldnt get it to run in Nexus Launcher.

`For InfoType 0
CPUInfo[0] = 0xd
CPUInfo[1] = 0x68747541
CPUInfo[2] = 0x444d4163
CPUInfo[3] = 0x69746e65

For InfoType 1
CPUInfo[0] = 0x810f81
CPUInfo[1] = 0x80800
CPUInfo[2] = 0x7ed8320b
CPUInfo[3] = 0x178bfbff

For InfoType 2
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 3
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 4
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 5
CPUInfo[0] = 0x40
CPUInfo[1] = 0x40
CPUInfo[2] = 0x3
CPUInfo[3] = 0x11

For InfoType 6
CPUInfo[0] = 0x4
CPUInfo[1] = 0x0
CPUInfo[2] = 0x1
CPUInfo[3] = 0x0

For InfoType 7
CPUInfo[0] = 0x0
CPUInfo[1] = 0x209c01a9
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 8
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 9
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 10
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 11
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 12
CPUInfo[0] = 0x0
CPUInfo[1] = 0x0
CPUInfo[2] = 0x0
CPUInfo[3] = 0x0

For InfoType 13
CPUInfo[0] = 0x7
CPUInfo[1] = 0x340
CPUInfo[2] = 0x340
CPUInfo[3] = 0x0
2 :Starting client in location C:\Users\mezal\.nlul\Client\legouniverse.exe, currDir(C:\Users\mezal\.nlul\Client)
1 :Network initialized successfully.
3 RESOURCE:ResMgr could not find file: mesh\miscellaneous\Create_Frame1.NIF
3 RESOURCE:ResMgr could not find file: mesh\miscellaneous\Create_Frame2.NIF
3 RESOURCE:ResMgr could not find file: mesh\miscellaneous\Feedback2.NIF
3 RESOURCE:ResMgr could not find file: mesh\miscellaneous\Login.NIF
3 RESOURCE:Warning!  File missing [mesh\miscellaneous\Create_Frame1.NIF]
3 RESOURCE:Warning!  File missing [mesh\miscellaneous\Create_Frame2.NIF]
3 RESOURCE:Warning!  File missing [mesh\miscellaneous\Feedback2.NIF]
3 RESOURCE:Warning!  File missing [mesh\miscellaneous\Login.NIF]
4 :BrickIDTable: LOT 5597 (design ID 64290) is an alias-duplicate of LOT 5308 (design ID 32525)
3 GUI:Error: Second parameter of Object.registerClass(wt, undefined) should be function or null
2 GUI:Using ScrollingList without a movie clip! BAD!
2 GUI:Message 'OnItemRollout' was sent but no listeners were found.
2 GUI:Message 'ToggleToolTipRollover' was sent but no listeners were found.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:WARNING! Using a MovieClipLocation without a valid MovieClip!
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:WARNING! Using a MovieClipLocation without a valid MovieClip!
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 18
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 34
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 24
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 24
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 24
2 GUI:TextResizer given an undefined TextField instance: undefined target font size: 24
2 GUI:attempting to set text 'All the Gear' on undefined textField
2 GUI:attempting to set text 'All the Minigames' on undefined textField
2 GUI:attempting to set text 'All the Bricks' on undefined textField
2 GUI:attempting to set text 'All the Action' on undefined textField
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:resetting rename UI
2 GUI:WARNING! Using a MovieClipLocation without a valid MovieClip!
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 GUI:Requesting Vignette...
2 GUI:Requesting Vignette...
2 GUI:Requesting Vignette...
2 GUI:Message 'ToggleFriendsList' was sent but no listeners were found.
2 GUI:Message 'ToggleFriendsList' was sent but no listeners were found.
2 :Attempting to connect to Auth...
2 GUI:Sending login request...
2 :RakNet base connection to Auth acquired.  Sending version...
2 :Connection to Auth confirmed. (NetID 0)
2 :Submitting Login info to Auth...
2 :Stamp PASSPORT_AUTH_LEGOINT_RECEIVED(44) at 14000 (start+0, last+0)
1 :Auth response (SUCCESS). Response Code: (1) SessionKey: (<SessionKey>) GatewayIP: (<IP here>) GatewayPort: (12001) ChatIP: () ChatPort: (0)
2 :Attempting to connect to World...
2 :Auth rejected/terminated connection.
2 :RakNet base connection to World acquired.  Sending version...
2 :Connection to World confirmed. (NetID 1)
2 :Submitting Validation to World... (accnt: Mezalion, key: <SessionKey>)
2 :Received Character List
2 :A camera with ID: 0 already exists
2 :A camera with ID: 8 already exists
2 GUI:Message 'ResetFreeTrialRenameUI' was sent but no listeners were found.
2 GUI:resetting rename UI
2 GUI:Message 'OnItemRollout' was sent but no listeners were found.
2 GUI:login playing roll out
2 GUI:The message sent named "ShowFreeTrialMembershipDialog" had no listeners.
2 :Sending Character Login Request...
2 GUI:Message 'OnItemRollout' was sent but no listeners were found.
2 :Received TransferToWorld (ip <iphere>, port 12004)
2 :Attempting to connect to World...
3 GUI:Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
3 GUI:Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
3 GUI:Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 :Connection to 'Unknown Server' Dropped. (ID 1, IP <IP here>.30, Port 12001, Reason: 2)
2 GUI:The message sent named "GFxWidgetLoaded" had no listeners.
2 :RakNet base connection to World acquired.  Sending version...
2 :Connection to World confirmed. (NetID 2)
2 :Submitting Validation to World... (accnt: Mezalion, key: <SessionKey>)
2 :Not requesting character list... (accnt: Mezalion, key: <SessionKey>)
2 :Received Load Zone, ID (1000:1:0)
2 RESOURCE:LoadThread_Run: MSG_LOAD_ZONE: (zone 1000:1:0, manual file {(invalid)})
2 RESOURCE:LoadThread_DoZoneLoadPart2: (zone 1000:1:0, file {maps/01_Live_Maps/Space_Ship/nd_space_ship.luz} {maps/01_Live_Maps/Space_Ship/nd_space_ship.luz})`

**Comment by Mezalion** [comment]
> Your IP is contained in these log files; I've edited them out of this comment for now, but please delete and repost with it properly removed.

Done, see above

**Comment by Mezalion** [comment]
Ok, next Update: After more tests we discovered it has to do something with your local Network Set-Up. I got it running on the same Laptop as before but with a different Network.

**Comment by Mezalion** [comment]
Closing this now. Multiple people could load in, its just some networks apparently. Could not figure out which one and what determined them.
