### ISSUE TITLE
BUG: Misaligned player animation for pirate-only quickbuild in Forbidden Valley

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1066]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

2e284eb

### Issue Description

Old bug. When building the pirate-only quickbuild in Forbidden Valley at Mantis Rock, the animation of the player swinging is greatly misaligned but the rope's movement is accurate. When the player finishes the animation in the air, their position is corrected visually.

### Reproduction Steps

Build the pirate-only quickbuild from the crate smashable in Mantis Rock in Forbidden Valley.

### Expected Behavior

The player's animation should be aligned with the quickbuild's animation.

### Environment

ubuntu server

**Comment by aronwk-aaron** [comment]
Will fix orientation, but the animation still wont line up all the way, this is how it was in live
https://youtu.be/KsxTXB60Ce8?list=PL9EFB8500E625ADC7&t=733
