### ISSUE TITLE
BUG: Friends list no longer displaying

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1072]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

33c12f3

### Issue Description

Just updated, and now the friends list is not showing like it should (displaying as empty). Checked and the chat server was still up and logs were normal.

### Reproduction Steps

.

### Expected Behavior

.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Chat server crashed.  It respawns itself so it being up is not indicative of it not being a chat server issue.

**Comment by EmosewaMC** [comment]
Issue has been isolated and fix is found.
