### ISSUE TITLE
BUG: Finishing a race does not send the player back

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1080]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

4ff5afd

### Issue Description

After finishing a race and pressing exit at the leaderboards, nothing happens. Tested on singeplayer, I have yet to test multiplayer.

### Reproduction Steps

Enter a race, play through and finish the race, attempt to exit the race. (only tested on singleplayer)

### Expected Behavior

player should be returned to their previous world

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Is there anyway to get out of the race?

**Comment by MustacheMan2** [comment]
as far as I'm aware, not without gm commands

**Comment by EmosewaMC** [comment]
Can you return to character select and then re-select the character?

**Comment by aronwk-aaron** [comment]
relogging should fix it due to racing being an instanced world and the server not allowing a player to log into an instanced world
