### ISSUE TITLE
ENH: Implement Brick Buckets 

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1086]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

bf0ae6f

### Issue Description

.

### Reproduction Steps

Open the magnifying glass icon in the top left of the inventory while on the bricks tab. Select the option to make a new brick bucket. Drag any bricks into the bucket, select the bucket to see the highlighted bricks inside. Relog or change worlds and notice that the bucket is gone.

### Expected Behavior

They should be saved permanently (I assume)

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Resolved
