### ISSUE TITLE
Add GitHub Discussions area

### ISSUE THREAD

**Issue by lilithium-hydride** [DarkflameUniverse/DarkflameServer#109]
GitHub allows repositories to add a more freeform chat area for people to have discussions. This would allow people to discuss the issues that they may be personally having, without flooding the issue tracker with useless clutter.

**Comment by MasterEric** [comment]
Strong agreement here. The devs can define a set of rules, such as No issues about setup questions. Then, setup questions can be made into discussions as they appear by clicking the Transfer button.

**Comment by Xiphoseer** [comment]
@DarwinAnim8or can you enable this? I don't see any downsides to it

**Comment by MustacheMan2** [comment]
Definitely would be nice to save the embarrassment to know ahead of time "is this a bug?" or "is this not a bug?"

**Comment by DarwinAnim8or** [comment]
Enabled!
