### ISSUE TITLE
BUG: Find 5 blue X-marks on Crux Prime Mission from Duke Exeter isn't working

### ISSUE THREAD

**Issue by FrueherFuchs** [DarkflameUniverse/DarkflameServer#1094]
### Make sure you've done the following:

- [x] I have checked that this issue has not already been reported

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version
https://github.com/DarkflameUniverse/DarkflameServer/commit/f9b52ad01ce3e73a4162e3ac8d65987f345b54d1

### Issue Description
The 5 blue X-marks are there and you can summon an Imagination Blast like the mission want it from you. But after summoning the Blast and destroying the X-mark, the X-mark respawns after a short time and you didn't get any progress. Restarting, redownloading or rebuilding the server doesn't help.

### Pictures
![Screenshot 2023-05-17 103206](https://github.com/DarkflameUniverse/DarkflameServer/assets/56700408/12312817-b241-4494-a0e6-24f1b3040ab0)
![Screenshot 2023-05-17 103535](https://github.com/DarkflameUniverse/DarkflameServer/assets/56700408/072bc4c4-b784-49e9-8656-91eb74b28f32)
![Screenshot 2023-05-17 103644](https://github.com/DarkflameUniverse/DarkflameServer/assets/56700408/7d2ca369-5a46-4a71-ab5a-e1df5a003e95)
![Screenshot 2023-05-17 103702](https://github.com/DarkflameUniverse/DarkflameServer/assets/56700408/621f3efd-1953-4cdf-8921-4204b3b2338c)

### Repruduciton Steps
- get the Mission from Duke Exeter
- try to complete the mission

### Expected Behavior
- mssion progress
- no respanw of the marks

### Environment
Ubuntu Server

**Comment by EmosewaMC** [comment]
Seems to be a flag issue introduced recently.
