### ISSUE TITLE
DarkflameServer running inside of WSL2 can only be connected to from the host machine

### ISSUE THREAD

**Issue by Liam3997** [DarkflameUniverse/DarkflameServer#110]
I've done a bunch of research on this, and still haven't found a satisfying answer. **I'm not expecting the DLU devs to fix this as it seems to be a WSL2 issue**, but I'm creating this issue for further discussion and reference (and hopefully for somebody to prove me wrong and get this working!).

## Your Environment
- Windows 10.0.19043 Build 19043
- Windows Subsystem for Linux Version 2 (WSL2)

## Expected Behavior
- After setting up DarkflameServer within WSL2, the server can correctly bind to the host's public IP, allowing local and external traffic to be serviced by the server

## Current Behavior
- After setting up DarkflameServer within WSL2, the server can only correctly bind to `localhost` or the WSL2 hostname
- If the host's public IP is specified as the `external_ip`, the server will fail to start

## Steps to Reproduce
1. Install WSL2 on Windows 10 or 11
2. Set up DarkflameServer following the instructions in the README
3. Use a service such as https://www.whatismyip.com/ to get the host's public IP
4. Set `external_ip` in `authconfig.ini`, `chatconfig.ini`, and `masterconfig.ini` to the public IP
5. Note that even if you have setup DarkflameServer correctly, port-forwarded correctly, etc. DarkflameServer will still fail to start
6. If you set `external_ip` in `authconfig.ini`, `chatconfig.ini`, and `masterconfig.ini` to the WSL2 hostname, you will be able to connect to it from your host machine, but it cannot be accessed by other devices

## Cause
- This appears to be an issue in WSL2 that has been reported since at least 2019 and has no official fix yet
- Information on the WSL2 issue can be found here: https://github.com/microsoft/WSL/issues/4150

#### `netsh interface portproxy add v4tov4`
- One of the main solutions proposed online is to use `netsh interface portproxy add v4tov4` to forward ports from the host to WSL2. This unfortunately does not work, as `netsh portproxy` does not support the UDP protocol (TCP only)

#### Use a third-party UDP proxy
- There are third-party tools built to forward UDP traffic, such as `socat` or `sudppipe`. I've tested with each of these and they work, but since they can only forward one port at a time, you would need to run a bunch of instances of them at the same time in order to fully communicate between the host and the WSL2 DarkflameServer

#### Use a third-party tool that bridges WSL2's networking to the host's
- Some third-party tools such as [wslbridge2](https://github.com/Biswa96/wslbridge2) or [WSLHostPatcher](https://github.com/CzBiX/WSLHostPatcher) have been created to simulate bridging between WSL2 and the host machine. I haven't tested these, so I can't comment on their effectiveness

#### Switch to WSL1
- At this point you're just switching platforms, but this might honestly be the simplest solution to get this working, as WSL1 uses bridging instead of NAT

**Comment by Morthi** [comment]
also with WSL1 no chance that friends can connect on the server

**Comment by MickVermeulen** [comment]
Thanks for the very thorough issue, will pin this one so that others will notice! Seems like currently there's not much we can do about this. But it's still useful to have a central place for people to discuss this.

**Comment by averysumner** [comment]
We could have a seperate bind ip and redirect ip… Thoughts?

**Comment by conorlawton** [comment]
To add onto that, despite the client's ports being hardcoded, it would be nice to be able to set the ports/port ranges for the servers so that we can translate them as needed.

**Comment by Br3akout** [comment]
I resolved this issue by using the ip adress given by the command "ip addr" under eth1 inet. This Adress needs to be in the config.ini files and in the boot.cfg in the client. After i'd done this other people on my home network could connect to the server and even the account manager (with the same adress and under port 5000).

**Comment by yodadude2003** [comment]
I fixed this by simply reverting my WSL install to WSL v1. Its the simplest option, and if you still want to have a WSL2 machine as your main you can setup multiple VMs. This solution works for me, though it does kinda sidestep it entirely.

**Comment by averysumner** [comment]
Internally we've talked about adding a "bind_ip" config option. This would
be the address that the server binds to, while "external_ip" would remain
the address that the server redirects to. I'll create an issue for this.

**Comment by Virepri** [comment]
From my own testing, I don't believe this is WSL specific; but that it in fact applies any time ports are being forwarded.

**Comment by yodadude2003** [comment]
As far as I understand, this issue is caused by the fact that WSL2 creates a virtual network adapter for the virtual machine, which makes it very difficult to give it a static IP address that you can then port forward to. I have had no issues port forwarding my server on my NAT after switching to WSL1

**Comment by aronwk-aaron** [comment]
Superseded by #225
