### ISSUE TITLE
Shady Vendor bug

### ISSUE THREAD

**Issue by HorizonFade** [DarkflameUniverse/DarkflameServer#112]
![image](https://user-images.githubusercontent.com/16822185/145134118-5a1525c9-c921-44f2-83ce-9240075d017b.png)

**Comment by NealSpellman** [comment]
This is intentional and a DLU-specific feature, adding a camera item that we used to hook up to upload screenshots. Not sure if we planned to remove it from Mr. Ree, but it's not anything you should be concerned over.

**Comment by averysumner** [comment]
I feel like we should add config options to disable DLU-specific stuff like this and the additional inventory space on level-up.

**Comment by Jettford** [comment]
> I feel like we should add config options to disable DLU-specific stuff like this and the additional inventory space on level-up.

@averysumner There already are ones for the NPCs and the additional inventory stuff
