### ISSUE TITLE
BUILD: Docker Windows Compose GLIBCXX Dependency Error

### ISSUE THREAD

**Issue by marqda4th** [DarkflameUniverse/DarkflameServer#1124]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### DarkflameServer Version

2d31b7e

### Platform

Windows

### Architecture

x86

### Error Logs

cmake: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by cmake and /lib/x86_64-linux-gnu/libicuuc.so.72)

<details>

 => ERROR [darkflame build 23/23] RUN echo "Build server" &&     mkdir -p cmake_build &&     cd  0.5s
------
 > [darkflame build 23/23] RUN echo "Build server" &&     mkdir -p cmake_build &&     cd cmake_build &&     sed -i -e "s/NET_VERSION=.*/NET_VERSION=171023/g" ../CMakeVariables.txt &&     sed -i -e "s/__maria_db_connector_compile_jobs__=.*/__maria_db_connector_compile_jobs__=12/g" ../CMakeVariables.txt &&     cmake .. -DCMAKE_BUILD_RPATH_USE_ORIGIN=TRUE &&     make -j 12:
#0 0.183 Build server
#0 0.189 cmake: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by cmake)
#0 0.189 cmake: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libicuuc.so.72)
------
failed to solve: process "/bin/sh -c echo \"Build server\" &&     mkdir -p cmake_build &&     cd cmake_build &&     sed -i -e \"s/NET_VERSION=.*/NET_VERSION=${BUILD_VERSION}/g\" ../CMakeVariables.txt &&     sed -i -e \"s/__maria_db_connector_compile_jobs__=.*/__maria_db_connector_compile_jobs__=${BUILD_THREADS}/g\" ../CMakeVariables.txt &&     cmake .. -DCMAKE_BUILD_RPATH_USE_ORIGIN=TRUE &&     make -j $BUILD_THREADS" did not complete successfully: exit code: 1

</details>

docker version: 4.20.1

Please let me know what I need to do to install this dependency, I searched around online but was unable to find a Windows/Docker fix.

**Comment by EmosewaMC** [comment]
Gah more docker issues...  I'm not sure what's going on here as the wsl install should be able to find the glibc++ library.  Perhaps try deleting the container and trying again or trying to download specifically gnulibc++ in the docker files.  We don't test on docker so when issues arise it catches us by surprise.

**Comment by marqda4th** [comment]
Tried adding adding "libc++-dev libc++abi-dev libicu-dev" to the end of apt-get install, but no luck. Let me know if I should be trying something different, or if you have any ideas. Thank you

**Comment by EmosewaMC** [comment]
could try adding the following to the docker setup steps
`sudo apt-get dist-upgrade`
Not sure of its ability to fix the issue, but [this thread](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error) seems to say it solved issues

**Comment by aronwk-aaron** [comment]
I would look into bumping the base image before doing a dist-upgrade in a container

**Comment by marqda4th** [comment]
After a bit of banging my head against the wall, bumping the base image from gcc:11 → gcc:12 on lines 1 and 32 of docker/Dockerfile solved the issue. 

Thanks all for the help!
