### ISSUE TITLE
BUG: Two Issues Regarding Earth Spinjitzu Missions and Mechanics

### ISSUE THREAD

**Issue by AugustRenders** [DarkflameUniverse/DarkflameServer#1139]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

Unknown, possibly the latest

### Issue Description

These are the issues I discovered.

### Reproduction Steps

There's actually two issues, here.

-1: After you find the key to unlock the chest in the Earth Dojo, equip all parts to the Earth Ninja Suit, and accept Cole's objective of interacting with the Earth lantern. The mission will automatically be marked as completed, even though you've done nothing.

-2: Once you're able to interact with the lanterns, you'll find that their mechanic is working as it should, except there's a problem with the sounds; they're not playing!

### Expected Behavior

-1: You should have to interact with the lantern in order for the objective to be marked as completed.

-2: You should hear the crumbling movement of dirt as you pass through the ground upon interacting with the Earth lantern.

### Environment

Windows 10

**Comment by EmosewaMC** [comment]
Please make 1 issue per bug.

**Comment by EmosewaMC** [comment]
on top of this, the first issue you listed is not a bug and will not be fixed.
