### ISSUE TITLE
Repackaging changed unpacked files.

### ISSUE THREAD

**Issue by MayoIsASauce** [DarkflameUniverse/DarkflameServer#114]
After changing the value in `res/scripts/ai/minigame/survival/l_zone_survival_client.lua` it appears that I need to repackage the files. Seeing as this step is included in the directions I shall ask the question here. Does anyone know of a way to repackage these unpacked .pk extension files?

**Comment by NealSpellman** [comment]
This is not an issue for this repository. We suggest instead using an unpacked client or searching for repackaging tools around the community.
