### ISSUE TITLE
BUG: some buffs do not expire when they should

### ISSUE THREAD

**Issue by Terrev** [DarkflameUniverse/DarkflameServer#1161]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

yeah

### Issue Description

items using the newer buff system do not get canceled in circumstances when they should

### Reproduction Steps

give yourself a dirt sandwich, lot 14502 

you'll have to /completemission 1827 to complete the precondition to be able to eat it (which conveniently awards you with a dirt sandwich as well)

eat the sandwich

die

observe that the buff to your life and armor remains even though the skill specifies that it should not: https://explorer.lu-dev.net/skills/behaviors/37108/37097

this demonstrates cancel_on_death not working but note that theres quite a few such parameters 

### Expected Behavior

The cancel_on_death parameter being set to 1 should force the buff to end on death.

### Environment

yeah

**Comment by aronwk-aaron** [comment]
fixed by #1296
