### ISSUE TITLE
BUG: Spiderlings cannot be stunned

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1173]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

0610fe99

### Issue Description

While other enemies are stunned properly and are unable to move or attack from many kinds of items, spiderlings are exempt from this. They can still move and attack and often don't even get the stun animation.

### Reproduction Steps

Use an Enchanted Dragon's Tooth on a spiderling, observe as they can freely move and attack

### Expected Behavior

they become stunned

### Environment

ubuntu server

**Comment by MustacheMan2** [comment]
To elaborate more, it seems that regular spiderlings seem to be stunned by more things than survival spiderlings, which I have yet to stun successfully. Tested that regular spiderlings were stunned by the daredevil fire extinguisher and the dragons tooth but not by the flash bang, where survival spiderlings were not affected by the above.

**Comment by EmosewaMC** [comment]
This is intentional by the game designers.  Won't fix.
