### ISSUE TITLE
Put back to login screen when going to Block Yard to fight Spider Queen

### ISSUE THREAD

**Issue by xKaleck** [DarkflameUniverse/DarkflameServer#118]
On the first quest to kill the Spider Queen in order to clear the Block Yard "Back-up Bulwark!". When I interact with the launcher and travel to the Block Yard, the game quits out and sends me back to the login screen. (Same thing that happens when the Survival Minigame is left unfixed). Is there a solution similar to the Survival Minigame for this problem?

**Comment by NealSpellman** [comment]
Going to need more details; have you run the migrations to CDServer and confirmed there's nothing in the server logs about what's going wrong here? Can you share any client log details if there's nothing on the server side and you've double checked you've run the migrations? (Be sure to remove any IP addresses from your logs)

**Comment by xKaleck** [comment]
Okay, nothing wrong with CDServer, however, I do have some information from the client log details. I'm attaching a text document below with the information. I'm attempting to move from Avant Gardens (Zone 1100) to Block Yard (Zone 1150). I replaced my name with UserA, and the IP has been removed from the logs.

[serverlog-1150-error.txt](https://github.com/DarkflameUniverse/DarkflameServer/files/7673294/serverlog-1150-error.txt)

**Comment by BustosAndrew** [comment]
@xKaleck can you upload the client logs when you can?

**Comment by xKaleck** [comment]
> @xKaleck can you upload the client logs when you can?

Do you know where they would be within the client?

**Comment by xKaleck** [comment]
Fixed the problem, incorrectly port forwarded when setting up the server. Closing.
