### ISSUE TITLE
BUG: Slow Kraken in Shooting Gallery

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#119]
The Kraken is very slow and loses all of its difficulty in the process.

**Comment by averysumner** [comment]
Can you show evidence of its speed in live? Jamesster play through link?

**Comment by MustacheMan2** [comment]
[https://m.youtube.com/watch?v=xilmSHk8oq8&list=PL9EFB8500E625ADC7&index=39](url) 7:50

The Kraken is significantly slower than it should be in DLU

**Comment by averysumner** [comment]
Interesting… possibly a hardcoded value somewhere. Any idea @Wincent01?

**Comment by aronwk-aaron** [comment]
Hard coded in the script:
https://github.com/DarkflameUniverse/DarkflameServer/blob/58d2cee984cccdb268b0718ebe5407ec535510fa/dScripts/SGCannon.cpp#L988-L994

Last two entries on Line 992 are the min and max speed, will tinker with these till it looks live accurate
