### ISSUE TITLE
BUG: Buccaneer Monkey inflicts damage on the player

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1194]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

2e386d2

### Issue Description

.

### Reproduction Steps

- Equip 7416
- Throw the monkey at an enemy (slot 4)
- stand near the monkey until it explodes
- observe that you took 5 damage

### Expected Behavior

this should not happen

### Environment

Ubuntu Server 20.04

**Comment by EmosewaMC** [comment]
Lol

**Comment by MustacheMan2** [comment]
apparently this hurts all players as well, could make for a funny troll

**Comment by EmosewaMC** [comment]
fixed on main with the repro steps provided here.
