### ISSUE TITLE
BUG: LUP Rocket interface opens for other players in the instance

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1195]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

2e386d2

### Issue Description

When accessing the rocket launcher in Starbase 3001, the interface for choosing the LUP worlds opens for you, but also opens for other players in the instance.

### Reproduction Steps

- Go to the rocket pad in Starbase 3001
- With another player present, interact with it (or have the other player interact)
- observe as everyone gets the popup

### Expected Behavior

this should not happen

### Environment

Ubuntu Server 20.04

**Comment by aronwk-aaron** [comment]
lol, will try to look at it sometime this week, very surprised this wasn't noticed until recently, as it hasn't been touched in like a year
