### ISSUE TITLE
Streaks cannot be lost in Shooting Gallery

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#120]
They are added up and streak bonus points given, but missing boats/hitting friendlies will not drop the streak, making for an easy game with not much skill involved.

**Comment by EmosewaMC** [comment]
This is not a bug - if you get the supercharged cannon, you are not supposed to lose your streak.

**Comment by averysumner** [comment]
Can someone confirm this with video from live?

**Comment by Racater** [comment]
https://www.youtube.com/watch?v=pAZO1ikhn6M?t=175.
It looks like the streak is not lost. The bug can be closed.

**Comment by MustacheMan2** [comment]
Coming back to this issue to ask what happened here lol. The issue is definitely still present. I never said I was using the supercharged cannon, and the live evidence provided here does not include the player missing a shot, unlike here https://youtu.be/xilmSHk8oq8?si=CV05ntLMke3EQKQN&t=396

**Comment by EmosewaMC** [comment]
Streaks can be lost, just not in every scenario.  Create a new, non-vague issue then because only missing a shot does not drop the streak.  Everything else loses a streak and works as intended.
