### ISSUE TITLE
BUG: `5 :Bad FX Unserialize For Object 16589!  Restart Server to Fix`

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#1200]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

main

### Issue Description

See title.  Should not happen.  Nimbus station race place -> plaza.

### Reproduction Steps

spawn in race place
go to plaza
check logs

### Expected Behavior

No log

### Environment

All

**Comment by aronwk-aaron** [comment]
16589 is shouty, so same should be happening in NT and AG
