### ISSUE TITLE
Server error on start-up

### ISSUE THREAD

**Issue by cowabummerr** [DarkflameUniverse/DarkflameServer#121]
The server was working poorly with consistent crashing at the armor polish quest, but it was still working. I decided to shut down the server to re-launch it to see if that would fix any issues, but I now get a consistent error that keeps the server from starting.
I know little to nothing about coding or how any of this all works, but the issue seems to be in this snip of server shit
![drtfyhukjl](https://user-images.githubusercontent.com/95734439/145151477-18aac123-80c1-46a2-9437-8fb1e99b1aff.png)
.

**Comment by CitrusHappy** [comment]
#40

**Comment by averysumner** [comment]
> #40

The line `Destroying MySQL connection! ` doesn’t mean the bug is the same. That is just what happens every time the server gracefully exits. It closes the MySQL connection _intentionally_.

**Comment by cowabummerr** [comment]
I figured out the issue.
For some reason using ctrl + c doesn't close the WorldServer, so I had 4 or so running at once from previous server launches.
After using the kill command on them all the server runs again.
