### ISSUE TITLE
ENH: Replace Account Manager with Nexus Dashboard

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#1223]
### Is your feature request related to a problem?

Account manager was always just the bare minimum and much more feature complete nexus dashboard exists now and should be used instead

### Describe the solution you'd like

fully replace AccountManager with Nexus Dashboard in the docker setup.  

### Repository breaking implications

Docker users would need to re-setup their instance or possibly wouldnt be able to update if the alternative is taken.

### Describe alternatives you've considered

Throw away docker entirely and use pre-release binaries instead and require the user to setup nexus dashboard on their own

**Comment by Xiphoseer** [comment]
Fixed in #1373
