### ISSUE TITLE
BUG: Pets do not despawn until 12 seconds pass

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#1241]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

all

### Issue Description

Pets no longer despawn when you hibernate them until 12 seconds pass.  Issue is caused when we properly implemented death_behavior type 0.

### Reproduction Steps

summon a pet
hibernate said pet
observe that the pet does not despawn, nor does it play its despawn animation

### Expected Behavior

pet plays a despawn animation

### Environment

all

**Comment by MustacheMan2** [comment]
This seems fixed.
