### ISSUE TITLE
BUG: Shooting gallery objects spawning on top of each other

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1260]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

0f9e951

### Issue Description

Shooting gallery targets, most notably the larger infected galleons, often spawn on top of each other, meaning you can take out multiple with one shot. Will provide video evidence on request.

### Reproduction Steps

.

### Expected Behavior

.

### Environment

Windows

**Comment by EmosewaMC** [comment]
Taking out multiple with one shot is determined by the skill and is unrelated to the ships spawning on top of one another.  If you vsn take out multiple with 1 shot then that is intentional by the designers.

**Comment by MustacheMan2** [comment]
> Taking out multiple with one shot is determined by the skill and is unrelated to the ships spawning on top of one another. If you vsn take out multiple with 1 shot then that is intentional by the designers.

Well, yes, of course you can normally take out multiple, but in this case you can aim exclusively at one and take out all the others spawned on top of it in this case.

**Comment by EmosewaMC** [comment]
The bug here is in the fact that they can spawn on top of each other.  Taking out multiple with 1 hit is indeed intentional and fixed in a future pr.
