### ISSUE TITLE
Return to the Venture Explorer. Sentry bots are broken.

### ISSUE THREAD

**Issue by NekoTiga** [DarkflameUniverse/DarkflameServer#127]
Corrupted bots do not attack you and can not be attacked, this softlocks you from progressing since you need to destroy 6 of them.
![image](https://user-images.githubusercontent.com/20857024/145206466-b232840e-72cc-4a39-8ad9-da70672fc192.png)

**Comment by averysumner** [comment]
Duplicate of #54, closing. Please ensure your issue is not a duplicate next time.
