### ISSUE TITLE
Server errors when entering first area

### ISSUE THREAD

**Issue by cowabummerr** [DarkflameUniverse/DarkflameServer#128]
The server's up and running, but whenever I exit the tutorial area the server console shows stuff about not being able to get quests, and when I eventually get to the armor polish quest the server crashes when I try to talk to the vendor and resets my progress to when I was on the launch platform for the rocket.
Snip is right after the message confirming the player loaded into the area, up to the fatal errors that crash it
![sedtrfyhgj](https://user-images.githubusercontent.com/95734439/145207699-1637196c-a3ab-47ad-8c83-c185c4c51cde.png)
.

**Comment by Relran** [comment]
I have the same problem when reaching a litter further in mission (still pretty much at the start). Did you fixed it or someone have a solution? Thx

**Comment by MickVermeulen** [comment]
Have you tried this with the latest source code?

**Comment by averysumner** [comment]
Closing this issue as it is stale and no further communication has occurred. Feel free to open again if this issue persists.
