### ISSUE TITLE
BUG: Death plane in Advent Gardens spider cave does not function

### ISSUE THREAD

**Issue by jadebenn** [DarkflameUniverse/DarkflameServer#1282]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

411dce7

### Issue Description

The death plane in the Advent Gardens spider cave does not smash your character (despite the console stating it sends a die request).

### Reproduction Steps

1. Go to the Advent Gardens spider cave
2. Succumb to the pressures of life and jump off the edge

https://github.com/DarkflameUniverse/DarkflameServer/assets/9892985/73ddfbb3-3e00-4535-9a9c-50b3c0decbc2

### Expected Behavior

Death.

### Environment

Windows client, WSL Ubuntu server

**Comment by EmosewaMC** [comment]
if it sends a die request then the person sending said request should be smashed

**Comment by jadebenn** [comment]
It's definitely strange. I see this in the console when I jump:
`[12-11-23 18:34:33 GameMessages.cpp:4158] Got die request: 1`
but my character does not smash.

**Comment by EmosewaMC** [comment]
> It's definitely strange. I see this in the console when I jump: `[12-11-23 18:34:33 GameMessages.cpp:4158] Got die request: 1` but my character does not smash.

sounds like a small modification to be made :)

**Comment by jadebenn** [comment]
Definitely seems like it would be up my alley. I'm mainly going through my "bug list" I'd been compiling during my playthrough right now so I can get these issues tracked. Some of them I can probably fix myself when I have the time.

**Comment by EmosewaMC** [comment]
I will put this one assigned to you and if you don't want to work on it, feel free to let me know.

**Comment by jadebenn** [comment]
Sounds good to me!
