### ISSUE TITLE
BUG: Enemies can "spawn camp" the Advent Gardens (front) spider cave respawn point

### ISSUE THREAD

**Issue by jadebenn** [DarkflameUniverse/DarkflameServer#1283]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

411dce7

### Issue Description

Enemies will attack spawning players in the front section of the Advent Gardens spider cave.

https://github.com/DarkflameUniverse/DarkflameServer/assets/9892985/2ffd06df-fbc2-49e7-876c-c076a3f947df

### Reproduction Steps

1. Go to the front section of the Advent Gardens spider cave
2. Aggro a bunch of enemies
3. Die
4. Be spawn camped

### Expected Behavior

In live, enemies would disengage from players who walked onto the rocks, as shown here:

https://youtu.be/XYUIEo798Ps?si=qz6-HjofppDLWwkL&t=181

### Environment

Windows client, WSL Ubuntu server

**Comment by MustacheMan2** [comment]
Is it just me that can't view the video files you're sharing?

**Comment by jadebenn** [comment]
Works fine on my end. Would be good to hear from someone else to see if it's just me?

**Comment by EmosewaMC** [comment]
Works for me too.  It's a navmesh issue, so only I can solve it.
