### ISSUE TITLE
BUG: Server interrupting quickbuild completion when the player is actually able to finish it

### ISSUE THREAD

**Issue by jadebenn** [DarkflameUniverse/DarkflameServer#1285]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

411dce7

### Issue Description

When a player's imagination capacity is equal to that of a quickbuild, the server interrupts the quickbuild the moment their stored imagination hits zero, despite the quickbuild being completable.

https://github.com/DarkflameUniverse/DarkflameServer/assets/9892985/1690e096-c168-4097-8e62-866f1346c061

### Reproduction Steps

1. Find a quickbuild with an imagination cost equal to your current imagination capacity
2. Attempt to build it
3. Be interrupted by the server when your character's imagination hits zero
4. Press shift again to nonetheless finish the quickbuild

### Expected Behavior

Quickbuild completion should not be interrupted

### Environment

Windows client, WSL Ubuntu server

**Comment by EmosewaMC** [comment]
I know the issue here and its not an easy one, has to do with timings
