### ISSUE TITLE
Was able to get a quest from lcdr

### ISSUE THREAD

**Issue by Comitatvs** [DarkflameUniverse/DarkflameServer#129]
After getting the quest in Gnarled Forest from Captain Jack Knife that requires you to get those 3 map pieces I was able to get one of those missions from lcdr's NPC
![lcdr huh](https://user-images.githubusercontent.com/95754363/145209036-37266559-8774-4267-874a-a9e426b35718.PNG)
![lcdr quest](https://user-images.githubusercontent.com/95754363/145209070-d92f9e4c-8db5-4d4e-9a3d-15489beb2841.PNG)

**Comment by averysumner** [comment]
This is an issue with his base NPC having available missions. Shouldn’t impact gameplay too much, just a bit annoying. Likely a won’t fix.

**Comment by Comitatvs** [comment]
Yea I don't think its a big deal, just wanted to report it in case there's a more serious underlying issue.

**Comment by aronwk-aaron** [comment]
Won't fix, disable vanity NPC's if you don't want this to happen
