### ISSUE TITLE
BUG: Seeing the dust clouds in "Sentinel Scrubdown" requires reloading the character

### ISSUE THREAD

**Issue by jadebenn** [DarkflameUniverse/DarkflameServer#1310]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

98dc291

### Issue Description

Dust clouds do not appear when Sentinel Scrubdown is initiated unless you reload the character (or presumably, enter and exit the map).

### Reproduction Steps

1. Accept mission
2. Dust clouds do not show up until relog

### Expected Behavior

Dust clouds showing up should not require relog

### Environment

WSL

**Comment by MustacheMan2** [comment]
I believe it loads in by scene so alternatively you can just walk to a different area of the tower and come back and they will be there, but often there aren't enough spawned for a single go.
