### ISSUE TITLE
BUG: Extreme slowdowns and lag in Gnarled Forest

### ISSUE THREAD

**Issue by PuppyIron** [DarkflameUniverse/DarkflameServer#1334]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

c0b969e3

### Issue Description

Once I reach the midway point of Gnarled Forest and start accepting quests or try to fight enemies there is SEVERE delay to the actions I take (This is serverside not clientside). The WorldServer spits out Error codes when I try to take a quest action like turning it in. All other worlds have been without issues so far only when I visit this world I get this issue. Progress is saved inconsistently.

### Reproduction Steps

Play the game and make it to the midway point of gnarled forest.

### Expected Behavior

Game should run smoothly. Progress should be possible.

### Environment

I set the server up using the [Native Windows Setup Guide by HailStorm](https://gist.github.com/HailStorm32/169df65a47a104199b5cc57d10fa57de).

**Comment by EmosewaMC** [comment]
Change maximum bandwidth in sharedconfig.ini to 0.

**Comment by PuppyIron** [comment]
The gameplay works now. But now the animations and weapons seem to disapear at times. I guess I'll just have to deal with it. Thanks.
