### ISSUE TITLE
server crashes (probably) because server can't update RespondToMission

### ISSUE THREAD

**Issue by Relran** [DarkflameUniverse/DarkflameServer#135]
when I am reaching the shop mission (at the start) my server crashes and says:

[08-12-21 21:32:10] [GameMessages]: Unable to get mission 314 for entity 1152921508901814274 to update reward in RespondToMission
[08-12-21 21:32:50] [GameMessages]: Unable to get mission 315 for entity 1152921508901814274 to update reward in RespondToMission
[08-12-21 21:32:55] [GameMessages]: Emote (356) (288300748454049803)
[08-12-21 21:32:55] [GameMessages]: Emote target found (1)
[08-12-21 21:32:58] [GameMessages]: Unable to get mission 733 for entity 1152921508901814274 to update reward in RespondToMission
[08-12-21 21:33:04] [GameMessages]: Emote (356) (0)
Fatal error 11

Anyone have an idea? help will be greatful!

**Comment by Relran** [comment]
https://cdn.discordapp.com/attachments/918229190405398568/918232521479716935/unknown.png
this is the actual error*

**Comment by Pr3roxDLC** [comment]
when was the last time you rebuild your Server?

**Comment by Relran** [comment]
What do I mean by rebuild?

**Comment by Racater** [comment]
"rebuild" is when you run the `make` command on your server machine.

**Comment by inventorman101** [comment]
I am also getting this issue with a another player that is a non-gm player

```
[GameMessages]: Unable to get mission 1673 for entity 1152921508901814274 to update reward in R
espondToMission
```

**Comment by mattachew12** [comment]
I also get a similar message on my server output, but it may be something completely different. I've attached the server output below. 
The issue I see is that when returning to Bob on the Venture Explorer after collecting the 6 imagination orbs, I level up and then get stuck after the zoom animation to see Sky Lane fails to run. At this point I am able to punch and use my mouse to rotate the camera vertically, but rotating the camera horizontally doesn't work and neither does moving. Logging out and in fixes the movement and camera, but then I still have 0 imagination out of 6, and breaking the cargo rocket boxes doesn't give any, which prevents proceeding through the tutorial.
[ServerOutput.txt](https://github.com/DarkflameUniverse/DarkflameServer/files/7716454/ServerOutput.txt)

**Comment by averysumner** [comment]
Has this issue persisted on the latest commit?

**Comment by EmosewaMC** [comment]
Not an issue with Responding to Mission.  Could you confirm if this happens on the latest commit?

**Comment by EmosewaMC** [comment]
Closing due to stale thread and this not being the actual issue.  Feel free to re-open with a new issue with some more details while being on the latest commit
