### ISSUE TITLE
better documentation or at least linking to better one :)

### ISSUE THREAD

**Issue by apppro123** [DarkflameUniverse/DarkflameServer#137]
First thank you all for bringing back the game, its awesome!!!

Because the documentation is quite difficult so far, there is a great video for Windows/Linux to get the server/game up and running.
I am not sure if an issue is the right thing for it, but I don't know where I should post it instead. So sorry if its the wrong place.

What I have done is wrote down all the commands with some improvements and comments (on how to use it and what issues were coming up in my process with my fixes for them):

source (video): [Darkflame Universe Server Setup Tutorial (2021)](https://www.youtube.com/watch?v=mDGoV5AYaDo)

**other information**
**terminal**
Crl+V doesn't work (according to my knowledge) (CTRL+C does)
in my case right clicking worked to paste something from clipboard

**nano**
a tool to edit files in terminal
when "Ctrl+X" is stated, to save the file do
1. press "y" when asked to save the content
2. press enter to save the file with that name

**commands (explanations)**
ls = list items in current directory
cd (path) = change path to where you specified ".." means you want to go one directory up/out
mkdir = make directory

**INSTALLATION BEGINS**
*Windows Power Shell*
wsl --install -d Ubuntu (if that is not working, just install it via the microsoft store, that way you don't need powershell)

*after it has installed*
apt update && apt upgrade

sudo su (if you dont want to type sudo each time)

sudo apt install gcc cmake build-essential

apt-get install zlib1g-dev

cd / (not sure if that is the best way)

git clone --recursive https://github.com/DarkflameUniverse/DarkflameServer

cd DarkflameServer
nano CMakeVariables.txt --> probably you can leave it as is (but you had their DarkflameUniverse client e.g. as a beta tester)
Ctrl+X to exit

mkdir -p build
cd build
cmake ..
make

*according to the youtuber, MariaDB works fine (MySQL not)*
apt install mariadb-server
service mysql start (MariaDB installs mysql automatically)
mysql_secure_installation

*Enter:*
1. your root password (that you configured when installing ubuntu/linux distro)
2. n (dont want to change root password)
3. y (remove anonymous users)
4. n (login remotely, you can set that to yes, if you know why)
5. y (remove test database)
6. y (reload privilege tables --> makes changed settings active immediately)

mysql -u root (login mysql as root user)

*opens MariaDB terminal (in current terminal)*
CREATE DATABASE DLU;
CREATE USER 'dluserver'@'localhost' IDENTIFIED BY 'darkflame'; (dluserver is the username and darkflame the password in this case)
GRANT ALL PRIVILEGES ON DLU.* TO 'dluserver'@'localhost';
FLUSH PRIVILEGES;
exit

*back in ubuntu terminal*

*test if user works*
mysql -u dluserver -p
(type in password you specified, in this guide it would be darkflame)
exit

cd ..
mysql -u root

*in MariaDB terminal*
USE DLU;
source migrations/dlu/0_initial.sql (see which files are under https://github.com/DarkflameUniverse/DarkflameServer/blob/main/migrations/dlu, because we cloned the whole repository, we already have that file and can directly import them into our database)
exit

*back in ubuntu terminal*
*create resources folder in the next steps*
apt install python3-pip
pip install git+https://github.com/lcdr/utils

*to not use a too long path to get to these utils*
git clone https://github.com/lcdr/utils (now they should show up, if you type ls)

cd build/res

look around 21:00 for instructions to copy files to build/res folder
\\wsl$\Ubuntu (for getting into Ubuntu files)

*if you have access problems, change the access with chmod to 777 temporarely*

*after these copy instructuions (around 24:30)*

(inside DarkflameServer directory) python3 utils/utils/fdb_to_sqlite.py build/cdclient.fdb --sqlite_path build/res/CDServer.sqlite
cd build
rm cdclient.fdb

apt install sqlite3
cd ..
sqlite3 build/res/CDServer.sqlite < migrations/cdserver/0_nt_footrace.sql
sqlite3 build/res/CDServer.sqlite < migrations/cdserver/1_fix_overbuild_mission.sql
sqlite3 build/res/CDServer.sqlite < migrations/cdserver/2_script_component.sql

cd build

nano authconfig.ini
hostname -I (shows your public IP) (copy)

*edit*
mysql_host=localhost
mysql_database=DLU (or the name you choose when creating the database)
mysql_username=dluserver (or the username you choose when creating the database)
mysql_password=darkflame (or the password you choose when creating the database)
dump_folder=crashlogs/auth
external_ip=(paste the IP) (just exists in 3 of the 4 .ini files)
Ctl+X to exit (dont forget to save)

*do the same to the other files: chatconfig.ini, masterconfig.ini, worldconfig.ini*
*would be good to change the crashlogs folder, so you know, to which "config"/topic the crash belongs/what did it throw*
*e.g. in chatconfig.ini dump_folder=crashlogs/chat*

mkdir crashlogs
mkdir crashlogs/auth crashlogs/chat crashlogs/master crashlogs/world

*create the admin account for the game*
./MasterServer -a (if you don't do it in one part, and you get an error "Unable to connect to localhost" just reastart database like service mysql start)
(input a username and password)

*create account manager*
cd /
git clone https://github.com/DarkflameUniverse/AccountManager
cd AccountManager
pip install -r requirements.txt
nano credentials.py
(copy content from here in this file https://github.com/DarkflameUniverse/AccountManager under the proper section)
(change SECRET_KEY to random generated string)
(change DB_URL field to e.g. 'mysql+pymysql://dluserver:darkflame@localhost/DLU'
nano resources.py
(copy content from here in this file https://github.com/DarkflameUniverse/AccountManager under the proper section)

*start this*
python3 app.py
(you can open it via "Running on <copy this address> ..." then paste it in a browser with /login (if you are admin and want login) /activate (if you are a player to signup to a server))
(Ctrl+C in terminal to leave)

*finished with server configuration :) *

*in your client folder*
(open boot.cfg)
change AUTHSERVERIP=0:<your-server-ip>; (you can find it again with "hostname -I")

*again in server terminal*
cd /DarkflameServer/build
./MasterServer

*now run legonuniverse.exe from client directory*

*do bug fix in client for minigames*
*instructions can be found [here](https://github.com/DarkflameUniverse/DarkflameServer#survival)

**General (from now on)**
*starting server*
1. start/open server (e.g. Ubuntu)
2. sudo su (not really needed, just for some commands later)
3. service mysql start
4. cd /DarkflameServer/build
5. ./MasterServer
6. execute your client executable

**Comment by Jettford** [comment]
The documentation for setup is perfectly fine, the documentation is not made for everyone as far as I am aware. It is made for sysadmins and Developers

**Comment by JustProp** [comment]
is there any steps/guides on rebuilding the server? there seems to be patches and such but i dont know how to update my current files without ruining something.

**Comment by Saymoan** [comment]
@JustProp 
https://gist.github.com/Saymoan/cee72d3e6244a51f70124ac86a2802e9#updating-dlu

**Comment by JustProp** [comment]
@Saymoan really helpful, tysm!

**Comment by NealSpellman** [comment]
Given this doesn't really fit as an "issue", I'm closing this. You're welcome to open a PR if there's specific changes you'd like to see.
