### ISSUE TITLE
Dramatic movement speed increase with spinjitsu

### ISSUE THREAD

**Issue by ianRudnick** [DarkflameUniverse/DarkflameServer#139]
When using spinjitsu (using The Nunchucks Of Lightning) on enemies at Brig Rock in Gnarled Forest, my character's movement speed progressively increases. I suspect it has something to do with dying (to maelstrom chests or admirals) while in spinjitsu. I've been able to replicate it after relogging and after restarting the server, but haven't pinned down the exact cause.

**Comment by ianRudnick** [comment]
I reproduced this issue at Cavalry Hill while using The Shurikens of Ice and dying to the horsemen while charging spinjitsu.

**Comment by averysumner** [comment]
Although this came first, I’m closing it in favor of #235, as it provides a better description.
