### ISSUE TITLE
Word Built Username Not Populating in the Database

### ISSUE THREAD

**Issue by Cethyrion** [DarkflameUniverse/DarkflameServer#140]
To preface we're currently looking into our server setup to find out if it is an issue on our end. If any solution is found, it will be posted here.

When creating a new character with or without a custom name, the three word username is being inserted into the charinfo table as "INVALID" this has the side effect of causeing any future three word usernames to register as "In Use" which blocks the creation of new characters. if the INVALID character is deleted, a custom name is approved, or a value is manually inserted into the database, then the situation appears to be fully resolved

<img width="501" alt="invalid" src="https://user-images.githubusercontent.com/23558207/145328421-788e6674-917f-413a-804e-3265c2b53f00.PNG">
<img width="479" alt="invalidwithoutcustom" src="https://user-images.githubusercontent.com/23558207/145328424-48bdcd03-8f51-49de-8d23-2080ad4894a1.PNG">
<img width="723" alt="use a diff name" src="https://user-images.githubusercontent.com/23558207/145328428-1122c9e6-4b05-4288-9317-c41ed8eb61d3.PNG">

**Comment by averysumner** [comment]
You have setup your server incorrectly. You must put the res/names folder from the client in your build/res folder.

**Comment by Cethyrion** [comment]
thank you avery! aparently we don't know how to read directions!

**Comment by Cethyrion** [comment]
@averysumner if possible it might be good to clarify that when using the unpack tool, the output directory should be same as the original client

The confusion on our end arose because the unpacked files had been placed in a new directory, so when pulling from the new client/res folder it was missing anything that doesn't come from the .pk files.

**Comment by averysumner** [comment]
The output directory is not required to be the same as the original client.
