### ISSUE TITLE
Death Barrier doesn't work in Forbidden Valley when falling off the map

### ISSUE THREAD

**Issue by CloudyCrayons** [DarkflameUniverse/DarkflameServer#141]
step to reproduce:

I was able to get it to work right before the gate.

ps
if anyone is in this mess the best option is to just spawn a jetpack and fly back up with the commands
/gmlevel 8
/gmadditem 1727
just remember to go back to normal by
/gmlevel 0

**Comment by averysumner** [comment]
Better option is to do /die to reset your character.

**Comment by leolion3** [comment]
I've had this at multiple points in Forbidden Valley aswell. Had to smash myself a dozen times.

**Comment by DrOverbuild** [comment]
Happened as soon as I walked around my first time in forbidden valley. I tried to use a jetpack to get up but at one point as I got nearer to the top, the camera got stuck, stopped following my character, and I couldn't see where to land so I had to use /die anyway lol.

**Comment by Philosoap** [comment]
![image](https://user-images.githubusercontent.com/77870215/147206567-55ec4ff0-35d8-474d-8807-0d212f7a3a13.png)

This happened to me as well lol. Strange, because everywhere else has been working just fine
