### ISSUE TITLE
Can't get achievements in Cannon Cove Shooting Gallery

### ISSUE THREAD

**Issue by JohnMichaelRouth** [DarkflameUniverse/DarkflameServer#143]
You cannot complete the missions or achievements regarding cumulative points in CCSG
You cannot get the achievements for hits in a row in CCSG
Basically, all the achievements besides score are unobtainable

**Comment by EmosewaMC** [comment]
This is because they just arent implemented.  I will try to implement these this week

**Comment by EmosewaMC** [comment]
#381 resolves this issue
