### ISSUE TITLE
Cant Recieve Maelstrom Vacuum from Wisp Lee

### ISSUE THREAD

**Issue by JustProp** [DarkflameUniverse/DarkflameServer#144]
Im on the quest where I need to acquire a maelstrom cube from wisp lee to bring to hu where. Talking to wisp lee does not complete the step, thus you do not recieve the vacuum.

**Comment by EmosewaMC** [comment]
Just to make sure, the mission from Hu Where is not the mission that gives you a vacuum but rather it allows the player to begin a mission with Wisp Lee that gives the player a vacuum if they do not already have one.  Was the vacuum stored in your vault perhaps or maybe thrown away on accident?

**Comment by averysumner** [comment]
There is very limited description here. Closing this issue as it is stale and no extra communication has occurred. Reopen it if you’re still encountering this on the latest commit.
