### ISSUE TITLE
Can't build on Ubuntu 20.04.6 LTS x86 Server

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#1448]
### Discussed in https://github.com/DarkflameUniverse/DarkflameServer/discussions/1441

<div type='discussions-op-text'>

<sup>Originally posted by **MustacheMan2** February  2, 2024</sup>
Whenever it gets to building RenderComponent.cpp, this happens.
![image](https://github.com/DarkflameUniverse/DarkflameServer/assets/48499798/1dca5543-a03a-4aae-8518-3c66930f93df)

Tested locally using WSL and it was able to build. If this answers anything, this server has been around since day one of DLU's launch, so it could be something wrong with the db or some outdated dependencies, though everything seems up to date. Happens on a fresh clone as well. Unsure whether or not this is specific to this machine.</div>

**Comment by EmosewaMC** [comment]
This is due to wsl20.04 using a build of gcc that is too old to support c++20 features.  The fix is upgrading your wsl instance to 22.04 so you can use gcc versions which support c++20 features.

**Comment by MustacheMan2** [comment]
> This is due to wsl20.04 using a build of gcc that is too old to support c++20 features. The fix is upgrading your wsl instance to 22.04 so you can use gcc versions which support c++20 features.

Awesome thanks. Considering this just became an issue recently, it may be a good idea if someone made note of this in the readme.
