### ISSUE TITLE
World Server will not reconnect to Chat Server

### ISSUE THREAD

**Issue by jelimoore** [DarkflameUniverse/DarkflameServer#145]
**Expected Behavior**
When connection to Chat server is lost, the World server attempts to reconnect periodically

**Current Behavior**
When Chat Server crashes or otherwise stops running, all current World Server instances will lose Chat Server connectivity. Ironically, Chat itself still works but Friends and Teams quit working. However, any new World Server instances started after the Chat Server have been restarted have functional Friends and Teams features.

**Possible Solution**
When connection to the Chat Server is lost, periodically poll for Chat Server to reconnect.

**Steps to Reproduce**
1. Start MasterServer
2. Join world
3. Kill ChatServer
4. Restart ChatServer
5. Attempt to add a friend

**Your Enviorment**
Ubuntu 20.04 LTS, x86 CPU VM, VMWare ESXi 7.0 U2

**Comment by DarwinAnim8or** [comment]
This is a good point, I'll look into it

**Comment by udop1** [comment]
Just to add to this, I have a screenshot of what happens when someone tries to add friends. (This is using WSL, Ubuntu 20.04 LTS). Hopefully, it's helpful somewhat.

![image](https://user-images.githubusercontent.com/52384714/145637067-968c0598-ebe9-45bd-b5ff-9f27a6062fa7.png)

**Comment by EmosewaMC** [comment]
This should be resolved on the latest commit.  If the issue persists please re-open
