### ISSUE TITLE
can anyone help me set this server up on windows

### ISSUE THREAD

**Issue by cypherpunks132** [DarkflameUniverse/DarkflameServer#148]
i am currently stuck at "Setting up the environment"
to be specific the database section
i am using windows 10 and wsl and i am using the windows version of mysql workbench
any help would be helpful

thx in advance

**Comment by padraicheaton** [comment]
I found this vid on youtube incredibly helpful for setting this all up on windows: https://www.youtube.com/watch?v=mDGoV5AYaDo&t=915s

**Comment by NealSpellman** [comment]
Our issues channel is not a place to ask for help setting up the server. Please refrain from opening issues like this and instead ask for help elsewhere.
