### ISSUE TITLE
BUG: crash dumps no longer contain function definitions

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#1515]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

Main

### Issue Description

Title.  Crash dumps used to contain function definitions but they were removed when visibility was standardized.  

### Reproduction Steps

Crash the server with /crash
Observe there are no function names

### Expected Behavior

Function names from the stack exist

### Environment

Non-windows builds

**Comment by jadebenn** [comment]
PR compiling now. Had to partially revert the visibility changes - only inlined functions are hidden now. That _probably_ won't meaningfully affect anything, and although it does personally bug me to have the inconsistency between Unix and Windows, it makes sense here.
