### ISSUE TITLE
Bullhorn not working on certain enemies

### ISSUE THREAD

**Issue by starjones101** [DarkflameUniverse/DarkflameServer#152]
If you're not familiar with the **Bullhorn**, it leaves enemies stunned. Here's a clip showing that it wasn't working on **Spiderlings** in Battle of Nimbus Station (BoNS), however it seems to work outside of BoNS. After further testing, I've found that **Stromling Admirals** can still attack while stunned but only if they've started their attack (video below). It also seems that **Stromling Apes** aren't effected by the Bullhorn.

Spiderlings: https://streamable.com/pypj7a
Strongling Admiral: https://streamable.com/bzrilh
Stromling Ape: https://streamable.com/tsdfre

**Comment by NealSpellman** [comment]
Not sure on the first two, someone else can comment on those.

Apes and other minibosses are stun-immune, even if the effects show up. This is not a bug.

**Comment by starjones101** [comment]
> Not sure on the first two, someone else can comment on those.
> 
> Apes and other minibosses are stun-immune, even if the effects show up. This is not a bug.

Admirals do seem to get stunned it's just that if they've started an attack the attack keeps going. I had no trouble stunning spiderlings in Avant Gardens but for some reason in BoNS they were able to resist the stun. Thanks for clearing up the apes! :)

**Comment by Wincent01** [comment]
The Spiderlings in Battle of Nimbus Station are also immune to stuns, along with a few other Spiderling variants:
https://github.com/DarkflameUniverse/DarkflameServer/blob/82a1c8a765f73244c88bb088a16db8e57808c69a/dScripts/CppScripts.cpp#L380-L381
https://github.com/DarkflameUniverse/DarkflameServer/blob/82a1c8a765f73244c88bb088a16db8e57808c69a/dScripts/AgDarkSpiderling.cpp#L5-L8
