### ISSUE TITLE
BUG: bouncer pad at avant gardens monument is not possible for a pet to walk to

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#1533]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

HEAD

### Issue Description

title.  really just an issue tracker for me.

### Reproduction Steps

pull pet out, walk it to the bouncer, it does not walk onto and activate said bouncer

### Expected Behavior

activates bouncer

### Environment

All

**Comment by jadebenn** [comment]
Interesting. I think this may have been unintentionally fixed in the PetFixes branch, as I remember using it successfully there.

**Comment by TAHuntling** [comment]
> Interesting. I think this may have been unintentionally fixed in the PetFixes branch, as I remember using it successfully there.

Can I get confirmation whether it was fixed in the PetFixes branch?

**Comment by EmosewaMC** [comment]
> > Interesting. I think this may have been unintentionally fixed in the PetFixes branch, as I remember using it successfully there.
> 
> Can I get confirmation whether it was fixed in the PetFixes branch?

your branch did not fix that.

**Comment by EmosewaMC** [comment]
> > > Interesting. I think this may have been unintentionally fixed in the PetFixes branch, as I remember using it successfully there.
> > 
> > 
> > Can I get confirmation whether it was fixed in the PetFixes branch?
> 
> your branch did not fix that if it was broken on jades branch. Your issue fixed taming and did not touch anything to do with pet navigation in the world

To clarify, this is an issue solely for me to work on as it is a navmesh issue, which only I can edit.
