### ISSUE TITLE
Crash to login screen when loading properties

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#156]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

I have had a user load a property of mine with a small brick model and a few regular models and crash to the login screen every time, regardless of what their patchserverip is set to. I tried loading the property on a different device that didn't have the models processed and it also could not load it. Someone else was able to load it though, but they crashed once. I removed the brick model and the stuck user was then able to load the property. Another user is now crashing while loading a different property, but that property has only regular models, so this is inconsistent and I have no way to know what causes it

### Reproduction steps

Join someone else's property for the first time, with brick models if possible.

### Expected Behavior

load without crashes

### Environment

Ubuntu Server 20.04.03

**Comment by BustosAndrew** [comment]
Almost the exact same issue as #80.

**Comment by Saymoan** [comment]
Can confirm this issue. Temporary fixes include deleting the data on a player's property or editing their character's charxml file to change what world they are in.

**Comment by MustacheMan2** [comment]
changed the UGC server ip to mine and it helps a lot, but I still can't load the property, my client log states HTTP error 0, and can't download the hkx and lxfml manifest for the model.

**Comment by averysumner** [comment]
Has this issue persisted?

**Comment by simondumalski** [comment]
@averysumner Sure has. Community has found some ways to make it slightly less annoying (a Discord bot that has a command to "unstuck" a player, a python script to "unstuck" the player) but it is still an issue.

**Comment by EmosewaMC** [comment]
Some property fixes have been pushed to main.  Could yall give this another test and see if the issue persists or if it has been fixed?

**Comment by Racater** [comment]
Yes, the issue is still present. Here are the client logs:
[log_bug.txt](https://github.com/DarkflameUniverse/DarkflameServer/files/8419966/log_bug.txt)

The log server-side are:
> [05-04-22 16:08:44] [PlayerContainer] Added user: Racater (1152921508901814274), zone: 1150
> [05-04-22 16:08:44] [ChatServer] Asked for ignore list, but is unimplemented right now.
> [05-04-22 16:08:44] [HandleQueryPropertyData] Entity (9628) requesting data
> [05-04-22 16:08:44] [Properties] Getting property info for 1150
> [05-04-22 16:08:44] [SendDownloadPropertyData] (288300748454049520) sending property data (1)
> [05-04-22 16:08:44] [HandleQueryPropertyData] Entity (3315) requesting data
> [05-04-22 16:08:44] [Properties] Getting property info for 1150
> [05-04-22 16:08:44] [SendDownloadPropertyData] (288300748454049521) sending property data (1)

**Comment by EmosewaMC** [comment]
> Yes, the issue is still present. Here are the client logs (I logged in directly into an affected property): [log_bug.txt](https://github.com/DarkflameUniverse/DarkflameServer/files/8419966/log_bug.txt)
> 
> The log server-side are:
> 
> > [05-04-22 16:08:44] [PlayerContainer] Added user: Racater (1152921508901814274), zone: 1150
> > [05-04-22 16:08:44] [ChatServer] Asked for ignore list, but is unimplemented right now.
> > [05-04-22 16:08:44] [HandleQueryPropertyData] Entity (9628) requesting data
> > [05-04-22 16:08:44] [Properties] Getting property info for 1150
> > [05-04-22 16:08:44] [SendDownloadPropertyData] (288300748454049520) sending property data (1)
> > [05-04-22 16:08:44] [HandleQueryPropertyData] Entity (3315) requesting data
> > [05-04-22 16:08:44] [Properties] Getting property info for 1150
> > [05-04-22 16:08:44] [SendDownloadPropertyData] (288300748454049521) sending property data (1)
> 
> I made sure to have a running ugc server with 404.

What does the python server logs show?  They should show some logs to say a connection was made / refused.  Multiple people can confirm that if the readme is followed, all properties load just fine.
