### ISSUE TITLE
horse mount 14535 does not work

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#157]
### Is your feature request related to a problem?

The mount does not go into my inventory, and if mailed it will disappear when dragging it to the inventory. This mount worked in the live game.

### Describe the solution you'd like

make it equippable and functional in the same way it was in the live game.

**Comment by averysumner** [comment]
Won’t fix, developer item. Feel free to PR if you know how to fix it.

**Comment by aronwk-aaron** [comment]
I am fixing this, and found that DLU's whole possessor component was not the real possessor component.

**Comment by aronwk-aaron** [comment]
resolved by #726
