### ISSUE TITLE
Spider Queen does not ground pound

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#158]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The Spider Queen will just stay motionless and not ground pound (except when leaping from the mountain).

### Reproduction steps

Fight the spider queen

### Expected Behavior

Spider Queen should ground pound often when the player is up close.

### Environment

Ubuntu server

**Comment by averysumner** [comment]
Please provide evidence from live of this occurring, and if possible video evidence of it not occurring on DLU.

**Comment by MustacheMan2** [comment]
This has been fixed in a recent commit. Closing...
