### ISSUE TITLE
BUG: models trashed from within the vault don't give you their bricks

### ISSUE THREAD

**Issue by Terrev** [DarkflameUniverse/DarkflameServer#1593]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

yes

### Issue Description

dragging a model from the vault to the trash says it will give you its bricks, but doesn't

### Reproduction Steps

trash a model in your vault

### Expected Behavior

it is smashed into bricks instead of simply being deleted

### Environment

5 pound burrito

**Comment by EmosewaMC** [comment]
I havent looked at this yet but id like to wager its just us only looking in 1 inventory vs all of them or something.
