### ISSUE TITLE
BUG: Mythran messages don't carry across worlds?

### ISSUE THREAD

**Issue by MajickTek** [DarkflameUniverse/DarkflameServer#161]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

I had to restart my server to apply core changes. Before I restarted, my shutdown process was:

```
/setanntitle The server is shutting down.
/setannmessage But don't panic! We'll be back.
/announce
/shutdownuniverse
```

As you can see, two Mythran announcements should have been sent. The "Don't panic" and the "Server is shutting down in 10 minutes" one. However, all of my players say they didn't receive the messages.

### Reproduction steps

Send an announcement as a Mythran/Admin account with GM Level 9.

### Expected Behavior

All players see the given announcement.

### Environment

Ubuntu 20.04 Server

Linode VPS (Dedicated base plan)

**Comment by averysumner** [comment]
I’m assuming your chat server isn’t working, as we have code that propagates announcements to all instances connected to the chat server.

https://github.com/DarkflameUniverse/DarkflameServer/blob/82a1c8a765f73244c88bb088a16db8e57808c69a/dChatServer/ChatServer.cpp#L196

**Comment by SilberComic** [comment]
its working fine for me, maybe there was a building error or something

**Comment by NealSpellman** [comment]
Given it's working fine for others, I'm closing this issue. Make sure your chat server is working and retest.

**Comment by MajickTek** [comment]
> Given it's working fine for others, I'm closing this issue. Make sure your chat server is working and retest. If the problem persists after you've confirmed that, we can reopen this.

I did fix this with a restart, i just didn't close that with an issue
