### ISSUE TITLE
BUG: team loot option not working

### ISSUE THREAD

**Issue by rlnt** [DarkflameUniverse/DarkflameServer#1612]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

sha256:ea884c80dbcbf532241fea068b1c846dcecf5e5e04944b4aad81891ae64730d2

### Issue Description

The team loot option doesn't seem to do anything. It's always the live accurate shared loot.
The setting in `sharedconfig.ini` called `default_team_loot` is set to `1` which means `Free for All`. In the game, it does indeed set the option to `Free for All` but it's not working. Loot will still spawn for each character in the team and you can't pick it up. It has no difference from when you set it to `Shared Loot`. Even switching between the two settings will not take any effect.

We had some *very* rare occasions where the loot was `Free for All` after opening the team but it seems to be rather random. We didn't find a way to achieve the same result on purpose yet. On all the occasions where we had `Free for All` loot, the team was created by the same person but that's not always the case.

### Reproduction Steps

1. Set the `sharedconfig.ini` config option `default_team_loot` to `1` (default value)
2. Create a team in the game (we are 3 if that matters)
3. Check the team settings and make sure `Free for All` is selected as specified in the config
4. Farm some enemies to see that they still drop character-specific loot.

### Expected Behavior

The team setting should affect the gameplay.

### Environment

DarkflameServer is running on the official Docker image in the provided docker-compose setup with the database and the Nexus Dashboard.

The containers are hosted on a Debian 11.9 system.
```
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye
```

The DarkflameServer was installed yesterday and all the environment variables are default except for the ones you have to change like the IP, the account manager secret, and the database password.
Only a single config option has been changed because of desync which is the `maximum_outgoing_bandwidth` inside the `sharedconfig.ini`. Its value has been set to `0` which fixed the desync.

**Comment by EmosewaMC** [comment]
Correct, this is by design in LU.  "Free for all" is actually dropping loot for each member of the team, as it did in live, and "Shared Loot" drops 1 enemies' loot for a member in a round robin style.  The text shown for the options isn't exactly clear on this, but that should be the behavior you are experiencing and it should currently be correct.

**Comment by rlnt** [comment]
Thanks for the clarification. I misinterpreted the behavior then. Thanks a lot for the fast response. This is solved now. :)
