### ISSUE TITLE
BUG: teams and friends list break frequently

### ISSUE THREAD

**Issue by Jcross666** [DarkflameUniverse/DarkflameServer#163]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

On occasion the friends list will wipe and the team function will break as well.

### Reproduction steps

There’s no way of recreating it, it just happens for no reason.

### Expected Behavior

The friends list will wipe and the team function won’t let you join or invite teams as you won’t get the invite.

### Environment

Windows

**Comment by NealSpellman** [comment]
This is due to the chat server crashing and never reconnecting. #145 is about that, so that should resolve this.

Your friends list doesn't actually get wiped. It shows as empty until the chat server is connected again.

**Comment by averysumner** [comment]
Actual issue is #145.
