### ISSUE TITLE
The Broadsider's schooner won't work 

### ISSUE THREAD

**Issue by Owagadugu** [DarkflameUniverse/DarkflameServer#164]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The schooner for the Buccaneer's Broadsider spawns in but does not do any damage to the enemy. Also on the Ubuntu command prompt there is this issue [CppScripts]: Attempted to load CppScript for 'scripts\EquipmentScripts\BuccaneerValiantShip.lua', but returned InvalidScript. 

### Reproduction steps

Get the Broadsider and use the third ability

### Expected Behavior

I expected the schooner to ram the enemy but it just sits there doing nothing 

### Environment

I was running it on Ubuntu.

**Comment by NealSpellman** [comment]
Yeah, this is an unimplemented script on the server side so it won't work until someone implements it.
