### ISSUE TITLE
Space Marauder gear not showing collectibles and bosses

### ISSUE THREAD

**Issue by starjones101** [DarkflameUniverse/DarkflameServer#165]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

I'm using space marauder rank 2 gear and a passive isn't working. Space marauder rank 2 & 3 have a passive of showing dangerous enemies and collectibles on the mini-map however this doesn't seem to be working. I assume this is known by the team, but I thought I'd post just in case it was forgotten. I haven't tested rank 3 gear.

### Reproduction steps

Equip rank 2/3 space marauder gear from paradox and check your map.

### Expected Behavior

Shows collectibles such as flags and shows dangerous enemies which I'm assuming means bosses. I found this on the wiki for the rank 3 gear: Each dangerous enemy appears as a purple blob/cloud on the minimap, but dark spiderlings (including elites and invaders) create false alarms.

### Environment

Windows Ubuntu

**Comment by EmosewaMC** [comment]
This is because of a missing behavior that just isn't set up yet on the server.
