### ISSUE TITLE
README Darkflame Universe setup is now drastically simplified

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#1687]
You no longer need anything aside from a LEGO Universe client and the [latest release](https://github.com/DarkflameUniverse/DarkflameServer/releases) to play the game.
Please check the updated [README](https://github.com/DarkflameUniverse/DarkflameServer?tab=readme-ov-file#setting-up-a-single-player-server) for steps on how to setup a single player server now.

**Comment by jadebenn** [comment]
Sorry, misclicked
