### ISSUE TITLE
BUG: Dragonmaw chasm fumes do no damage

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#172]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

when driving over the fumes under the refinery in Dragonmaw Chasm, they do not harm you.

https://user-images.githubusercontent.com/48499798/145666114-19f22435-90ba-4700-a38d-f3d0df76e56f.mp4

### Reproduction steps

Race in Dragonmaw chasm, drive over the fumes.

### Expected Behavior

the fumes should instantly smash you

https://youtu.be/phlZ-Ql8IJc?t=149

### Environment

ubuntu server

**Comment by MickVermeulen** [comment]
Assuming a missing script, thanks for the concise report (especially the video is helpful!). Will look into this.

**Comment by EmosewaMC** [comment]
This issue is not due to a missing script but rather a lot of misfiring is going on with phantom collisions in this race.  Hoping to investigate this further in the next few days

**Comment by MickVermeulen** [comment]
Can confirm @EmosewaMC , I did look into this but couldn't figure out why the phantom collisions weren't firing correctly
