### ISSUE TITLE
BUG: Satellite Beacons do not call down an air strike

### ISSUE THREAD

**Issue by simondumalski** [DarkflameUniverse/DarkflameServer#173]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The Buildable Satellite Beacons in Avant Gardens do not call down air strikes when built.

### Reproduction steps

Go to Avant Gardens and build a Satellite Beacon.
An airstrike will not be called/cause any damage.

### Expected Behavior

The Stromlings get nuked.

### Environment

Ubuntu 20.04
Oracle Cloud VPS
1 vCPU
1GB RAM

**Comment by averysumner** [comment]
Do you also have issues with turret builds not spawning from mechs?

**Comment by Saymoan** [comment]
@averysumner Initially I was, but after applying the fix, the turret builds started spawning, but no change for the satellite beacons.

**Comment by MickVermeulen** [comment]
Have confirmed this also doesn't work for me. It does play the cinematic for some of them but it doesn't kill the enemeis.

**Comment by averysumner** [comment]
Bumping priority as it's part of some somewhat important missions in Avant Gardens and it would be nice if it worked.

**Comment by averysumner** [comment]
Has this persisted?

**Comment by EmosewaMC** [comment]
I looked into the nd_avant_gardens_12_sen_camp.lvl file and noticed that the spawner for this QB does specify a custom script server and that the beacon itself has a script 887 attached to it which we do not have in the codebase yet.  The fix would likely be implementing the script that this object uses.

**Comment by aronwk-aaron** [comment]
the skill cast is based on lutriggers, which aren't fully implemented #710

**Comment by MustacheMan2** [comment]
This seems to have been half fixed recently. Now the proper animations play and the enemies in range are smashed, but the satellite in the sentinel camp causes enemies to drop items, which it should not, and the blasts happen twice. Unsure if players properly receive knockback when in range of the blast.

**Comment by aronwk-aaron** [comment]
This bug has been fixed, if other issues have arisen from the fix, please open separate issues for them
