### ISSUE TITLE
BUG: Dying in some zones shouldn't make you drop coins, but does

### ISSUE THREAD

**Issue by Terrev** [DarkflameUniverse/DarkflameServer#174]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

some zones (i.e. WBL worlds) shouldn't punish you with coin loss on death: https://youtu.be/K2s7U9_OMDU?list=PL9EFB8500E625ADC7&t=2960

this is determined by the PlayerLoseCoinsOnDeath values in ZoneTable

currently not implemented

### Reproduction steps

die in portabello (physically, not just spiritually)

### Expected Behavior

no coins drop

### Environment

computer

**Comment by averysumner** [comment]
Won’t fix, visiting portabello is not expected gameplay.
