### ISSUE TITLE
Banana bunches break in the trees

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#181]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When you hit a banana tree, the bunch breaks while up top, this can cause bananas to remain out of reach.

https://user-images.githubusercontent.com/48499798/145685988-5cfcb6ca-b364-4959-8a18-7320139f8a47.mp4

### Reproduction steps

walk up to a banana tree, and hit the trunk.

### Expected Behavior

The bunch should fall from the tree still intact, and then will drop the items when broken apart.

https://youtu.be/5OrRMmr4aUU?t=174

### Environment

ubuntu server

**Comment by NealSpellman** [comment]
This is another won't fix on our part, I think. @Wincent01 If you could comment, I don't exactly recall what the problem was initially that lead us to choosing to not make it accurate. Was it some AI/physics component for the banana falling? Something like that.

**Comment by Wincent01** [comment]
The bananas are special in that they use rigidbody physics. To make them bounce around on the floor correctly we'd need to do an entire physics simulation, which for a couple bananas ain't worth it.

**Comment by DarwinAnim8or** [comment]
@Wincent01 I think that we could solve this issue by spawning the bananas slightly lower maybe? (so that they don't end up on top of the tree I mean)

**Comment by averysumner** [comment]
I mean if someone wants to PR in full dynamics simulation I’m not stopping them… :P

**Comment by DarwinAnim8or** [comment]
Reopen this issue if issue persists after applying the latest update (#383 has been merged to main)
