### ISSUE TITLE
Trying to connect from outside LAN

### ISSUE THREAD

**Issue by jamesbsmith359** [DarkflameUniverse/DarkflameServer#182]
### 

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### Platform

WSL1

### Architecture

x86

### Error Logs

I’m having a friend try to connect from outside my LAN and so far he’s been unable to. My .ini files are set up with what should be my external ip, and I can connect from my local pc. I set up port forwarding in the router and allowed ports in my firewall, both tcp and udp. He set his boot.cfg up with my external ip and he can’t connect at all. When he uses my router ip in his boot.cfg he can log in and the server creates a session id, but he gets kicked back to the login page and a message asking for nickname/password. Any ideas?
<details>

Replace this line with the error logs.

</details>

**Comment by Orthestral** [comment]
Make sure in your `masterconfig.ini` that `external_ip` is set to your external IP. I was having this problem as well

**Comment by Wincent01** [comment]
This is a misconfiguration either in your ini files (see previous comment), or the network settings in your environment. This isn’t something we can support, closing.
