### ISSUE TITLE
Mission #1183 Colours don't match

### ISSUE THREAD

**Issue by starjones101** [DarkflameUniverse/DarkflameServer#183]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When collecting the green alien shell it gives you a yellow alien core & vice versa.

Video: https://streamable.com/08q4hf

### Reproduction steps

Mission #1183 "Close Encounter" Go to venture explorer and find the alien parts as shown in the video.

### Expected Behavior

When you collect the green alien shell you should receive object 12480.
When you collect the yellow alien core you should receive object 12481.

### Environment

Windows Ubuntu

**Comment by averysumner** [comment]
Are we sure it wasn’t like this in live?

**Comment by starjones101** [comment]
Honestly can't remember, but I doubt it because the colours don't match the item you receive.

**Comment by averysumner** [comment]
We’re using the same CDClient they should’ve though…

**Comment by Terrev** [comment]
This is live accurate: https://youtu.be/FCDnVftRWyM?list=PL9EFB8500E625ADC7&t=3079

**Comment by averysumner** [comment]
Hahah, of course it is. @starjones101 looks like you'll need a client mod
if you really want to fix this. Closing.

**Comment by starjones101** [comment]
Alrighty. Didn't realise live was also like that, doesn't go down well with the OCD.
