### ISSUE TITLE
BUG: Mission 769 - "The System Is Down" Missing Quickbuild

### ISSUE THREAD

**Issue by Vlathis** [DarkflameUniverse/DarkflameServer#184]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Mission 769, "The System is Down" requires building three pipes at the same time, however this is currently not possible as the third pipe's quickbuild is not present. The missing pipe is the one in the back of the platform on which this mission takes place, behind the horseman and next to the barrel. 

### Reproduction steps

- Accept Mission 769 - "The System is Down"
- Go to the lower platform next to Echs Ray, NPC 9680
- Search in vain for the third pipe needed to complete the mission

### Expected Behavior

The platform next to the Paradox Refinery, on which this mission takes place, should have three pipe quickbuilds, and building all three allows the mission to complete.

### Environment

Google Cloud

**Comment by NealSpellman** [comment]
There are three pipe quickbuilds; one is on the upper platform as you're heading to the Dragon Battle area, near a rock smashable overlooking the pipe area. That's the one you describe as missing, but it sounds like you didn't look there. Can you confirm this isn't the case?

**Comment by Vlathis** [comment]
> There are three pipe quickbuilds; one is on the upper platform as you're heading to the Dragon Battle area, near a rock smashable overlooking the pipe area. That's the one you describe as missing, but it sounds like you didn't look there. Can you confirm this isn't the case?

You are correct, I had missed that area and misremembered the location of the third pipe. It does appear to present afterall. Sorry for the false report.

**Comment by NealSpellman** [comment]
> > There are three pipe quickbuilds; one is on the upper platform as you're heading to the Dragon Battle area, near a rock smashable overlooking the pipe area. That's the one you describe as missing, but it sounds like you didn't look there. Can you confirm this isn't the case?
> 
> You are correct, I had missed that area and misremembered the location of the third pipe. It does appear to present afterall. Sorry for the false report.

Glad that solved it! It's been 10 years since most people have played the game and done these quests, so I get not remembering. Just make sure to double check around before reporting things!
