### ISSUE TITLE
BUG: Achievement Trigger: Forbidden Valley - "Gate Crasher"

### ISSUE THREAD

**Issue by Verathian** [DarkflameUniverse/DarkflameServer#186]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

![image](https://user-images.githubusercontent.com/46253834/145695603-b772b977-0349-448c-9de8-ffe55e79690f.png)
![image](https://user-images.githubusercontent.com/46253834/145695612-63253966-4ed0-4269-8408-44c72e1d9cfd.png)
The "Gate Crasher" achievement in Forbidden Valley (Mission ID 849) is failing to trigger for one of the two ways around the gate. Specifically, the jump-pad.

### Reproduction steps

In Forbidden Valley, attempt to sneak around the right side of the gate using the buildable launchpad.

### Expected Behavior

One of the ways to sneak around the gate is by building the launchpad, and this achievement will get one of its two steps. This is not occurring.

### Environment

Client: Windows 10 + Unpacked Client (unaltered outside of the steps provided by DLU).
Server: Ubuntu 20.04 running the recent DLU update with the corrected chat filter.

**Comment by Verathian** [comment]
Update:
During my play on another character, I jumped into the water in Nimbus Station for the first time (and got eaten by a shark). When this happened, "Shark Bite 1" was awarded as expected; however, the missing step of "Gate Crasher" (mission ID 849), as well as another achievement "Friend of the Ninja" (mission ID 848), was also rewarded. Screenshots below. Based on this information, I believe this may be some form of misplaced trigger (sorry if the terminology is off, fairly new to the LU code).

![image](https://user-images.githubusercontent.com/46253834/145699830-1f0951e4-b25f-4650-9e8f-a3bb4778b3d0.png)
![image](https://user-images.githubusercontent.com/46253834/145699845-a8080634-c1ab-4549-859e-94736f549c7b.png)

**Comment by MrPowerMac** [comment]
I also witnessed this while playing with a friend on my private server instance. He had triggered the jump pad but the achievement did not complete, and I shortly after accidentally fell into the water near the Gnarled Forest launch pad and received the achievements as described. I had yet to even visit Forbidden Valley with that minifig.

Both of our accounts were online at the same time when this occurred.

**Comment by EmosewaMC** [comment]
Issue here is an overlapping LOT number being used to check completion of these missions.  I have fixed the overlapping issue but am also looking into solving the issue with the gate not progressing.
