### ISSUE TITLE
FDB Checksum

### ISSUE THREAD

**Issue by averysumner** [DarkflameUniverse/DarkflameServer#188]
### Is your feature request related to a problem?

With the rise in hosted DarkflameServer instances, it would make a lot of sense to implement the built in FDB checksum verification feature of the client. Not only to prevent cheating, but to prevent possible undefined behavior caused by a CDClient mismatch between server and client.

### Describe the solution you'd like

Implementation of handler for packet [[53-04-00-01] (user session info)](https://lcdruniverse.org/lu_packets/lu_packets/world/server/struct.ClientValidation.html). This handler would kick the user if their checksum was invalid. The checksum on the server could either be a hardcoded config value or be automatically generated based on a provided CDClient.fdb.

**Comment by Jettford** [comment]
Fixed in #189

**Comment by MickVermeulen** [comment]
Overall very much agree that fixing this would be a good thing.
