### ISSUE TITLE
Not sure what is meant by "run the MasterServer binary"

### ISSUE THREAD

**Issue by padraicheaton** [DarkflameUniverse/DarkflameServer#19]
I may just be missing something / may not be well versed in this stuff. But I've made it all the way to the end of the guide, just not sure what you guys meant by "run the MasterServer binary". Should I be running the 'MasterServer.cpp'?

**Comment by udop1** [comment]
Yeah I’m near the end and having a similar issue. My MasterServer file is just a file (not even a .cpp like you suggest). So I'm not entire sure how I can execute it.

I’ve tried simple things like changing the file to an exe, or even trying it in a Linux environment to make it executable. But can’t seem to get it to work. Maybe I did something wrong with the build at the beginning? Not sure.
Any suggestions or pointers from anyone would be useful.

**Comment by lilithium-hydride** [comment]
> My MasterServer file is just a file (not even a .cpp like you suggest). So I'm not entire sure how I can execute it.


```bash
chmod +x MasterServer  # Makes the server file able to be executed
./MasterServer  # Executes the server binary

**Comment by Tyrobag** [comment]
> > My MasterServer file is just a file (not even a .cpp like you suggest). So I'm not entire sure how I can execute it.
> 
> ```shell
> chmod +x MasterServer  # Makes the server file able to be executed
> ./MasterServer  # Executes the server binary
> ```

When I try that it says that there is no such file or directory (and I am in the correct directory).

**Comment by udop1** [comment]
> > My MasterServer file is just a file (not even a .cpp like you suggest). So I'm not entire sure how I can execute it.
> 
> ```shell
> chmod +x MasterServer  # Makes the server file able to be executed
> ./MasterServer  # Executes the server binary
> ```

As @Tyrobag said above, it just says it doesn’t exist.

**Comment by lilithium-hydride** [comment]
If you've actually built the binary with CMake as per the readme, then it should be there. Try going through the steps again to make sure you didn't miss anything.

**Comment by Tyrobag** [comment]
> If you've actually built the binary with CMake as per the readme, then it should be there. Try going through the steps again to make sure you didn't miss anything.

It is there, it just has no file extension and the terminal doesn't seem to see it. Ubuntu only recognizes it as a "shared library" file, which it won't execute even when flagged as runnable.

**Comment by udop1** [comment]
Yeah. When I get home, I was going to try rebuilding it. In case something went wrong during my initial setup.

**Comment by lilithium-hydride** [comment]
> it just has no file extension 

I've never seen a Linux executable binary with a file extension, this is normal

> the terminal doesn't seem to see it

What does `ls` show? I've never heard of a file being visible with GUI programs but not in the terminal, that doesn't sound possible.

**Comment by Tyrobag** [comment]
> 

I got it to attempt to run. I'm not entirely sure but I think I was forgettingto run it under sudo before. While in the build directory I ran: sudo ./MasterServer -a

Unfortunately now I have this issue: https://github.com/DarkflameUniverse/DarkflameServer/issues/49 where it can't find the activity rewards table

**Comment by padraicheaton** [comment]
I've fixed this now by redoing all the steps using the WSL for windows rather than just raw windows, and it seems to have worked fine! Running into another issue now:

"[07-12-21 23:36:38] [MasterServer]: Got an error while connecting to the database: Unable to connect to localhost"

have tried going through everything in the issues here, but I can't find a solution. I'm running the mysql database locally on my computer, same as the server with each .ini file configured as:

mysql_host=localhost
mysql_database=lu_database
mysql_username=root
mysql_password=*******

**Comment by Pr3roxDLC** [comment]
is your database correctly set up?

**Comment by padraicheaton** [comment]
I'm pretty sure its all set up correctly, its reporting that its running and ready for connections, I've run all the sql I need to for the setup aswell

**Comment by Pr3roxDLC** [comment]
for the mariadb and the sqlite database?

**Comment by Pr3roxDLC** [comment]
have you tried setting up another mariadb user with root perms? thats what fixed it for me iirc

**Comment by padraicheaton** [comment]
yeah I've got both the mariadb setup and the sqlite setup, I'll try a diff user though

**Comment by padraicheaton** [comment]
followed everything in this vid here, absolute godsend of a walkthrough :D
