### ISSUE TITLE
BUG: Players can no longer create minifigs ( Username BUG )

### ISSUE THREAD

**Issue by IAmVolvic** [DarkflameUniverse/DarkflameServer#192]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When a new user joins the server and creates a new minifig. When they get to pick a name ( randomly generated or custom ) it will default back to " INVALID " meaning no one can create minifigs anymore.

### Reproduction steps

Create a new minifig try and pick a name click next and well
![image](https://user-images.githubusercontent.com/71038869/145702003-f79259d1-217d-4f96-ba53-490938f6a693.png)

### Expected Behavior

Depending on what the user picks ( Custom or Generated ) it should store that within the database and continue as normal.

### Environment

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

Mysql: Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

**Comment by NealSpellman** [comment]
Sounds like you missed a step in setup, such as issue #140. Can you confirm you've put the res/names folder from the client in your build/res folder?
