### ISSUE TITLE
BUG: Xpresso Speedbuff retained after dying

### ISSUE THREAD

**Issue by Mezalion** [DarkflameUniverse/DarkflameServer#194]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When dying short before the XPResso Speedbuff expires the Buff is kept after death. Not transfered when changing worlds tho.

### Reproduction steps

Use Xpresso
Die shortly before the Timer Ends
Respawn -> Eternal XPresso Speed

### Expected Behavior

It should delete the Buff on Dying

### Environment

VPS Ubuntu 20.something 
LCDRs Unpacked Client

**Comment by Mezalion** [comment]
Newly Discovered: After every death the Speed slightly increases.

**Comment by averysumner** [comment]
Possibly related to #235.

**Comment by ianRudnick** [comment]
This also seems to happen when using other speed boosts, like Daredevil flare guns skill 3. It also works in Nexus Tower: using the Paradox warps has the same effect as dying on increasing speed.

**Comment by EmosewaMC** [comment]
fixed by #856 from my testing.  Let us know if the issue persists and the reproduction case.
