### ISSUE TITLE
BUG: No death plane near Ninjago-Ruins

### ISSUE THREAD

**Issue by Mezalion** [DarkflameUniverse/DarkflameServer#195]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Falling of the Edge near Ninjago-Ruins does not smash Charakter. Probably just a missing death barrier or something

### Reproduction steps

Run of the Edge at Ninjago Ruins
Stand in thin air

### Expected Behavior

Die on Contact with Death Barrier

### Environment

VPS Ubuntu 20.something
LCDRs unpacked

**Comment by EmosewaMC** [comment]
The main issue here is that the death plane is not 640x640 units as the file name may hint, but is actually 640x640 _4x2 lego studs_ which means our death planes were 3.2 times smaller than they should be.
