### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by JustProp** [DarkflameUniverse/DarkflameServer#196]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Stromling Ape is not spawning in proper location in Gnarled Forest, specifically the first one you encounter, not the one by the imagination brick.

### Reproduction steps

Just visiting gnarled forest 

### Expected Behavior

He is appearing by the elephant pet area and Arthur Arbuckle, not at the X location near the Admirals.

### Environment

Ubuntu

**Comment by Wincent01** [comment]
That Stromling Ape has two spawning locations, the two you mentioned, closing.
