### ISSUE TITLE
ENH: Command to abandon missions

### ISSUE THREAD

**Issue by CloudyCrayons** [DarkflameUniverse/DarkflameServer#197]
### Is your feature request related to a problem?

Yes. Because some missions are not completable right now I think the community would like a command to abandon them, rather than have them staying in our mission lists until bugs get completed. 

### Describe the solution you'd like

/abandonmission <missionid#

**Comment by MustacheMan2** [comment]
/completemission <missionid> already exists provided you have the right gm set.

**Comment by Wincent01** [comment]
Believe this is a bad solution to the real issue of some missions not working. Introducing additional user commands also shouldn't be a go to solution, as it's not intuitive. Please open separate issues for each mission you've noted doesn't work. Unless we have any objections I believe we can close this.
