### ISSUE TITLE
BUG: Players becoming immobile randomly after logging in

### ISSUE THREAD

**Issue by brandonlee04** [DarkflameUniverse/DarkflameServer#199]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Sometimes when logging in a player is stuck in place
Cannot play without being teleported away from the area by an admin
![unknown234](https://user-images.githubusercontent.com/12752498/145726617-6ab1dfa7-90ad-4265-9881-117ecb3d19f3.png)
a

### Reproduction steps

When you login this sometimes happens 
This has occurred outside of Nimbus race track and in the Ninjago area

### Expected Behavior

Player should be able to move around and play

### Environment

Distributor ID: Ubuntu
Description: Ubuntu 20.04.3 LTS
Release: 20.04
Codename: focal

Mysql: Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

**Comment by NealSpellman** [comment]
Are there any more details? Any logs from affected users? This doesn't give us much to go on.

**Comment by IAmVolvic** [comment]
https://cdn.discordapp.com/attachments/917644671906377790/919643340390137856/LUP_Gif.mp4

**Comment by IAmVolvic** [comment]
> Are there any more details? Any logs from affected users? This doesn't give us much to go on.

I have logs but I would like to send it directly since it has exposed IPS

**Comment by NealSpellman** [comment]
> > Are there any more details? Any logs from affected users? This doesn't give us much to go on.
> 
> I have logs but I would like to send it directly since it has exposed IPS

Edit the logs and remove the personal information?

**Comment by IAmVolvic** [comment]
> > > Are there any more details? Any logs from affected users? This doesn't give us much to go on.
> > 
> > 
> > I have logs but I would like to send it directly since it has exposed IPS
> 
> Edit the logs and remove the personal information?

See I would do that but ah... since its a big server like 300 world logs was created lol

**Comment by IAmVolvic** [comment]
<img width="821" alt="Screenshot 2021-12-12 at 22 32 16" src="https://user-images.githubusercontent.com/71038869/145730336-8dba4efd-793d-4d8e-a6ac-4c0773d0b963.png">

**Comment by NealSpellman** [comment]
Throwing 300 world logs at us is not great either. Please sort through them so we don't have 300 to look at or wait until it happens again and give us only that specific log. Also confirm with the user that has the problem that there's nothing odd in their client log file.

**Comment by NealSpellman** [comment]
Talking with the team, this isn't a bug; this is what happens when the player is waiting on a player ready message. Their network and connection to the server may lag this out. In the screenshot attached to the base issue, there's no Nexus Tower launchpad guard which confirms it hasn't fully loaded in yet.

It should resolve after some time, whenever their network receives the game message. Players experiencing this may want to check their network and connection to the server to mitigate this. Closing this issue.
