### ISSUE TITLE
Server Crashing WSL Ubuntu

### ISSUE THREAD

**Issue by diminikov** [DarkflameUniverse/DarkflameServer#20]
Whenever I run my server with the command `sudo ./MasterServer` all that happens is this:
`
[05-12-21 20:29:18] [dServer]: Server is listening on localhost:2000 with encryption: 0
Fatal error -1
Stacktrace:
./MasterServer(+0x1ddcf)[0x55e0275badcf]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c)[0x7f1e174e238c]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3f7)[0x7f1e174e23f7]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa6a9)[0x7f1e174e26a9]
/mnt/c/Users/Dimitri/Desktop/DLU/DarkflameServer/build/_deps/mysql-src/lib64/libmysqlcppconn.so.9(+0x73a7b)[0x7f1e176bfa7b]
./MasterServer(+0x2382e)[0x55e0275c082e]
./MasterServer(+0x1701c)[0x55e0275b401c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f1e1726d0b3]
./MasterServer(+0x18b3e)[0x55e0275b5b3e]
`

**Comment by averysumner** [comment]
Is your database running and are your config files configured to use it?

**Comment by DomePB** [comment]
Couldn't open ./logs/MasterServer_1638769054.log for writing!
[06-12-21 06:37:35] [dServer]: Server is listening on localhost:2000 with encryption: 0
Fatal error -1
Stacktrace:
./MasterServer(+0x1ddcf)[0x55d9cf7badcf]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c)[0x7f790d99938c]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3f7)[0x7f790d9993f7]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa6a9)[0x7f790d9996a9]
/mnt/e/DarkflameUniverseServer/DarkflameServer/build/_deps/mysql-src/lib64/libmysqlcppconn.so.9(+0x73a7b)[0x7f790db76a7b]
./MasterServer(+0x2382e)[0x55d9cf7c082e]
./MasterServer(+0x1701c)[0x55d9cf7b401c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f790d7240b3]
./MasterServer(+0x18b3e)[0x55d9cf7b5b3e]

I basicly have the same problem and altough i can run MasterServer with -a to create an admin account

**Comment by leolion3** [comment]
This also happened to me after todays commits. It was still working yesterday in commit "2f064f0145c59f0612e7ed306d6b54e28b359eac".

**Comment by leolion3** [comment]
Ok so in my case I had set a symbolic link from "/var/lib/mysql/mydatabase" to a folder containing the database in a different location, which however accidentally also had a link to that directory (cyclic). Removing the cyclic dependency fixed it.

**Comment by diminikov** [comment]
avery was correct it was the databases
