### ISSUE TITLE
Egyptian Headdress 12780 is invisible

### ISSUE THREAD

**Issue by starjones101** [DarkflameUniverse/DarkflameServer#207]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When you equip the egyptian headdress you can't actually see it on your head

https://user-images.githubusercontent.com/95867412/145822870-2026c0a8-93fb-44bf-83ac-d1155fac44f2.mp4

.

### Reproduction steps

/gmadditem 12780 and equip it.

### Expected Behavior

You should see the helmet on your head

### Environment

Windows Ubuntu

**Comment by averysumner** [comment]
Client bug, closing.
