### ISSUE TITLE
BUILD: Error return when attempting to run Master Server

### ISSUE THREAD

**Issue by zedleplin** [DarkflameUniverse/DarkflameServer#208]
### 

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### Platform

macOS

### Architecture

x86

### Error Logs

I have followed the ReadMe and used a few YouTube tutorials to help me understand the process of setup. All runs smoothly until I attempt to start up the MasterServer. I have run it with and without sudo and both ways I get the error I have pasted into the details section. 

I tried to run the file from the GUI by double clicking the file (without the use of terminal so no '-a' flag) and I got this output: 

![Screenshot 2021-12-13 at 14 26 18](https://user-images.githubusercontent.com/95768324/145829941-94cfce3f-febb-4537-81df-535f43d48d6c.png)

From this and the terminal output in the Details tab I thought it may be a problem with symlinks not being set up properly so I redid them all as they read in the ReadMe file and just got the same error. I am unsure what to do from here.

Thanks

<details>
Patricks-MacBook-Air:build patrick$ ./MasterServer -a

dyld: Symbol not found: _ASN1_ANY_it

  Referenced from: libssl.1.1.dylib

  Expected in: libssl.1.1.dylib

 in libssl.1.1.dylib

Abort trap: 6

</details>

**Comment by averysumner** [comment]
You have misconfigured your server, you need to put the dynamic libs from _deps/mysql-src and _deps/zlib-build and put them in the same directory as your executable.

**Comment by zedleplin** [comment]
Thanks for the quick reply. What do you mean by _deps? I also don't know where I would find mysql-src. Would they be in /usr/local ?

**Comment by averysumner** [comment]
> Thanks for the quick reply. What do you mean by _deps? I also don't know where I would find mysql-src. Would they be in /usr/local ?

There should be a folder in your build folder named `_deps`.
