### ISSUE TITLE
BUG: Server High server cpu for worlds causes performance issues

### ISSUE THREAD

**Issue by IAmVolvic** [DarkflameUniverse/DarkflameServer#212]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Hello, I'll like to first point out this has been reported in many different ways but not 100% understood what the issue is.

After a while when a world is created the CPU starts to spike around 90% for one world this isn't only for one world this could be multiple at a time, I have documented this issue to Mick on discord and we both kinda figured it out but again not 100% sure where the source is.

Server screenshots:
https://cdn.discordapp.com/attachments/918708768202702899/920038743346397194/Screenshot_2021-12-13_at_20.45.09.png
After force closing some worlds:
https://cdn.discordapp.com/attachments/918708768202702899/920046793495035974/B9228F41-82CF-45C6-A144-6D5DA59195B1.jpg

WORLDS:

World - ID (Zone): 1300
CPU%: 89

World - ID (Zone): 1100
CPU%: 99.4

World - ID (Zone): 1400
CPU%: 95.2

World - ID (Zone): 2000
CPU%: 95

World - ID (Zone): 1800
CPU%: 20 - 40.4

Again I'll like to say thank you so much for your time and dedication in bringing this project to life!

-Volvic

### Reproduction steps

Have a large server with loads of traffic give it some time and you will start to see issues.

### Expected Behavior

Reasonable CPU usage

CPU I have no idea.

### Environment

**Dedicated Server**

Distributor ID: Ubuntu
Description: Ubuntu 20.04.3 LTS
Release: 20.04
Codename: focal

Mysql: Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

Ram: 128

Supermicro 8-Bay 2xE5-2670v3

**Comment by NealSpellman** [comment]
Putting this to low priority, given the only reporting for this has been from a server with hundreds of players which we do not endorse/support. Not an important or pressing issue to fix.

**Comment by averysumner** [comment]
Port issue in #214

**Comment by IAmVolvic** [comment]
After sitting in a world for around 3 or so hours, the world spiked to around 100% CPU usage, within the world I run **/metrics** to get a clear reading on what it could be, now I am still unsure of what it could be but here is what I found.

![image](https://user-images.githubusercontent.com/71038869/146021915-2317314b-a8b4-492e-a499-f30336b20562.png)
![image](https://user-images.githubusercontent.com/71038869/146021930-303f1f8d-4829-4fe5-8642-7dee74172c38.png)

**Comment by DarwinAnim8or** [comment]
Pushed an update to main, let me know if the issue persists.

**Comment by IAmVolvic** [comment]
> Pushed an update to main, let me know if the issue persists.

Test fix applied, time will tell thank you again.

Ill reply back here if anything is found.

**Comment by averysumner** [comment]
Has this persisted?

**Comment by EmosewaMC** [comment]
Yes this has persisted.  Ill do some investigation on the issue.

**Comment by DarwinAnim8or** [comment]
We'd need someone to post their metrics when this is happening again, but I remember from conversations with Volvic that the physics issue was resolved, and that the remaining high CPU just slowly crept up as a sum of tiny things taking up more and more time

**Comment by EmosewaMC** [comment]
> We'd need someone to post their metrics when this is happening again, but I remember from conversations with Volvic that the physics issue was resolved, and that the remaining high CPU just slowly crept up as a sum of tiny things taking up more and more time

Ive investigated this and the first issue is that we are not caching behavior parameter lookup stuff at _all_.  This is causing super high CPU and insane server lag when players are first using skills on a world since we load them as the player is attacking and this can cause lots of lag due to the sheer number of queries we are running.  Ill be working on caching this information properly and figuring out a way to load behaviors faster on their first use.  This may be an entirely different issue as well and unrelated unfortunately.

**Comment by EmosewaMC** [comment]
This can likely be closed if its resolved as my issue is not the same one as the one described here

**Comment by DarwinAnim8or** [comment]
> > We'd need someone to post their metrics when this is happening again, but I remember from conversations with Volvic that the physics issue was resolved, and that the remaining high CPU just slowly crept up as a sum of tiny things taking up more and more time
> 
> Ive investigated this and the first issue is that we are not caching behavior parameter lookup stuff at _all_. This is causing super high CPU and insane server lag when players are first using skills on a world since we load them as the player is attacking and this can cause lots of lag due to the sheer number of queries we are running. Ill be working on caching this information properly and figuring out a way to load behaviors faster on their first use. This may be an entirely different issue as well and unrelated unfortunately.

Hah, yeah. That was an issue in DLUv1 where this code originated from, so that's not surprising. 
I'll close this issue now as it's not the same cause.
