### ISSUE TITLE
Some racing missions not working

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#218]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

I've tried many times, they just don't work:

"No Wreckin'"
 
"Dragonscourge"

### Reproduction steps

take these missions when you get to them, race. Counters for the dragon eggs wont go up, and missions like No Wreckin' will not complete.

### Expected Behavior

missions should be completable as normal

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
This is partially or fully addressed by #366.
