### ISSUE TITLE
BUG: Forbidden Valley racetrack falling pathways do not appear

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#219]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

There should be some rocky pathways that fall down during lap 2 and 3 in dragonmaw chasm, they don't. However the collisions for them are there all 3 laps.

### Reproduction steps

race in dragonmaw chasm

### Expected Behavior

during laps 2 and 3 some rock pathways should be falling down

### Environment

ubuntu server

**Comment by BDimaurizio** [comment]
Here's a video of what it's supposed to look like. The ramp falls at around 2:00

https://www.youtube.com/watch?v=phlZ-Ql8IJc

**Comment by MustacheMan2** [comment]
The collisions seem to act pretty weird as well. I'm now noticing that the shape of them change here and there, like on lap 1 you could crash in one place in one match but during the next match that collision was not there (not to mention there should be no collisions by the flag at all on lap 1).

**Comment by DarkDengar** [comment]
+1, still seeing the very odd collisions on this track, mainly in the dragon area after the eggs and the non-damaging flames issue in #172.

**Comment by aronwk-aaron** [comment]
Superseded by #746 as this is a missing scripts isse
