### ISSUE TITLE
Mixed Cases on Linux

### ISSUE THREAD

**Issue by Capital-EX** [DarkflameUniverse/DarkflameServer#22]
The code attempts to load the maps using all lowercase, however the unpacked files are a mix of Title_Case and lower_case. Currently had to use a python script to recursively rename files from lowercase to uppercase.

**Comment by luxaritas** [comment]
If I remember correctly, capitalization is inconsistent between different clients. Need to verify this.

**Comment by jgkawell** [comment]
For anyone who doesn't want to fool with Python, this will recursively rename everything to lowercase: ` find . -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;`

Just be sure to run it within the directory you intend to update or point it at another directory.

**Comment by Jettford** [comment]
> Need

Yeah, afaik all unpacked clients (like clients built from unpacked packed ones should have 0 capital files names)

**Comment by godismyjudge95** [comment]
> For anyone who doesn't want to fool with Python, this will recursively rename everything to lowercase: ` find . -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;`
> 
> Just be sure to run it within the directory you intend to update or point it at another directory.

Also for those that stumble across this, to run this ^^ command you possibly need to install the rename tool (by running the following on debian/ubuntu):
```
sudo apt install rename
```

**Comment by Orthestral** [comment]
What's the equivalent on Arch?

**Comment by godismyjudge95** [comment]
> What's the equivalent on Arch?

I believe it's:
```
sudo pacman -Syu perl-rename
```
And then:
```
find . -depth -exec perl-rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;
```

**Comment by dddddddd207** [comment]
> What's the equivalent on Arch?

`perl-rename`

On Centos 7 it's `prename` in `EPEL`; I can't seem to find it in Centos 8 so I just copied it from https://gist.github.com/javiermon/3939556
