### ISSUE TITLE
BUG: Completed Battle Of Nimbus Station missions/achievements are re-completable

### ISSUE THREAD

**Issue by Tap-W** [DarkflameUniverse/DarkflameServer#223]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Upon completing any one-time achievements in the Battle of Nimbus Station (Timesmash or Solo), or the Wenn Wuzzit mission "Smash The Four Riders!" (ID 1249), completing the objective again will re-award the achievement/mission. It will only give the U-score and coin amount associated, and will not give the player any item awards, although it will add 1 achievement to the counter for LEGO Universe Commendation and Nexus Force Commendation, respectively. This has occurred just under 10 times on a private server.
I do not know if the previous Wenn Wuzzit missions have the same effect.

This video shows me getting the Murgle Blotch Timesmash and Solo achievements again after having already gotten them. Also shows that I don't receive the items again:
https://www.youtube.com/watch?v=4nbrNh-RBdM (4:02 to skip fighting)

### Reproduction steps

1. Complete any of the Timesmash or Solo achievements, or complete the Wenn Wuzzit mission "Smash The Four Riders!".
2. Fulfill the requirements again.

### Expected Behavior

The Timesmash and Solo achievements should not be able to be done again after being completed once.
The Four Riders mission should never reactivate upon beating the Four Riders another time.

### Environment

DLU server instance shown in linked video is running main as of commit d7294bd, on an Oracle Cloud VPS running Ubuntu 20.04 amd64. Client in use is DLU branded, NET_VERSION 171023.

**Comment by EmosewaMC** [comment]
From my observations what I believe is happening is that every time you reach a milestone wave, the missions are re-accepted for some reason even though they are achievements (achievements are just missions that are always active with the isMission flag set to false).  Looking into patching this if I can today
