### ISSUE TITLE
BUG: Cannot create Imagination Tea in Crux Prime Ninjago Area

### ISSUE THREAD

**Issue by MichaelFedora** [DarkflameUniverse/DarkflameServer#224]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

After having provided the Imagination Ninja with enough flowers, you should be able to interact with his teapot and create more tea.

While the "shift" button appears to be intractable, there doesn't seem to be any script on this server which provides you with the brewed tea. This makes the mission "Tea Time" (id `991`) not able to be completed unless you save the one Tea you recieve from the mission "For All the Tea in Ninjago" (id `976`), which I did not.

### Reproduction steps

Complete mission `976` ("For All the Tea in Ninjago") and attempt to brew more tea using the teapot in the Crux Prime Ninjago area.

### Expected Behavior

You should be able to make more tea.

### Environment

Windows client / ubuntu server

**Comment by metric-ambient** [comment]
This bug still exists on main branch
