### ISSUE TITLE
Bug: Lego Dice item does not complete rolling animation

### ISSUE THREAD

**Issue by ckawell** [DarkflameUniverse/DarkflameServer#237]
NOTE: This Bug is addressed [in this PR](https://github.com/DarkflameUniverse/DarkflameServer/pull/236). This issue report is to document the issue.

When the Lego Dice (12513) is rolled, the rolling animation appears in the sky, then disappears without completing the roll. This is because the logic for the roll is not implemented server side.

**Comment by NealSpellman** [comment]
You've failed to follow the issue template. Closing this and reopening with proper template.

**Comment by jakawell** [comment]
@NealSpellman The Bug template (and all templates other than "Feature") are broken. When folks try to open a non-feature issue they're forced to create a blank issue with no template.

**Comment by NealSpellman** [comment]
> @NealSpellman The Bug template (and all templates other than "Feature") are broken. When folks try to open a non-feature issue they're forced to create a blank issue with no template.

Yep, been reported to the member who wrote those but in the meantime you could copy from currently existing bug reports or use the template as it exists in the files to set it up. At the very least, some semblance of the same format would've been appreciated.

I've opened a new issue following the format; #238

**Comment by ckawell** [comment]
Just to clarify @NealSpellman, I was the one who opened the issue and PR, not jakawell. 
Because the templates were bugged I just wanted to get something out there real quick to provide more info for the fix in my PR. 
Thanks for the comment and I'll copy/paste in the future, but brace yourself for more people not following the template until it exists again :)

**Comment by jakawell** [comment]
Too many Kawell's lol 😉

**Comment by NealSpellman** [comment]
> Just to clarify @NealSpellman, I was the one who opened the issue and PR, not jakawell. Because the templates were bugged I just wanted to get something out there real quick to provide more info for the fix in my PR. Thanks for the comment and I'll copy/paste in the future, but brace yourself for more people not following the template until it exists again :)

You both really have to have usernames with -kawell, huh? :P My bad @jakawell, I autopiloted my response seeing the end of your username. 

And, even with templates bugged (as of writing this, they are fixed), we still expect users to follow the format. We're trying to keep issues properly formatted and including every detail our template asks for, as they help cut down on time other devs have to spend looking at it / researching / guessing missing details. This case wasn't super important, at least!

**Comment by ckawell** [comment]
Glad to see the fix rolled out so quickly, thanks!
