### ISSUE TITLE
BUG: LEGO Dice doesn't work

### ISSUE THREAD

**Issue by NealSpellman** [DarkflameUniverse/DarkflameServer#238]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Upon using the LEGO Dice item (id 7989), it will roll and disappear before it can complete. This is due to an unimplemented script.

### Reproduction steps

1. Give yourself the LEGO Dice item. (7989)
2. Use the item.
3. Notice that it disappears before completing.

### Expected Behavior

You should be able to roll the dice to see what number you get and, if rolling the required number for the achievement, get achievement progress.

### Environment

N/A

**Comment by jakawell** [comment]
Just referencing PR #236 addressing this.

**Comment by ckawell** [comment]
@NealSpellman this can be safely closed
