### ISSUE TITLE
How to approve usernames?

### ISSUE THREAD

**Issue by MasterEric** [DarkflameUniverse/DarkflameServer#24]
Is there an interface through which usernames can be approved? I was expecting it to be part of the Account Manager but I don't see it there.

**Comment by Lego6245** [comment]
I have “approved” names by editing the DB directly, but I’m not sure if there are other steps required to approve names.

**Comment by jgkawell** [comment]
@Lego6245 How did you do that? I'm not seeing them show up in the DB sometimes. When I create them and set them to valid it still doesn't work.

**Comment by Pr3roxDLC** [comment]
@jgkawell in your mariadb/mysql database there should be a database called charinfo, this contains the name info for each created minifigure, there is name and pending name, i did it by just copying over pending_name to name for all players

**Comment by MasterEric** [comment]
There's also someone who [submitted a contribution to the account manager](https://github.com/DarkflameUniverse/AccountManager/pull/5) so we'll see if that gets approved.

**Comment by jhayes2-chwy** [comment]
For *nix based platforms, this `approveThings.sh` script works just dandy:
```shell
#!/bin/sh

# Enter Server DB Info
dbhost="<database ip address>"
dbname="<database name>"
dbuser="<mysql_username>"
dbpassword="<mysql_password>"

# Approves Character Names
#Set the player's name to their pending name
mysql -h ${dbhost} -u ${dbuser} -p${dbpassword} -e "USE $dbname; UPDATE charinfo SET name = pending_name WHERE pending_name != \"\";"
#Set the player's pending name to an empty string
mysql -h ${dbhost} -u ${dbuser} -p${dbpassword} -e "USE $dbname; UPDATE charinfo SET pending_name = \"\" WHERE pending_name != \"\";"

#Approve all pet names
mysql -h ${dbhost} -u ${dbuser} -p${dbpassword} -e "USE $dbname; UPDATE pet_names SET approved=2;"

#Approve all player properties
mysql -h ${dbhost} -u ${dbuser} -p${dbpassword} -e "USE $dbname; UPDATE properties SET mod_approved=1;"
```

**Comment by averysumner** [comment]
https://github.com/DarkflameUniverse/NexusDashboard now exists and is intended to provide a fix for this issue. Closing.
