### ISSUE TITLE
ENH: Automated Server Deployment Tool

### ISSUE THREAD

**Issue by leolion3** [DarkflameUniverse/DarkflameServer#240]
### Is your feature request related to a problem?

Nooo

### Describe the solution you'd like

I created an automated build tool for the server. All it needs is the path of the client's `res` folder, the rest is done autonomously.
https://gist.github.com/leolion3/ccf654ab60c8e110c65ef948da6af461#file-buildserver-sh

The IP Address of the server is supplied in the last step. All other things are automated.

**Comment by averysumner** [comment]
I feel like a docker solution would be much better.

**Comment by Xiphoseer** [comment]
Closed by #90
