### ISSUE TITLE
Buccaneer monkey ability does not stun enemies

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#241]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The ability shows the animation that enemies are stunned but the enemies can still attack you, although they are occasionally stuck in place.

### Reproduction steps

Use Rank 3 Buccaneer Bandolier ability on some enemies

### Expected Behavior

The monkey should lock them in place, keep them stunned until it runs out of time and explodes, dealing damage.

### Environment

ubuntu server

**Comment by averysumner** [comment]
Sounds like an unimplemented script to me. Not entirely sure though.

**Comment by Stigurna** [comment]
This is happening to me too, and the 5 damage does not work either. It registers client side, so it kills enemies around it. However, no drops happen from the enemies, the player will take damage from seemingly nothing, and a few seconds later the enemies respawn with the same HP as they had before the monkey exploded.

**Comment by MustacheMan2** [comment]
I have now noticed that other stun abilities have also become useless and only display client side, such as the adventurer whip stun.

**Comment by EmosewaMC** [comment]
> Sounds like an unimplemented script to me. Not entirely sure though.

It is an unimplemented script.
