### ISSUE TITLE
BUG: In vehicle build mode, vehicle parts don't reappear in inventory

### ISSUE THREAD

**Issue by leolion3** [DarkflameUniverse/DarkflameServer#243]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When in vehicle build mode (rocket/car), removing a piece from the build should place it back in the inventory but it doesnt. The only way to get the piece back is by exiting build mode.

### Reproduction steps

- Enter rocket build mode
- add a nose cone or something 
- remove it from the build
- piece is gone.

### Expected Behavior

The pieces should be placed back in the player's inventory.

### Environment

Ubuntu 18.04 local server (physical machine), newest server version.

**Comment by averysumner** [comment]
Modular building has always been buggy. I'm pretty sure if you logout mid build you just lose everything that was in there. This is somewhat lower priority than most stuff though, it's not going to ruin your whole experience if you lose one nose cone (unless it's for that Mardolf mission).
