### ISSUE TITLE
Dragons do not ground pound

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#244]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [x] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Dragons of all kinds will only use their fire attack.

### Reproduction steps

Fight a dragon up close

### Expected Behavior

Dragons should occasionally fly up and ground pound to knock back players.

https://youtu.be/Fby_Iiz2gO8?t=257

### Environment

ubuntu server

**Comment by MrPowerMac** [comment]
I cannot confirm this behavior for Dragon Invaders on Crux Prime. Fought several of them last night alongside a friend and I did witness the ground pound attack.

**Comment by NealSpellman** [comment]
Given we've got two people saying dragons include this attack for them, I'm going to need more details from you, @MustacheMan2. This seems like your server specific issue. You've confirmed there's nothing in your server logs about missing scripts, you're running the latest DLU source and have fought them multiple times up close or in close proximity?

**Comment by starjones101** [comment]
Dragons on my server seem to ground & pound just fine, might be an issue for your server.

**Comment by NealSpellman** [comment]
Given we've got three separate confirmations that this is working fine, I'm closing this for now. If the issue still persists, please do the following:
- Confirm you're on the latest commit
- Check server logs when fighting dragons and see if there's any errors / messages in the logs about it
- Fight them at varying ranges; they will only sometimes use the ground pound attack.

We can reopen this if, after confirming all the above and checking the server logs, the issue still persists. Follow up with a comment here with more information after.
