### ISSUE TITLE
Stuck without imagination after talking to Bob 

### ISSUE THREAD

**Issue by mattachew12** [DarkflameUniverse/DarkflameServer#247]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### Platform

Ubuntu

### Architecture

x86

### Error Logs

When returning to Bob on the Venture Explorer after collecting the 6 imagination orbs. I level up and then get stuck after the zoom animation to see Sky Lane fails to run. At this point I am able to punch and use my mouse to rotate the camera vertically, but rotating the camera horizontally doesn't work and neither does moving. Logging out and in fixes the movement and camera, but then I still have 0 imagination out of 6, and breaking the cargo rocket boxes doesn't give any, which prevents proceeding through the tutorial.
I'm guessing it has something to do with 
[14-12-21 23:05:25] [GameMessages] Unable to get mission 173 for entity 1152921508901814274 to update reward in RespondToMission
but I may be wrong.
[ServerOutput.txt](https://github.com/DarkflameUniverse/DarkflameServer/files/7729970/ServerOutput.txt)

This doesn't seem to be something others are encountering, so it didn't seem right to treat it as a bug. I'm guessing my environment is the cause but I have followed the instructions completely. 
The only steps that weren't copy-pasted from the guide were the database and firewall setup. I also changed the bind-address of the database to 0.0.0.0 in /etc/mysql/mariadb.conf.d/50-server.cnf so that it could receive connections from other machines.
If it's helpful, I also have a complete list of the commands and steps I used in setup:
[ServerSetupCommands.txt](https://github.com/DarkflameUniverse/DarkflameServer/files/7730001/ServerSetupCommands.txt)

**Comment by Wincent01** [comment]
This is an issue which occurs when you haven't run the migrations for the CDClient, [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/migrations/cdserver); please read the README again. Closing.
