### ISSUE TITLE
"Got an error while connecting to the database: Unable to connect to localhost"

### ISSUE THREAD

**Issue by Drakonkinst** [DarkflameUniverse/DarkflameServer#25]
On the step where we run the MasterServer binary, I get this error. I suspect it has something to do with a misconfiguration of the .ini files from an earlier step. I'm new to SQL, could someone provide an example authentication info for `mysql_host`, `mysql_database`, `mysql_username`, and `mysql_password` for a locally hosted MySQL server?

Also, my MySQL server only opens one port. Should this port be 1001 to match the auth, or something different? Are the ports mentioned in the .ini files supposed to be used by MySQL or is that something different?

**Comment by Landshark77** [comment]
Had the same problem.  I resolved it by adding the two lines below to my /etc/mysql/my.cnf file.  After adding, restarted mariadb and was then able to connect.

```
[mysqld]
skip-grant-tables
```

**Comment by Drakonkinst** [comment]
Fixed this myself as well, just had to change the MySQL server port back to 3306 since I realized it has nothing to do with the .ini files. Thanks!
