### ISSUE TITLE
BUG: Character deletion still shows deleted character rarely

### ISSUE THREAD

**Issue by Rangnarok123** [DarkflameUniverse/DarkflameServer#250]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When you delete a character, after the confirmation screen and where you need to enter the password again to confirm the deletion, the character pops back up on screen with the same name.

However, the console confirms that the character has been deleted. If you log out of the account and log back in, that character is gone.

### Reproduction steps

Delete a character. Goes through the confirmation process.

### Expected Behavior

Character should disappear from the list of characters

### Environment

Linux/Ubuntu 20

**Comment by averysumner** [comment]
Known issue, VERY low priority.

**Comment by TheMatt2** [comment]
It seems the character will disappear if you restart the client.

**Comment by averysumner** [comment]
> It seems the character will disappear if you restart the client.

The character will disappear if you logout and log back in.
