### ISSUE TITLE
BUG: Wisp Lee mission not working

### ISSUE THREAD

**Issue by shatteredx17** [DarkflameUniverse/DarkflameServer#255]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The "Help Wanted" mission in Avant Gardens doesn't work. After collecting the maelstrom samples for Wisp Lee and accepting the rewards it doesn't give you a Maelstrom Cube and it doesn't show the mission as completed at the top of the screen.

### Reproduction steps

1. Daily mission from Hu Where in Avant Gardens launch area
2. Talk to Wisp Lee
3. Gather maelstrom samples
4. Accept rewards
5. No maelstrom cube

### Expected Behavior

Obtain Maelstrom Cube upon completion of mission

### Environment

Ubuntu

**Comment by averysumner** [comment]
Pretty sure this is a duplicate.

**Comment by sersorrel** [comment]
possibly of #144? though they don't even seem to get given the maelstrom vacuum.

**Comment by EmosewaMC** [comment]
This is fixed with #357 .  If its still broken report back here otherwise this can be closed

**Comment by averysumner** [comment]
Closing this issue as it is stale and no extra communication has occurred. Reopen it if you’re still encountering this on the latest commit.
