### ISSUE TITLE
Imagination replenish is permanent in nexus tower

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#256]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When you walk past the imagination nexus in nexus tower, you get your imagination replenished one point at a time. Currently this is permanent for the whole session no matter where you are in the tower once you walk past the nexus.

### Reproduction steps

walk to the imagination nexus, leave the area. You should still be getting your imagination replenished.

### Expected Behavior

The replenishing should stop once you leave the room.

### Environment

ubuntu server

**Comment by cooltrain7** [comment]
The beam is handled in `NtImagBeamBuffer` and it seems to be that `OnProximityUpdate` doesn't fire the `LEAVE ` state if you exit the room through the Sentinel or Paradox sides. Yet it does if you leave through the Venture or Assembly side.

**Comment by averysumner** [comment]
> The beam is handled in `NtImagBeamBuffer` and it seems to be that `OnProximityUpdate` doesn't fire the `LEAVE` state if you exit the room through the Sentinel or Paradox sides. Yet it does if you leave through the Venture or Assembly side.

Probably either an issue with the trigger volume or an issue with our physics engine. Or both.
