### ISSUE TITLE
Binoculars and Story Plaques are not tracked

### ISSUE THREAD

**Issue by Lego6245** [DarkflameUniverse/DarkflameServer#26]
The blue shimmer treatment is never removed, and the achievements panel does not update when interacting with either. So far I've confirmed this to be the case in both Advent Gardens and Venture Explorer.

**Comment by averysumner** [comment]
This was previously an issue but had been resolved. What platform are you on?

**Comment by Lego6245** [comment]
This is on a server running on Ubuntu 20.04 and a client running on Windows 10.

**Comment by ParadoxLULP** [comment]
i have the same problem. server is running on ubunto wsl, playing on windows 10 with lcdr/humanoids unpacked client

**Comment by ParadoxLULP** [comment]
dont know what i did, after applying the "patch" for survival and playing the required quest round for a minute, now it starts to count both

**Comment by Lego6245** [comment]
I believe this issue is the same as #46, and is fixed by re-running the migrations in the client DB. Will close this issue.
