### ISSUE TITLE
BUG: putting car on racetrack-join-platform causes soft-lock

### ISSUE THREAD

**Issue by SilberComic** [DarkflameUniverse/DarkflameServer#260]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

If you pick your car out of your inventory and put it on the joining platform for a race track (i tested it on nimbus, but should happen anywhere) you get spawned inside the car and are stuck until the server reboots

### Reproduction steps

-go to a race track join platform (where you normaly join a race)

-drag your car model onto the platform

-soft-locked

(if needed ill make a video)

### Expected Behavior

not being soft-locked

### Environment

Server is running on ubuntu

**Comment by EmosewaMC** [comment]
were you GM level 9 when doing this?  If so then this is a linked issue with #351

**Comment by SilberComic** [comment]
i think i was because a friend reported this issue to me and she was gm level 9 aswell and im not sure if i tested it with gm0 or not (i cant test it rn because the server hoster is having problems)

**Comment by EmosewaMC** [comment]
This is caused by being gm level 9 and pulling a car out and has been resolved on latest commit. If issues persist please re open the pr
