### ISSUE TITLE
BUG: Packs not rewarding items (Fright speed and Skeleton Rocket packs)

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#261]
### Make sure you've done the following:

- [x] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When opening a Skeleton Rocket package or a Fright speed car part pack, no items are given to the player.  This makes some achievements on Crux Prime impossible to complete due to this being the only way to get the parts.  The bugged packs simply disappear from the inventory without any notification.

The exact bugged packs are:
Skeleton Rocket (Cockpit, Rocket, Nose Cone) Package
Fright Speed Car Part Pack

### Reproduction steps

1) Obtain the aforementioned packs
2) Double click to open said packs and nothing will happen

### Expected Behavior

Rocket packages reward the specified rocket part and car pack rewards a random car part.

### Environment

Server: Ubuntu
Client: Windows 10

**Comment by Wincent01** [comment]
@Jettford is this fixed by the loot rework #216 ?

**Comment by Jettford** [comment]
Yes it is

**Comment by Jettford** [comment]
but that branch doesn't seem like it will ever get merged in so someone else should look into a fix for the current Loot gen

**Comment by averysumner** [comment]
> but that branch doesn't seem like it will ever get merged in so someone else should look into a fix for the current Loot gen

A fix for the current loot gen is literally, #216. Let's look into getting that merged.

**Comment by averysumner** [comment]
Closing as #216 has been merged. Reopen if issues persist.
