### ISSUE TITLE
BUG: Bat Lord 5-piece set bonus doesn't work

### ISSUE THREAD

**Issue by Tap-W** [DarkflameUniverse/DarkflameServer#263]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The 5-piece bonus for the Bat Lord set (restoring 3 health every time you kill an enemy) doesn't work and does not restore any health.
https://youtu.be/kWbpDonFXLs

### Reproduction steps

1. Equip all 5 pieces of the Bat Lord set.
2. Have any amount of health missing.
3. Kill something.

### Expected Behavior

3 health should be restored every time you kill something while wearing the Bat Lord set.

### Environment

Server instance running on Ubuntu 20.04 amd64

**Comment by averysumner** [comment]
This would require a custom script that is not currently implemented.

**Comment by TheMatt2** [comment]
Is this solved by #375?

**Comment by EmosewaMC** [comment]
Correct @TheMatt2 this can be closed
