### ISSUE TITLE
BUG: Remove friend doesn't remove friend

### ISSUE THREAD

**Issue by CommanderCookie** [DarkflameUniverse/DarkflameServer#267]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Using remove friend does nothing. No friend is removed or any changes to the database.

### Reproduction steps

- Get a friend or use a second account
- Add them as a friend
- Try to remove them

### Expected Behavior

The "friend" is removed.

### Environment

WSL 1 - Ubu 20.04

**Comment by EmosewaMC** [comment]
This is fixed in #347 from my testing however I am awaiting on #311 to be merged first so there are no conflicts.
