### ISSUE TITLE
BUG: normal green space jacket is turned into dark green space jacket when leaving char create

### ISSUE THREAD

**Issue by Terrev** [DarkflameUniverse/DarkflameServer#268]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

in char create:

![image](https://user-images.githubusercontent.com/21133460/146666143-fb36a17d-4acc-4827-86de-36ee37855ee9.png)

result upon saving minifig:

![image](https://user-images.githubusercontent.com/21133460/146666153-71336b33-d333-49f9-844d-589de9e704f1.png)

![image](https://user-images.githubusercontent.com/21133460/146666167-20139a71-dfb7-4e85-85b7-c4846b046d5f.png)

seems the server gives you the wrong item in this case, probably just a typo in that massive switch statement that handles it or whatever

it's possible there's more like this, I just stumbled into finding this one by chance

### Reproduction steps

choose a normal green space jacket in cc

### Expected Behavior

you get an item that matches that color+decal combo

### Environment

shoulder and back pain

**Comment by Terrev** [comment]
update - definitely more than just the space jacket, but don't have time to look into specifics atm unfortunately

![image](https://user-images.githubusercontent.com/21133460/146726202-be848279-a56c-4d5f-8a38-e5d73de93e44.png)

![image](https://user-images.githubusercontent.com/21133460/146726217-4bd6c36a-ead3-4b0f-ad23-6605c645bc38.png)

![image](https://user-images.githubusercontent.com/21133460/146726353-665f261f-7988-4fa3-8caa-d6e82177ae1f.png)

![image](https://user-images.githubusercontent.com/21133460/146726371-73204875-e0ce-4ccd-8aa6-c6760c44911e.png)

**Comment by Racater** [comment]
Can be closed
