### ISSUE TITLE
MySQL Cpp connection .dll error

### ISSUE THREAD

**Issue by Jovl** [DarkflameUniverse/DarkflameServer#27]
I thought I built everything correctly, but I seem to be getting an error related to a specific MySQL dll when I go to launch the MasterServer binary. 
![image](https://user-images.githubusercontent.com/17358208/144783227-6a6a954e-17ba-4892-b1e4-28765c8024a2.png)
Has anyone seen his error before?

**Comment by Jovl** [comment]
The same thing seems to happen for the ZLIB .dll when launching the WorldServer binary. The problem is "fixed" by moving the .dlls from the _deps directory, and into the build directory, but the windows for the servers don't stay open which I'm guessing means it doesn't actually fix the problem.

**Comment by averysumner** [comment]
Sadly fully static linking with mysql connector and zlib is not possible on windows. A bandaid solution would be an addition to the CMake file that puts these deps in place. Feel free to PR.
