### ISSUE TITLE
BUG: Team loot is broken

### ISSUE THREAD

**Issue by averysumner** [DarkflameUniverse/DarkflameServer#275]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Team loot is not live accurate.

### Reproduction steps

Kill any enemy that should have special loot depending on teams.

### Expected Behavior

Loot would be different if you were in a team.

### Environment

*

**Comment by Racater** [comment]
This may be related to #230

**Comment by Jettford** [comment]
Fixed, please close @averysumner
