### ISSUE TITLE
Boogie Down Achievement in Nimbus Station

### ISSUE THREAD

**Issue by stephanosstam** [DarkflameUniverse/DarkflameServer#278]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Dancing with Kant Dance, Sofie Cusion or Peppy Slapbiscuit in NS doesn't register to the achievement Boogie Down.

### Reproduction steps

1.Go near to one of the before mentioned npcs
2.Do any dance emote

### Expected Behavior

Dancing with the given nps should register to the Boogie down achievement

### Environment

Wsl 1 using Elocore's video tutorial

**Comment by godismyjudge95** [comment]
Can confirm this is bugged.
