### ISSUE TITLE
Connection From World Server Lost

### ISSUE THREAD

**Issue by j-usti-n** [DarkflameUniverse/DarkflameServer#28]
I successfully compiled the server (native windows) and configured the MySQL database. My user account authenticates correctly, but when I press play, I get a "Connection From World Server Lost" message after a few seconds.

I am getting `[timeStr] [dpWorld]: Error(s) occurred during navmesh load.` in the console, although I have ensured that navmesh folder is corectly configured

**Comment by j-usti-n** [comment]
caused by #31

**Comment by j-usti-n** [comment]
resolved with windows build fix

**Comment by Juliper** [comment]
what exactly have you done to fix it? Having the same problem. Don't have neough knowledge to understand what you mean ^^'
