### ISSUE TITLE
Anvil of armor and etc no longer work

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#286]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Anvil of armor and similar items no longer drop their powerups, broken from a recent commit, not sure which one though.

### Reproduction steps

place a cauldron of life, anvil of armor, etc. no power ups will drop.

### Expected Behavior

they should be dropping the powerups they say they will drop.

### Environment

ubuntu server

**Comment by metric-ambient** [comment]
Me and my friend also having this bug since updating last night.

**Comment by FutronBob** [comment]
Can confirm, been having this bug for the last couple days.  My guess would be from the loot table changes.

**Comment by averysumner** [comment]
Has this persisted?
