### ISSUE TITLE
BUG: Adventurer Passive "Shows the location of dangerous enemies and collectibles on your mini-map." does not work

### ISSUE THREAD

**Issue by MichaelFedora** [DarkflameUniverse/DarkflameServer#287]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The five-gear passive ability of Adventurer which "Shows the location of dangerous enemies and collectibles on your mini-map," does not work currently. I'm guessing this is because of a missing custom script.

### Reproduction steps

- Wear 5 pieces of adventurer rank 2 or 3 armor
- Go to a place where you haven't collected all of the flags
- Notice you can't see any flags on the minimap
- Go to crux prime while a named enemy is present
- Notice you cannot see them on the minimap

### Expected Behavior

The passive works

### Environment

Windows client / ubuntu server

**Comment by MustacheMan2** [comment]
Would like to add that neither set bonuses work for all Venture sets.

**Comment by Morthi** [comment]
same with the Space Marauder Sets

**Comment by MickVermeulen** [comment]
This is just not implemented yet, those passive abilities are still quite a mystery and most of them are simply hardcoded.

**Comment by EmosewaMC** [comment]
Is it possible to expand on what you mean by quite a mystery?  Do you mean that the functionality that allows the ability to function is hard to translate into a script?  I noticed some script files for faction classes but didnt see any scripts that used them.

**Comment by MickVermeulen** [comment]
It seems like most of them are hardcoded, we've been trying to find a system for them for a while but can't seem to find it in the source. This led to us hardcoding them, which isn't very tidy. I think most of the basic ones are implemented (e.g. the faction wide ones) but most of the class ones are missing. Maybe some of them were triggered by scripts, though, you're right about that. Can you link the scripts you've found?

**Comment by EmosewaMC** [comment]
I don't see any client sided scripts however when running a query on the scriptcomponent table, I noticed a bunch of names for faction scripts that are not being used.  Here is a list of the equipementtriggers I noticed.
```1031|scripts\equipmenttriggers\assemblyengineer1.lua|
1076|scripts\equipmenttriggers\sentinelKnight1.lua|
1077|scripts\equipmenttriggers\sentinelKnight2.lua|
1078|scripts\equipmenttriggers\sentinelKnight3.lua|
1081|scripts\equipmenttriggers\sentinelSamurai1.lua|
1082|scripts\equipmenttriggers\sentinelSamurai2.lua|
1083|scripts\equipmenttriggers\sentinelSamurai3.lua|
1086|scripts\equipmenttriggers\paradox2.lua|
1087|scripts\equipmenttriggers\paradox3.lua|
1090|scripts\equipmenttriggers\assemblyengineer2.lua|
1091|scripts\equipmenttriggers\assemblyengineer3.lua|
1179|scripts\equipmenttriggers\ventureDareDevil1.lua|
1180|scripts\equipmenttriggers\ventureDareDevil2.lua|
1181|scripts\equipmenttriggers\ventureDareDevil3.lua|
1182|scripts\equipmenttriggers\ventureBuccaneer1.lua|
1183|scripts\equipmenttriggers\ventureBuccaneer2.lua|
1184|scripts\equipmenttriggers\ventureBuccaneer3.lua|
1240|scripts\equipmenttriggers\assemblysummoner1.lua|
1241|scripts\equipmenttriggers\assemblysummoner2.lua|
1242|scripts\equipmenttriggers\assemblysummoner3.lua|
1294|scripts\equipmenttriggers\ImaginationBankNonFaction.lua|
1336|scripts\equipmenttriggers\ImaginationBankNonFaction.lua|
1375|scripts\equipmenttriggers\coilbackpack.lua|
1411|scripts\equipmenttriggers\sentinelSpaceRanger1.lua|
1412|scripts\equipmenttriggers\sentinelSpaceRanger2.lua|
1413|scripts\equipmenttriggers\sentinelSpaceRanger3.lua|
1415|scripts\equipmenttriggers\assemblyInventor1.lua|
1416|scripts\equipmenttriggers\assemblyInventor2.lua|
1417|scripts\equipmenttriggers\assemblyInventor3.lua|

**Comment by EmosewaMC** [comment]
Correction - Check /res/scripts/equipmenttriggers for scripts regarding faction bonuses

**Comment by MickVermeulen** [comment]
Ah right, thanks for looking that up!

**Comment by EmosewaMC** [comment]
So whats strange about this is the Treasure Finder _does_ show you collectibles on the minimap.  I've no clue as to why this works but it is being looked into.
