### ISSUE TITLE
"Your game is out of date."

### ISSUE THREAD

**Issue by Orthestral** [DarkflameUniverse/DarkflameServer#29]
![image](https://user-images.githubusercontent.com/76718984/144783843-82c3cead-9dee-4dfa-b8eb-5302914205f6.png)
Getting this error when trying to log into my admin account

I'm using version 1.10.64, but the server logs say "Received client version: 171022" every time I try to log in

**Comment by j-usti-n** [comment]
Open CMakeVariables.txt and set NET_VERSION=171022

**Comment by Orthestral** [comment]
Worked, thanks!
