### ISSUE TITLE
BUG: Some Items in Inventory Have no Sprite Until a World Transfer

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#295]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When logging into the game, some items in your inventory will have no sprite, but will still show how many are in the stack (if there are any in the stack.  Items without a stack number will just be invisible.) 

![LU inventory bug](https://user-images.githubusercontent.com/39972741/147144541-12c07569-7640-4a35-aa73-a8495c4188a9.png)
 

### Reproduction steps

1) Have a large amount of items in your inventory
2) Log out of the game
3) Log back into the minifigure and observe that part of your inventory has no sprites
4) Switch zones
5) Observe how now the entire inventory is loaded properly with sprites

### Expected Behavior

Inventory always loads all sprites

### Environment

Ubuntu

**Comment by Wincent01** [comment]
This is likely a client issue the server won't be able to mitigate, or it has something todo with the client not being connected to a patch server.

**Comment by averysumner** [comment]
Known client bug, happened in live.
