### ISSUE TITLE
Some properties are already cleared

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#298]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When going to some properties to claim them, they will appear already claimed, but you cannot build on it and the plaque is read like you are viewing someone else's.

![Lego Universe Screenshot 2021 12 23 - 00 34 30 20](https://user-images.githubusercontent.com/48499798/147193076-d41b9839-8c85-44d9-a91d-623356517feb.png)

### Reproduction steps

This seems inconsistent. Happened with Avant Grove on one character, and on Nimbus Rock for another. Just try going to claim properties.

### Expected Behavior

Personal properties must be claimed first, they cannot be already cleared when you load them for the first time.

### Environment

ubuntu server

**Comment by MickVermeulen** [comment]
Seems like this might be some race condition, what happens if you revisit the property? Will it become impossible for your character to claim this property afterwards?

**Comment by MustacheMan2** [comment]
> Seems like this might be some race condition, what happens if you revisit the property? Will it become impossible for your character to claim this property afterwards?

This is permanent for the character.

**Comment by MickVermeulen** [comment]
Thanks for clarifying!

**Comment by EmosewaMC** [comment]
While this issue does not inherently get fixed by #479, the issue will be prevented from happening in the first place by not allowing the player to claim properties on properties that are not their own.
