### ISSUE TITLE
"Preapproved" or Temporary Names have new line characters in them, breaking various UI elements

### ISSUE THREAD

**Issue by Lego6245** [DarkflameUniverse/DarkflameServer#30]
I can't imagine that it's intended for the First/Middle/Last pregen'd names to have aspects that cause them to break the UI in various ways, such as overflowing the upper left status UI and making the text super small in character select.

**Comment by averysumner** [comment]
What platform are you on? I recall this being an issue with differences in line endings.

**Comment by Lego6245** [comment]
My server is on Ubuntu 20.04 and my client is on Windows 10.

**Comment by Wincent01** [comment]
Format the txt files in the `names` folder to use Unix line endings `\n` instead of `\n\r`.

Allowing for both types of line endings would be a good addition. The code responsible for this can be found [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/dGame/UserManager.cpp#L38).
