### ISSUE TITLE
Using a speed boost on moonbase disables low gravity

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#300]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When using the speedy cap (and other speed boosts) on moonbase, the standard gravity returns.

### Reproduction steps

Use a speed boost such as a quicksicle or speedy cap on moonbase, the gravity will return. A relog fixes this.

### Expected Behavior

The low gravity should stay at all times (unless this was a live game bug I am unaware of).

### Environment

ubuntu server

**Comment by Jettford** [comment]
I think that this would have been a live game bug to be honest

**Comment by averysumner** [comment]
> I think that this would have been a live game bug to be honest

Doubt it.

**Comment by averysumner** [comment]
It seems odd that this would happen as if I recall correctly the gravity effect is client sided. Has this persisted?

**Comment by Jettford** [comment]
Gravity effect is still really weird and doesn't work sometimes.

**Comment by MustacheMan2** [comment]
Finding further issues with the low gravity. Sometimes it doesn't work on world load, and now doing a standard attack (not kick/air attack) disables it as well. Not sure if I should make another issue/edit this one.
