### ISSUE TITLE
BUG: Falling Into The Void in the Dragon Cave Doesn't Smash Minifigure

### ISSUE THREAD

**Issue by OfficialLahusa** [DarkflameUniverse/DarkflameServer#301]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When falling of the cliff in the forbidden valley dragon cave instance, the minifigure doesn't get smashed. After reconnecting, the minifigure will stand on the world bottom plane, alive.

![grafik](https://user-images.githubusercontent.com/34841946/147293661-3527fe4f-a2a7-43af-a64e-3dddf4e729ad.png)
_After reconnecting_

### Reproduction steps

1. Enter dragon cave instance in forbidden valley
2. Fall down

### Expected Behavior

Minifigure gets smashed

### Environment

Ubuntu

**Comment by OfficialLahusa** [comment]
Additional information: the /leave-zone command can be used to escape the instance

**Comment by averysumner** [comment]
leave-zone is a legacy workaround and should be removed soon. @Wincent01 thoughts?

**Comment by MickVermeulen** [comment]
All of the death plane scripts are a bit of a patch in themselves, I'm guessing a fix would be an even bigger patch.
