### ISSUE TITLE
Horsemen seldom move

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#302]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Maelstrom horsemen of all kinds seldom move except when wandering. This makes things like "Lead The Charge" next to impossible to do, and the end of BoNS very underwhelming.

### Reproduction steps

Try to lead a horseman towards Brick Fury.

### Expected Behavior

Horsemen should follow the player some.

### Environment

ubuntu server

**Comment by johntor** [comment]
I can confirm that happened to me twice but after restarting the client fixed that!

**Comment by MickVermeulen** [comment]
Do we have some video footage on the expected behavior? This is a bit subjective right now.

**Comment by MustacheMan2** [comment]
you'll find that their behavior here https://youtu.be/uhOFDQ0pweI?t=2080 is drastically different from live https://youtu.be/HAaknVJU3Ew?t=2220

**Comment by MickVermeulen** [comment]
That seems fair, thanks for clarifying!

**Comment by EmosewaMC** [comment]
How would one go about investigating this issue?  What files would be a good place to look at to diagnose the problem?

**Comment by MickVermeulen** [comment]
@EmosewaMC I think for this one it might be a misconfiguration of the entity's speed settings. You can check the movementAI component and check if the values that are loaded from the CDClient seem correct. If not; try to poke around in the CDClient and find a better variable for the horse speed.

**Comment by EmosewaMC** [comment]
Gotcha @MickVermeulen.  Ill poke around there and push a PR soon!

**Comment by EmosewaMC** [comment]
As far as I can tell the FV horse speed is in the database as "10" and is being properly set and cached as the speed so I guess this is now just a balance issue.  Will work on bringing the horse behavior closer to their live variants.

**Comment by EmosewaMC** [comment]
I believe this is actually an issue with how long the horse stand still after an attack.  Is there a spot I can look to see attack behaviors?  What files control an AI's combat and such?  I'm poking around BaseCombatAIComponent currently to see if I can find anything

**Comment by MickVermeulen** [comment]
The main components you should look at are the [BaseCombatAI](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/dGame/dComponents/BaseCombatAIComponent.cpp), [MovementAI](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/dGame/dComponents/MovementAIComponent.cpp) and [SkillComponent](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/dGame/dComponents/SkillComponent.cpp)s, I highly recommend looking at the prior two first as the skill system is a very deep rabbit hole :P

**Comment by EmosewaMC** [comment]
@MickVermeulen believe I have found the source of the issue however as I expected, the issue mentioned here affects all AI and not just horsemen.  Will link the PR when I have tested the changes more thoroughly.

**Comment by EmosewaMC** [comment]
I am testing some changes to AI behavior in a private server - will update here if the change works!

**Comment by EmosewaMC** [comment]
Fixed by #407 and can now be closed
