### ISSUE TITLE
BUG: Paradox Daily 75.000 Point Gnarled Forest Minigame Mission doesn't complete

### ISSUE THREAD

**Issue by OfficialLahusa** [DarkflameUniverse/DarkflameServer#303]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Cog Blammo's daily mission of achieving a score of 75.000 in the shooting gallery doesn't show up as finished, cannot receive rewards from him.
Rejoining the game worsens the situation, as the progress resets and doesn't track anymore.

![grafik](https://user-images.githubusercontent.com/34841946/147305577-be168cf1-2e83-4898-97e5-3fa1bd8c197b.png)
_Progress meter after rejoin_

### Reproduction steps

1. Pick up the daily quest series from Paradox vendor Cog Blammo on the nimbus plaza
2. Reach the part where you have to achieve a score of 75.000 points in the gnarled forest shooting gallery
3. Reach 75.000 points or more
4. Return to Cog Blammo
5. _Quest shows up as complete in the quest tracker at the top of the screen, but not in Cog Blammo's dialogue_
6. Restart game
7. _Score resets_
8. Click on Cog Blammo's dialogue for the same quest again
9. Play the minigame again
10. _Mission progress now doesn't track anymore and is uncompletable (?!?)_

### Expected Behavior

Quest always tracks correctly and shows up as completed in Cog Blammos UI

### Environment

Ubuntu

**Comment by metric-ambient** [comment]
I had this same glitch in Venture League

**Comment by MickVermeulen** [comment]
Can see how this is caused by the complete oddity that is the shooting gallery

**Comment by MrPowerMac** [comment]
Also observed this with a similar Paradox daily. using `/completemission` gives the reward but doesn't properly clear the mission.

**Comment by EmosewaMC** [comment]
#381 resolves this issue
