### ISSUE TITLE
BUG: Projectiles stun enemies or deactivate their AI completely

### ISSUE THREAD

**Issue by OfficialLahusa** [DarkflameUniverse/DarkflameServer#305]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Weapon used: Exceptional Flintlock Rifle of Blasting

Shooting enemies with this projectile weapon seems to deactivate their AI, or at least stun them for a while.
Attacking them again using any other weapon resolves the issue.
If enemies are shot during an attack animation (i.e. Ronin 3-Part attack), only the first hit actually does damage, and while the animation continues, the other hits have no effect.

![grafik](https://user-images.githubusercontent.com/34841946/147305775-f042be33-b4ff-42c7-aa54-efda7934ff36.png)
_Hanging out with some lobotomized admirals and pirates_

![grafik](https://user-images.githubusercontent.com/34841946/147306340-32109ce3-9bc6-45b1-9f6e-17caaa9c2219.png)
_Stromling Mech without AI_

### Tested Enemies
- Stromling Admiral (Full deactivation)
- Stromling Pirate (Full deactivation)
- Maelstrom Mech (Full deactivation if shot before receiving aggro, otherwise no effect)
- Dark Spiderling (Full deactivation)
- Dark Ronin (Full deactivation)
- Ronin Rider (Full deactivation)
- Stromling Ape (No effect)
- Maelstrom Dragon (No effect)

### Reproduction steps

1. Kill 60 stromling admirals to receive the weapon
2. Shoot at one of the enemies from the list above
3. Watch them turning into standby mode
4. Attack them again with any other weapon
5. AI functions normally again

### Expected Behavior

Enemy AI continues to behave as usual

### Environment

Ubuntu

**Comment by MickVermeulen** [comment]
Thanks for the thorough review, this indeed does not seem like it's supposed to happen. Suspecting this to be a behavior that we have not implemented correctly.
