### ISSUE TITLE
BUILD: Requires at least CMake 3.14

### ISSUE THREAD

**Issue by patrickrst** [DarkflameUniverse/DarkflameServer#308]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### Platform

Ubuntu

### Architecture

x86

### Error Logs

`FetchContent_MakeAvailable` is from CMake 3.14: https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable

```
CMake Error at CMakeLists.txt:78 (FetchContent_MakeAvailable):
  Unknown CMake command "FetchContent_MakeAvailable".


-- Configuring incomplete, errors occurred!
```

**Comment by averysumner** [comment]
I don't plan on removing the FetchContent calls, so a fix for this would just be editing the minimum version in CMakeLists.txt, easy PR if you want to do it.
