### ISSUE TITLE
BUG: Nimbus Station Client Crash on Loading Screen

### ISSUE THREAD

**Issue by NathanielB123** [DarkflameUniverse/DarkflameServer#315]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

All worked perfectly until I reached Nimbus Station. First time going there I loaded in fine but the game crashed after moving forwards a bit (when I say crash I mean the game application itself force-closed, the server stayed up). Restarting the game and attempting to play as that same character again leads to the game getting stuck at 66% on the loading screen for a few seconds, and then crashing. I tested this repeatedly after stopping and restarting the server, restarting my pc, and pulling the latest version of Darkflame, rebuilding from scratch and then backing up the database - every time the game crashed at 66% loaded.

<img width="640" alt="Desktop Screenshot 2021 12 28 - 09 25 03 96" src="https://user-images.githubusercontent.com/30476356/147551179-576ff73b-31cf-4161-a19c-deb86abb773b.png">

### Reproduction steps

I'm not sure exactly what causes the issue - it seems other people are able to load into and walk around Nimbus Station just fine.

### Expected Behavior

The game loads into Nimbus Station without crashing.

### Environment

Running the client on Windows 10, the server on WSL 2 (Ubuntu).

**Comment by averysumner** [comment]
Post client and server logs. Client logs can be found at C:/Users/USERNAME/AppData/Local/LEGO Software/LEGO Universe/logs

**Comment by NathanielB123** [comment]
Client logs:  [Log Files.zip](https://github.com/DarkflameUniverse/DarkflameServer/files/7792729/Log.Files.zip)
Server logs (I assume the "logs" folder in "build" is what you want - I deleted all the previous log files, then started the server, opened the game, got the crash at 66% and then zipped it): [logs.zip](https://github.com/DarkflameUniverse/DarkflameServer/files/7792730/logs.zip)

**Comment by averysumner** [comment]
I don't see anything obviously wrong in either of the logs. Has this issue persisted?

**Comment by averysumner** [comment]
Closing this issue as it is stale and no further communication has occurred. Feel free to open again if this issue persists.
