### ISSUE TITLE
Your game assets don't match the server.  Please logout and try again.

### ISSUE THREAD

**Issue by godismyjudge95** [DarkflameUniverse/DarkflameServer#32]
First of all, thanks for all your hard work getting this game up and running again.

I have followed all the steps in the readme.  After which I had a single issue with the "client out of date" bug (https://github.com/DarkflameUniverse/DarkflameServer/issues/29) which I resolved by changing the NET_VERSION and recompiling.

However, after I got logged in, created a character, and then clicked the start button I received the following error:
"Your game assets don't match the server. Please logout and try again."

**Comment by Lego6245** [comment]
If you unpacked the client yourself, it's likely that the server's map resources have a different casing from what the game is looking for. See #22 for more information. The solution is to change the casing on the server for the maps folder to be 100% lower case letters, which you can see a command for in the linked issue.

**Comment by godismyjudge95** [comment]
@Lego6245 that did the trick, thanks! although I also had to recreate my character (it loaded partially without the map files in place).

For future reference I installed the rename tool by running:
```
sudo apt install rename
```

And then cd'd into the maps directory:
```
cd DarkflameServer/build/res/maps/
```

And finally ran the rename command:
```
find . -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;
```

It took a really long time to finish running, but once that completed.  I just needed to log in and recreate my character to get it working completely.

Awesome work guys.

**Comment by windowk1d** [comment]
Just got the server running and I'm getting this error also.  "Your game assets don't match the server. Please logout and try again."  I tried the above method and tried the rename command but unfortunately still getting the same error.  Any ideas?  My client came unpacked.  Appreciate the help!!!

**Comment by Williemarsman** [comment]
I had this exact same problem, but I accidentally ran the renaming command in the overall /res directory, rather than just /Maps. And now when I try to run the server through "sudo ./MasterServer" it gets a ping from WorldServer that CDServer.sqlite cannot be opened. 

As a note, CDServer.sqlite no longer operates by that name, due to my botched command. So if I had to guess I'd say the issue is needing to rename it. Is this true? And if so, how?
