### ISSUE TITLE
Dragonmaw Chasm Racetrack isnt working as intended

### ISSUE THREAD

**Issue by SlothLogic** [DarkflameUniverse/DarkflameServer#320]
There are invisible walls inside of the racetrack where old parts of the map were supposed to break off into the map but arent there, including a ramp, and a wall that blocks the track here is a video [of the ramp](https://www.youtube.com/watch?v=phlZ-Ql8IJc&t=125s&ab_channel=jamessterV2) also the achievement and quest to destroy the dragon eggs arent registering

**Comment by SlothLogic** [comment]
also the purple flames that come out of the ground arent smashing the car like theyre supposed too

**Comment by MustacheMan2** [comment]
#219 #218 and #172 already describe these issues

**Comment by averysumner** [comment]
Closing, duplicate.
