### ISSUE TITLE
ENH: Add UNIQUE constraint to `charinfo.name` database column

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/DarkflameServer#321]
### Is your feature request related to a problem?

It looks like the `charinfo.name` database column currently has no `UNIQUE` constraint:
https://github.com/DarkflameUniverse/DarkflameServer/blob/0a7d9c46eba551b5e2f908caf9c689f4139bffb4/migrations/dlu/0_initial.sql#L18

But uniqueness seems to be enforced in the code here:
https://github.com/DarkflameUniverse/DarkflameServer/blob/0a7d9c46eba551b5e2f908caf9c689f4139bffb4/dGame/UserManager.cpp#L263-L266

### Describe the solution you'd like

Would it make sense to add a `UNIQUE` constraint, or is there something I am overlooking?

**Comment by averysumner** [comment]
This would make sense. I see you’ve made several issues similar to this one to fix small problems with simple solutions. It would be much better for you to create pull requests for these with your solutions. I’m not going to fix this myself as it’s not currently a problem, but feel free to make a PR for it.

**Comment by Marcono1234** [comment]
As much as I would love to contribute in a more useful way, I am neither familiar enough with this project and some of the used technologies, nor do I have the necessary development setup at the moment to test my changes or to verify that they don't introduce any unwanted side effects.

Feel free to close this issue at any point. Sorry for wasting your time on this one, and thank you all for the work on this project!

**Comment by Xiphoseer** [comment]
> Sorry for wasting your time on this one

Just to clarify: Nobody thinks a suggestion like this is a waste of the time to review it, rather a suggestion as small yet detailed as this is basically already a pull request, so it's very welcome and convenient if you file it as that directly

**Comment by EmosewaMC** [comment]
Added this suggestion in #356.
