### ISSUE TITLE
BUG: Hardcoded mysql localhost references

### ISSUE THREAD

**Issue by jelimoore** [DarkflameUniverse/DarkflameServer#324]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

I do not know the exact cause of this issue, I will search in the next few days to try to find the root cause.

Basically, when using a mySQL server on a different host than the DLU server, worlds will crash on launch and will crash occasionally while in-game which cascades and breaks the whole server (I believe it to be just the main world 0 that crashes). I am assuming that there are hardcoded mySQL refs to localhost for a number of reasons:

- In my config files, I specify the IP of my other SQL server, and can connect to it with the mySQL client on the DLU machine
- When starting up with the local mySQL shut off, the two initial world servers will crash with no explanation - just a log that says Quitting.
- When editing the charxml to set the last world info, it is not honored by the server - your charxml might say you are in zone 1100 but you get pushed to zone 1600. Editing the charxml on the locally-hosted mySQL server will put you back in zone 1100.
- When initially connecting to worlds other than AG (I believe this to be caused by the state of my charxml between the two SQL servers) the worldserver will immediately quit upon connecting with no logs in the console - again, just a generic Quitting message. However, once I am in-game, I can use either rocket pads/portals or the /testmap command to move between worlds just fine. This issue did not occur until I migrated SQL servers.
- All of these issues did not occur before I migrated my mySQL server off-host and onto another VM in my cluster. Both times, before and after, I was running the latest commit.

### Reproduction steps

1. Install DLU as normal on an Ubuntu/Maria host.
2. Export DB using mysqldump and import it on another host with MariaDB installed and listening on all interfaces.
3. Import DB on second host.
4. Change configuration files to point to new SQL server

### Expected Behavior

I expect that the DLU server would honor the SQL server set in the configuration file and not default to localhost.

### Environment

Ubuntu 20.04 Server, MariaDB 10.3.32-MariaDB-0ubuntu0.20.04.1

**Comment by averysumner** [comment]
We used an offsite MySQL server on our internal servers for the longest time, I suggest you look for these supposed references in the codebase. GitHub’s search function works quite well.

**Comment by averysumner** [comment]
Any updates on this?

**Comment by TheMatt2** [comment]
I note that you are saying the issue was if you edited the charxml to have your player load into a different world, the server did not seem to recognize this change. I'm wondering if the server is caching the charxml information somehow, and not actually referencing a local mysql server.

**Comment by averysumner** [comment]
> I note that you are saying the issue was if you edited the charxml to have your player load into a different world, the server did not seem to recognize this change. I'm wondering if the server is caching the charxml information somehow, and not actually referencing a local mysql server.

You must fully logout and then edit the charxml for any changes to take place. Your data is cached in memory from login to logout, then converted back to XML and pushed to DB on logout.

**Comment by averysumner** [comment]
Closing this issue as it is stale and no extra communication has occurred. Reopen it if you’re still encountering this on the latest commit.
