### ISSUE TITLE
BUG: Stuck loading between moonbase and starbase 3001

### ISSUE THREAD

**Issue by Legodude101** [DarkflameUniverse/DarkflameServer#326]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Launching from moonbase back to starbase 3001 and game didn't go to loading screen after rocket launched. Force closed the game and upon reopening game was stuck loading at 0% to Starbase 3001.

### Reproduction steps

Created new character on same server.
Went to moonbase and launched back to starbase 3001.
Game didn't go to loading screen after rocket launched.
Force closed the game and upon reopening game was stuck loading at 0% to Starbase 3001.

### Expected Behavior

Game should load starbase 3001 upon re-entry.

### Environment

Linux

**Comment by averysumner** [comment]
Send server and client logs.

**Comment by BigSadge** [comment]
Tested 3 round trips between Starbase 3001 and Moonbase, was not able to reproduce.

**Comment by averysumner** [comment]
Closing this issue as it is stale and no further communication has occurred. Feel free to open again if this issue persists.
