### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by SlothLogic** [DarkflameUniverse/DarkflameServer#327]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Item dropped from frakjaw wont let me use the ability that it gives [video](https://streamable.com/2pewir)

### Reproduction steps

equip and unequip and the ability flashes but it dissapears

### Expected Behavior

the ability should just stay there and let me be able to use it

### Environment

windows server

**Comment by ngaionice** [comment]
Should be the same issue as #168.

**Comment by Xiphoseer** [comment]
Can you give this bug a meaningful title?
