### ISSUE TITLE
Stromling Mech Quick Builds not Spawning

### ISSUE THREAD

**Issue by AnLUFan** [DarkflameUniverse/DarkflameServer#33]
Expected Behavior

  Stromling Mechs spawn their quick builds when defeated. Allowing the mission "Fortify the Front" to be completable.

Current Behavior

  Stromling Mechs do not spawn their quick builds when defeated. Making the mission incompletable.

Possible Solution

  The simplest short term fix would be to use the completemission command, but I do not know the id for "Fortify the Front"

Steps to Reproduce

  Kill a mech in Avant Gardens

Your Enviorment

  I have compiled and ran the server on Manjaro and WSL (both connecting to the same database but not simultaneously)

**Comment by averysumner** [comment]
I have never encountered this issue or heard of anything similar. Are you sure your CDServer db is intact? That’s the only thing I can think of…

**Comment by Wincent01** [comment]
Make sure you've run the CDServer migrations [here](migrations/cdserver). This should fix your issue, hope it helps!

**Comment by MrPowerMac** [comment]
This did not occur for me at all. Definitely try that CDServer migration.

**Comment by AnLUFan** [comment]
My CDServer was not configured correctly! I initially ran the scripts in order with DBeaver, but rerunning the same scripts with DB Browser fixed my problem.
