### ISSUE TITLE
BUG: Cant tame a pet

### ISSUE THREAD

**Issue by SmallDiva** [DarkflameUniverse/DarkflameServer#333]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

I installed the game normally and made the server public for me and friends and everything works so far but the only issue I have right now and others is that we cant tame pets and I get the message that the minigame failed to load to tame the pet and I cant figure out what the problem is. 

### Reproduction steps

Go to tameable pet 
try to tame 
cant tame

### Expected Behavior

The minigame to tame the pet should pop up 

### Environment

VM Ubuntu

**Comment by SmallDiva** [comment]
Sooo I was an idiot and it seems that i forgot to copy the BrickModels to the server whoops

**Comment by alecasper66** [comment]
So I have the same issue, except that I did copy the BrickModels to the server. Everything is working fine otherwise, except for when i go to tame a pet, and that exact message pops up. How do I get around that? :)
