### ISSUE TITLE
BUG: Race place car chassis quest takes the chassis from you

### ISSUE THREAD

**Issue by simondumalski** [DarkflameUniverse/DarkflameServer#336]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

For the quest in Nimbus Station that requires you to purchase a car chassis, and then use that chassis to build a car in a proceeding quest, it takes the car chassis from you, requiring you to go and purchase another.

### Reproduction steps

Start the quest (I can't remember the name)
Go buy a car chassis
Complete the quest
Chassis is gone

### Expected Behavior

Chassis is not gone

### Environment

Ubuntu

**Comment by Xiphoseer** [comment]
Can you give this issue a meaningful title, please?

**Comment by Xiphoseer** [comment]
IIRC this may be a bug from live, but I'm not sure. Fixing this may involve handling more cases in the Collect Item Task bitmask

**Comment by EmosewaMC** [comment]
This is intended based on information I have found from the database.  It is not clear from the mission but the data shows that mission 622 is of mission type 11 (MISSION_TASK_TYPE_ITEM_COLLECTION) and seeks to collect 1 of LOT 8129 (Car Chassis).

**Comment by Xiphoseer** [comment]
> This is intended based on information I have found from the database.  It is not clear from the mission but the data shows that mission 622 is of mission type 11 (MISSION_TASK_TYPE_ITEM_COLLECTION) and seeks to collect 1 of LOT 8129 (Car Chassis).

Actually, there is still `taskParam1` which has a different meaning for every task but for collection tasks does influence whether an item is consumed or not. It's probably an enum or bitset and might not be fully implemented.

**Comment by EmosewaMC** [comment]
> > This is intended based on information I have found from the database.  It is not clear from the mission but the data shows that mission 622 is of mission type 11 (MISSION_TASK_TYPE_ITEM_COLLECTION) and seeks to collect 1 of LOT 8129 (Car Chassis).
> 
> Actually, there is still `taskParam1` which has a different meaning for every task but for collection tasks does influence whether an item is consumed or not. It's probably an enum or bitset and might not be fully implemented.

Noted.  Will pursue implementing this if possible!

**Comment by TheMatt2** [comment]
> IIRC this may be a bug from live, but I'm not sure. Fixing this may involve handling more cases in the Collect Item Task bitmask

While I can't confirm or deny if this was a bug in live, this footage seems to show that the mission is supposed to let the user keep the car chassis.

https://youtu.be/BE4-6IId_YE?t=254

**Comment by EmosewaMC** [comment]
I have figured the issue out.  Fix will be in a PR.
