### ISSUE TITLE
BUG: Survival Buff Station Doesn't Show Up

### ISSUE THREAD

**Issue by badooga** [DarkflameUniverse/DarkflameServer#341]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

There is an achievement for building the Survival Buff Station 100 times in Avant Gardens Survival. However, I have never seen any quick builds throughout my entire time playing Survival.

![image](https://user-images.githubusercontent.com/33851191/147966320-cfbd7b00-6b26-47b6-931f-9d62bc5dab54.png)

### Reproduction steps

Play Avant Gardens Survival and try (and fail) to find any sort of Quick Build.

### Expected Behavior

I don't even remember this thing existing in the original game to be honest. So either the Quick Build should be implemented, or the achievement should be removed.

### Environment

Ubuntu Server

**Comment by Xiphoseer** [comment]
There's an object for it at least (https://explorer.lu/objects/6412), and there's a `Rewards_01` spawner path with 7 coordinates and a `number_to_maintain: 1` setting. It also has a script, which I assume would spawn the powerups.

**Comment by EmosewaMC** [comment]
> There's an object for it at least (https://explorer.lu/objects/6412), and there's a `Rewards_01` spawner path with 7 coordinates and a `number_to_maintain: 1` setting. It also has a script, which I assume would spawn the powerups.

Touching up on this - the buff station is supposed to restore 1 imagination armor and health to all nearby players.  Where do you see the Rewards_01 spawner path though on explorer.lu?  Im having trouble finding those values and might want to take a look into implementing this script should it be in my skill range

**Comment by EmosewaMC** [comment]
> On https://explorer.lu/zones/1101 in the "Paths" menu.

@Xiphoseer Awesome sauce.  Off the top of your head do you know of any scripts that utilize similar features so I have something to base the script off of or would this be a fully custom implementaion?

**Comment by Xiphoseer** [comment]
@EmosewaMC I think this is custom but very simple. Just drop powerup on a timer IIUC
