### ISSUE TITLE
BUG: Various enemies can float and attack through the floor?

### ISSUE THREAD

**Issue by godismyjudge95** [DarkflameUniverse/DarkflameServer#349]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

It seems most smaller enemies can float through terrain within their relative boundaries (I don't know if this was the original behavior or not).  Most obvious case of this is in Gnarled Forest where the pirates and the captains can rather quickly float up to the top of the platforms which makes quickbuilding rather difficult.  But this also happens in Advent Gardens and Forbidden Valley.

Regardless of whether or not enemies float, there might need to be some code so that once enemies are within attacking distance they clip fully out of the floor so characters can attack them.  Or maybe just don't let enemies attack if they are inside terrain.

### Reproduction steps

1.  Go to an area with enemies and floating platforms (ie. gnarled forest prison area)
2. Climb to a platform above enemies

Result:  Enemies agro, float up, and attack you through the floor

### Expected Behavior

Only certain enemies float and the enemies that should float shouldn't attack through the floor.

### Environment

Ubuntu

**Comment by averysumner** [comment]
This is a combination of poor navmeshes and the lack of dynamics simulation. In all honesty it’s as good as it’s going to get with our current physics engine. Feel free to PR with a physics engine overhaul, wontfix.

**Comment by EmosewaMC** [comment]
Im not experiencing this on live.  Enemies in Gnarled forest do not float and this is after hours of being there.  Can you verify your setup?  (server hash, source of files used to setup server, type of system used to run the server (WSL, windows, mac))
