### ISSUE TITLE
Survival Minigame is still broken

### ISSUE THREAD

**Issue by Drakonkinst** [DarkflameUniverse/DarkflameServer#35]
The instructions to fix the survival minigame say to modify a line in `res/scripts/ai/minigame/survival/l_zone_survival_client.lua`. However, this file does not exist in the game client folder unless you have unpacked the client, so making this change does not actually fix the issue. I assume the game is actually reading something else that still has this bug and ignoring the scripts folder entirely. Any idea what this file might be?

As for the actual breaking bug, I cannot move in the survival minigame. Choosing "Smash myself" in the help menu fixes this, but there is still nothing spawning and no timer visible. For now, if you re-log after being smashed, you will be kicked back to Avant Gardens, so it is not complete hardstuck bug (though it prevents further progression).

**Comment by AnLUFan** [comment]
If you don't mind skipping the survival mission, the command "/skip-ags" might allow you to skip the mission (if I am reading correctly, the command can be used with any gm level). Although, I have not tested this myself. (Another mission skipping command from SlashCommandHandler.cpp is "/skip-sg," but I have no idea which mission it allows you to skip)

**Comment by Drakonkinst** [comment]
I'll give it a try, thank you! I assume players with permission level 0 can't do this, but I can modify the database to give them temporary perms.
