### ISSUE TITLE
BUG: gmlevel 9 Does Not Spawn Cars Properly

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#351]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When a player drags a built race car from their backpack to the game, the server will spawn the player in the car and lock them in place.  This would require intervention to free the player as they are now stuck in a car that cant do anything.  A server restart would fix the player being stuck.

A larger issue caused by this is there is no limit to the number of cars a player can spawn with this method and this will lead to degraded server performance until the server is restarted which would clear all of the cars.

![image](https://user-images.githubusercontent.com/39972741/148173003-4c749094-6976-499b-acc5-edb560dda20b.png)

### Reproduction steps

1) Build a car using modular building
2) Drag the car onto the screen repeatedly

### Expected Behavior

A pop saying you must be near a modular car build site should pop up

### Environment

Server: Ubuntu
Client: Windows 10

**Comment by EmosewaMC** [comment]
https://youtu.be/HIgGDJg6BwE
Here is a video of what happens if 3 players were to do this bug

**Comment by EmosewaMC** [comment]
This is very similar to #260 but since it wasn't the exact same issue I made its own issue.  If this should be merged with that one I'll do that.

**Comment by averysumner** [comment]
Is your player gmlevel 9?

**Comment by averysumner** [comment]
This should only be occurring if the player is gmlevel 9, if not let me know. This is a “feature”. It should place you in the car and let you drive around, but it doesn’t because there’s an issue somewhere with gms.

**Comment by EmosewaMC** [comment]
> This should only be occurring if the player is gmlevel 9, if not let me know. This is a “feature” for admins. It should place you in the car and let you drive around, but it doesn’t because there’s an issue somewhere with the game messages.

This is correct.  Closing the issue.

**Comment by averysumner** [comment]
Marking wontfix, would be cool if someone fixed this in a PR though.
