### ISSUE TITLE
Server shut down needs a response to master to speed up closing the server during development

### ISSUE THREAD

**Issue by Jettford** [DarkflameUniverse/DarkflameServer#361]
Forcibly closing the server starts a shutdown sequence on every instance, instead of the world servers telling the master server when it is done it just waits and this is just annoying and time consuming

**Comment by DarwinAnim8or** [comment]
For development purposes, you can just kill the instances as you don't really need it to save your progress per se. 
However I agree that it'd be better to make it listen for disconnection messages, when no connections remain before the time is up, you can safely exit
