### ISSUE TITLE
BUG: Meeting the faction leaders missions are bugged when accepted a second time

### ISSUE THREAD

**Issue by simondumalski** [DarkflameUniverse/DarkflameServer#363]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The Nexus Naomi at the entrance of Nexus Tower gives 4 missions, each leading you to a faction leader. After successfully completing it, you can go back to her and it will show up immediately as a “daily mission” and you can accept it again.

When you try to talk to the faction leaders after accepting the mission the second time, it will show the beam of light and prompt you to press shift to talk to the leader, but will simply do nothing when it is pressed.

### Reproduction steps

Goto nexus tower
Accept the “meet the faction leaders” missions from Nexus Naomi
Complete them
Go accept them again
You cannot hand them in

### Expected Behavior

I’m not sure if there are actually daily missions (I don’t see why they would be) but ideally after finishing them once, you would not even be prompted to do them again. I don’t remember having to “meet the faction leaders” more than once on live.

If these are daily missions, then having them completable after doing them once is what should happen.

### Environment

Ubuntu on a VPS

**Comment by TheMatt2** [comment]
Video from live seems to indicate those are in fact repeatable missions.

https://youtu.be/eJe2T-aad3k?t=70

**Comment by simondumalski** [comment]
If that is the case, then the repeatability of them does not work.
They can be completed once, and then will forever hang out in your active missions if accepted again.

**Comment by EmosewaMC** [comment]
Fix is implementing `scripts\02_server\Map\NT\L_NT_NAOMI_BREADCRUMB_SERVER.lua`

**Comment by EmosewaMC** [comment]
This is fixed
