### ISSUE TITLE
BUG: Typo in dialogue from Zane when learning ice spinjitzu

### ISSUE THREAD

**Issue by Saymoan** [DarkflameUniverse/DarkflameServer#364]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When learning ice spinjitzu, there is a typo in the dialogue from Zane.
https://media.discordapp.net/attachments/920435160279834674/926245586183802900/unknown.png
“Spinjitzu” is spelled “Spinjiztu” which is incorrect

### Reproduction steps

Go to the monastery and begin the missions to learn ice spinjitzu from Zane
Look at the dialogue on the “Student of Ice” mission

### Expected Behavior

Spinjitzu isn’t misspelled

### Environment

Ubuntu on a VPS

**Comment by Wincent01** [comment]
This is a client issue, nothing the server can fix. If you want to fix it in your client, edit the phrase in `locale/locale.xml`. Closing.
