### ISSUE TITLE
BUG: Headbash helmet ability being tied to Paradox Valiant Weapons

### ISSUE THREAD

**Issue by dinomking33** [DarkflameUniverse/DarkflameServer#369]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When using the Headbash Helmet (a reward from the passport) as well as skeleton skull helmet abilities, the cooldown is linked to paradox valiant weapon abilities. 

They occupy two different ability slots, and neither the headbash or skull helmet has any relation to the Paradox kits. 

Additionally, the headbash ability is to charge forward, deal 10 damage and knock an enemy down. Paradox valiant weapons summon a friendly unit to help fight for a limited time. Neither of these abilities share any relation with one another. 

Video depicting issue:
https://youtu.be/ny-_fzFLql4 

### Reproduction steps

In order to reproduce, equip either the Paradox Valiant Wormholer or DoomSlicer weapon, as well as either the skull helmet or headbash helmet. 

It is possible there are additional helmets in the game that may cause the issue, however I only have access to these two.

Use either the charge ability or valiant ability. You will be unable to perform the other ability for the duration of the cooldown. 

This is very problematic when using the summoning abilities, as you will be unable to use a charge ability for over thirty seconds.

### Expected Behavior

The cooldown should not be linked between the headbash helmets and the paradox valiant abilities. 

It should be possible to use the paradox valiant abilities and within that time period, use your headbash charge ability. 

### Environment

I am currently running Darkflame on Windows 10.

Additionally, i am currently running on the LUPLO server.

**Comment by NealSpellman** [comment]
Just because two items are seemingly not related does not mean they can't share the same cooldown group. Both items (13285, proxy Valiant and 12530, Headbash Helmet) use `cooldowngroup` 24 (skills 1028 and 987), which means they both go on cooldown when one is used.

This is live accurate behavior. Closing this; any changes to this behavior requires a client mod and will be up to server hosts.
