### ISSUE TITLE
Cmake could not find Zlib

### ISSUE THREAD

**Issue by Sloofy** [DarkflameUniverse/DarkflameServer#37]
**Expected Behaviour**
While in the build folder, typing cmake would start generating make files successfully.

**Current Behaviour**
Cmake encounters an error where it cannot find Zlib (It is installed on the system).

**Steps to Reproduce**
1. Run the build script (or follow the same commands in the script / README -- they're both the same).

**Your Environnment**
Fedora KDE Spin. Zlib and all other required packages are installed from the official repos.

**Terminal Output**
> ❯ cmake ..
> -- Variable: PROJECT_VERSION_MAJOR = 1
-- Variable: PROJECT_VERSION_MINOR = 0
-- Variable: PROJECT_VERSION_PATCH = 0
-- Variable: LICENSE = AGPL-3.0
-- Variable: NET_VERSION = 171023
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindZLIB.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:40 (find_package)
>
>
> -- Configuring incomplete, errors occurred!
See also "/home/sloofy/Documents/DarkflameServer/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/DarkflameUniverse/DarkflameServer/files/7658332/CMakeOutput.log)

**Comment by dddddddd207** [comment]
You need `zlib-devel` for the development headers etc. On other distros it might be called something like `zlib-dev`

**Comment by averysumner** [comment]
As stated above you are likely missing the development version of this package. As it stands we auto acquire zlib and build from source on Windows. We could change this auto acquire and build to just be on ZLIB_FOUND being false, preventing situations like this. Thoughts?

**Comment by Sloofy** [comment]
> You need `zlib-devel` for the development headers etc. On other distros it might be called something like `zlib-dev`

Installed zlib-devel and ran cmake again. This is the output:

> ❯ cmake ..
> -- Variable: PROJECT_VERSION_MAJOR = 1
> -- Variable: PROJECT_VERSION_MINOR = 0
> -- Variable: PROJECT_VERSION_PATCH = 0
> -- Variable: LICENSE = AGPL-3.0
> -- Variable: NET_VERSION = 171023
> -- Found ZLIB: /usr/lib/libz.so.1 (found version "1.2.11") 
> CMake Warning (dev) in CMakeLists.txt:
>   A logical block opening on the line
> 
>     /home/sloofy/Documents/DarkflameServer/CMakeLists.txt:80 (if)
> 
>   closes on the line
> 
>     /home/sloofy/Documents/DarkflameServer/CMakeLists.txt:98 (endif)
> 
>   with mis-matching arguments.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Version: 1.0.0
> -- Configuring done
> CMake Error at CMakeLists.txt:373 (add_library):
>   No SOURCES given to target: tinyxml2
> 
> 
> CMake Error at CMakeLists.txt:374 (add_library):
>   No SOURCES given to target: detour
> 
> 
> CMake Error at CMakeLists.txt:375 (add_library):
>   No SOURCES given to target: recast
> 
> 
> CMake Error at CMakeLists.txt:376 (add_library):
>   No SOURCES given to target: libbcrypt
> 
> 
> CMake Generate step failed.  Build files cannot be regenerated correctly.
>

**Comment by averysumner** [comment]
FindZLIB.cmake is not guaranteed to work on all platforms. I’ll look into building from scratch if it’s not found on platforms besides Windows.

**Comment by Sloofy** [comment]
> FindZLIB.cmake is not guaranteed to work on all platforms. I’ll look into building from scratch if it’s not found on platforms besides Windows.

Cheers! I'll keep an eye out for that, then

**Comment by luxaritas** [comment]
@Sloofy The later errors look like you haven't properly cloned the repo with submodules (ie, with the --recursive flag)

**Comment by Sloofy** [comment]
> @Sloofy The later errors look like you haven't properly cloned the repo with submodules (ie, with the --recursive flag)

Ah, yes, that'd be it. I was pretty quick in cloning the repo that I missed the recursive flag. As far as I know, having the zlib-devel package installed did solve the first issue I was encountering, so I'll close the issue here. Thank you so much!
