### ISSUE TITLE
BUILD: Windows Only Build Fails in Visual Studio 2022

### ISSUE THREAD

**Issue by TheMatt2** [DarkflameUniverse/DarkflameServer#371]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### Platform

Windows

### Architecture

x86

### Error Logs

Apologize if this is a simple issue, but under Visual Studio 2022 the server build always fails with an error message saying `mysqlcppconn-9-vs14.dll` cannot be found.

In visual studio, the project is configured as a CMake project, and does build successfully. But all attempts to run the code will fail.

Apologize if this is a simple issue, I am not used to the build process in Visual Studio.

I see the comment in the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md) that "Currently on native Windows the server will only work in Release mode." However, I am not sure if this is related.
CMake is set to build in "RelWithDebInfo", which I suppose is release mode.

![image](https://user-images.githubusercontent.com/22862051/149172985-bb3cdc8f-4285-4ada-a42d-2e3ba6602a9e.png)

    The code execution cannot proceed because mysqlcppconn-9-vs14.dll was not found. Reinstalling the program may fix this problem.

Environment

Windows 11, 21H2
Visual Studio 2022, Version 17.0.4

Traceback
<details>
    'MasterServer.exe' (Win32): Loaded 
    'C:\Users\User\source\repos\DarkflameServer\build\MasterServer.exe'. Symbols loaded.
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'.
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
    'MasterServer.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
    The thread 0x2eb0 has exited with code 3221225781 (0xc0000135).
    The thread 0x2f0c has exited with code 3221225781 (0xc0000135).
    The program '[2592] MasterServer.exe' has exited with code 3221225781 (0xc0000135) 'A 
    dependent dll was not found'.
</details>

**Comment by Jettford** [comment]
This is a configuration issue although one that wasn't documented for some reason.

Please take a look at this commit:
https://github.com/DarkflameUniverse/DarkflameServer/commit/9da6c81e900b040f9ab54403585a58bc6e6680c1

**Comment by Jettford** [comment]
Oops, didn't mean to close

**Comment by averysumner** [comment]
Not a build issue, configuration issue that presents itself on runtime. Some conversation about automating dll/so placement in PR #379. Closing.

**Comment by Jettford** [comment]
This is still an undocumented issue?
