### ISSUE TITLE
BUG: Faction token bags do not check if you are in a faction

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#374]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Faction token bags do not check whether you are in a faction and if are used when not in one will just disappear.

### Reproduction steps

1) obtain a faction token bag
2) use it and get no tokens

### Expected Behavior

bag is not consumed

### Environment

ubuntu server
windows client

**Comment by TheMatt2** [comment]
How do you obtain a faction bag without being in a faction?

**Comment by EmosewaMC** [comment]
Various achievements reward faction bags before you can be in a faction

**Comment by averysumner** [comment]
Anyone know what happened to these in the live game when you opened them? Presumably there would've been a precondition preventing you from opening it, which if it was in cdclient would already work. Maybe we add a manual check for these items?

**Comment by EmosewaMC** [comment]
@averysumner a pop up on the client side says you need to join a faction first to use this item

**Comment by averysumner** [comment]
Seems like some sort of missing precondition. Odd it’s not there…

**Comment by Xiphoseer** [comment]
At least the medium bag has a preconception (47):

> Faction members only. Find the Recruiter in Nimbus Station and join a Faction!

**Comment by EmosewaMC** [comment]
This is bugged again as precondition checks were removed on accident in #726
