### ISSUE TITLE
BUG: Shard armor and Imaginite Pack do not grant the respective bonuses

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#376]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

These items are supposed to restore armor/imagination after 5 hits but currently do not do so.

### Reproduction steps

1) equip one of the two items.
2) take 5 hits

### Expected Behavior

Gain armor or imagination after the hits

### Environment

server ubuntu
client windows 10

**Comment by aronwk-aaron** [comment]
Relates to #746
