### ISSUE TITLE
ENH: Implement Nexus Jawbox

### ISSUE THREAD

**Issue by simondumalski** [DarkflameUniverse/DarkflameServer#382]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When you spawn a Nexus Jawbox in either Nexus Tower or Nimbus Station (the two worlds known to have had a working jawbox in them at some point in time), the GUI opened when pressing shift does not allow players to put bricks inside of it, thus, making donating bricks impossible and the achievements incompletable.

### Reproduction steps

Spawn a Nexus Jawbox in
Open the GUI with shift
Attempt to put bricks into the GUI

### Expected Behavior

The GUI always you to put bricks inside of it to donate to complete the Nexus Tower Builder achievements.

### Environment

Ubuntu server on a VPS
Windows client using lcdr/humanoids 1.10.64 unpacked client

**Comment by NealSpellman** [comment]
I'm hesitant to even call this a bug at this point; Jawbox was removed and was inaccessible after the event, so this really would be an enhancement to get working as it will only appear if a GM spawns it. Technically yeah, doesn't work right now but it's not a part of the last Live patch's accessible content.

**Comment by aronwk-aaron** [comment]
Fixed bt #1168
