### ISSUE TITLE
BUG: Opening Mailbox Crashes Client

### ISSUE THREAD

**Issue by GreatPhoenix** [DarkflameUniverse/DarkflameServer#384]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Hi all,
I have this issue with my server when a client tries to open their mail at a mailbox it crashes there client to desktop. 
Is this a known issue or is there a broken script somewhere that did not install properly.
Thanks

### Reproduction steps

Go to the Gardens mailbox. 
Click shift to open the mailbox
My client hard crashes at that point

### Expected Behavior

Opening of the mail box UI to send and receive mail.

### Environment

Ubuntu Server 20.04.3 LTS

**Comment by averysumner** [comment]
What client are you using?

**Comment by GreatPhoenix** [comment]
I am using the Darkflame Client

**Comment by averysumner** [comment]
> I am using the Darkflame Client

This may be your issue. We used to have a client side workaround for mail that was recently removed.

**Comment by GreatPhoenix** [comment]
Though I am now familiar with rebuilding the server files at this point but it is not fun to do.
Is there anyway to reenable this workaround in the client? Also is this feature fixed in the standard client?

**Comment by zrev2220** [comment]
I have a similar issue where opening mail does not work. It doesn't crash my client, but the minimap disappears, as if the mail UI is supposed to have appeared. As a result, I can't check my mail at all. Talking/interacting with something/someone else makes the map reappear and things go back to normal.

I'm also using the Darkflame client.

**Comment by NealSpellman** [comment]
Use a standard client, not the Darkflame client. That Darkflame client that someone uploaded doesn't have our reverted fix for mail, whereas a regular live client will work fine.

If it doesn't crash anymore after swapping to that, let us know and we can close this issue.

**Comment by GreatPhoenix** [comment]
Awesome that is interesting that it is client side. This might be a noob question but can I change the server net version from 171023 to 171022 without a recompile or am I forced to recompile and rebuild the server?

**Comment by Jettford** [comment]
> Awesome that is interesting that it is client side. This might be a noob question but can I change the server net version from 171023 to 171022 without a recompile or am I forced to recompile and rebuild the server?

You are forced to regenerate the CMake file and rebuild due to how the NET_VERSION define works.
