### ISSUE TITLE
Ubuntu can't find Cmake.

### ISSUE THREAD

**Issue by Harb1ngerBD** [DarkflameUniverse/DarkflameServer#39]
I'm doing the Linux adapter on my Windows device. However, when I get to the step where I'm supposed to type <cmake ..>, it gives me an error message
<CMake Error: The source directory "/home/jack" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.>

**Comment by averysumner** [comment]
You must install CMake using the package manager apt on Ubuntu. Closing this issue as it’s unrelated to our codebase.
