### ISSUE TITLE
BUILD: Make fails while building MasterServer

### ISSUE THREAD

**Issue by Mar0xy** [DarkflameUniverse/DarkflameServer#398]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### Platform

Other

### Architecture

x86

### Extra Info
While compiling the MasterServer make always errors on the same line I don't know with which commit this started but on an older commit (0afba0d) It worked fine and according to the log it is due to undefined references I assume (as I don't know much about make and c++)
CMake version: 3.20.2
Make version: 4.2.1
GCC Version: 8.5.0
System: Oracle Linux/RHEL 8

### Error Logs

<details>

```make
[ 27%] Building CXX object CMakeFiles/MasterServer.dir/dMasterServer/InstanceManager.cpp.o
[ 28%] Building CXX object CMakeFiles/MasterServer.dir/dMasterServer/MasterServer.cpp.o
[ 28%] Building CXX object CMakeFiles/MasterServer.dir/dMasterServer/ObjectIDManager.cpp.o
[ 28%] Linking CXX executable MasterServer
CMakeFiles/MasterServer.dir/dMasterServer/MasterServer.cpp.o: In function `main':
MasterServer.cpp:(.text.startup+0x292): undefined reference to `std::filesystem::path::_M_split_cmpts()'
MasterServer.cpp:(.text.startup+0x29a): undefined reference to `std::filesystem::status(std::filesystem::path const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/MasterServer.dir/build.make:136: MasterServer] Error 1
make[1]: *** [CMakeFiles/Makefile2:193: CMakeFiles/MasterServer.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```

</details>

**Comment by EmosewaMC** [comment]
This is an issue with GCC not supporting the filesystem include.  @TheMatt2 i believe is working on a PR to fix this issue.

**Comment by Mar0xy** [comment]
> This is an issue with GCC not supporting the filesystem include. @TheMatt2 i believe is working on a PR to fix this issue.

Yea, just found the PR(#400) it was closed though even though I don't understand the reason why to drop the support for earlier versions as it worked just fine and also since some distros still default to GCC 8 and not GCC 10+ which doesn't support C++17 so after reading it I had to go and install
```
gcc-toolset-10-c++ gcc-toolset-10-make gcc-toolset-10-gcc
```
and then run
```
scl enable gcc-toolset-10 bash
```
to get an working bash with GCC 10
