### ISSUE TITLE
BUG: ChatServer doesnt work in Docker | Teams / adding Friends not working(No Notification/Way to accept)

### ISSUE THREAD

**Issue by DasRaschloch** [DarkflameUniverse/DarkflameServer#399]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [x] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Trying to invite someone to a party or sending a friend request doesn't work at all. There is no Popup or any other way to accept any invitation as there is no notification. As far as this got mentioned before in other Threads this has something to do with the ChatServer not running/crashing. But when i access the Logs of the DarkflameDocker or with docker-compose logs -f --tail 100
there isn't even an entry about the ChatServer getting initialized in the first place, or an entry of a Crash/restart.

### Reproduction steps

Installing Darkflame with Docker as described in Docker.md and Docker_Windows.md

### Expected Behavior

Being able to join Groups/add Friends

### Environment

Linux based System. Darkflame is installed with Docker.

**Comment by Jettford** [comment]
@TheNoim Was this something that you encountered?

**Comment by TheNoim** [comment]
Hm, interesting

**Comment by TheNoim** [comment]
Hey, can you try running `docker compose exec darkflame ps -ax` and send me the output? Want to know whether the ChatServer really crashed or if this is some kind of connection issue.

**Comment by DasRaschloch** [comment]
docker-compose exec darkflame ps -ax:
 ```
 PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/bash /start_server.sh
   33 ?        Sl    30:23 ./MasterServer
   36 ?        Sl    29:00 ./ChatServer
   38 ?        Sl    32:30 ./WorldServer -zone 0 -port 3000 -instance 0 -maxclients 999 -clone 0
   42 ?        S      0:00 sudo ./AuthServer
   45 ?        Sl    28:51 ./AuthServer
  106 pts/0    Ss+    0:00 sh
 1194 pts/1    Rs+    0:00 ps -ax
```

**Comment by TheNoim** [comment]
> There you go @TheNoim
> 
> docker-compose exec darkflame ps -ax:
> 
>  ```
> 
>  PID TTY      STAT   TIME COMMAND
> 
>     1 ?        Ss     0:00 /bin/bash /start_server.sh
> 
>    33 ?        Sl    30:23 ./MasterServer
> 
>    36 ?        Sl    29:00 ./ChatServer
> 
>    38 ?        Sl    32:30 ./WorldServer -zone 0 -port 3000 -instance 0 -maxclients 999 -clone 0
> 
>    42 ?        S      0:00 sudo ./AuthServer
> 
>    45 ?        Sl    28:51 ./AuthServer
> 
>   106 pts/0    Ss+    0:00 sh
> 
>  1194 pts/1    Rs+    0:00 ps -ax
> 
> ```

Ok, this means the ChatServer is still alive. What is the output of the other command?

**Comment by DasRaschloch** [comment]
> > There you go @TheNoim
> > docker-compose exec darkflame ps -ax:
> > ```
> > 
> > PID TTY      STAT   TIME COMMAND
> > 
> >    1 ?        Ss     0:00 /bin/bash /start_server.sh
> > 
> >   33 ?        Sl    30:23 ./MasterServer
> > 
> >   36 ?        Sl    29:00 ./ChatServer
> > 
> >   38 ?        Sl    32:30 ./WorldServer -zone 0 -port 3000 -instance 0 -maxclients 999 -clone 0
> > 
> >   42 ?        S      0:00 sudo ./AuthServer
> > 
> >   45 ?        Sl    28:51 ./AuthServer
> > 
> >  106 pts/0    Ss+    0:00 sh
> > 
> > 1194 pts/1    Rs+    0:00 ps -ax
> > ```
> 
> Ok, this means the ChatServer is still alive. What is the output of the other command?

```
root@VaultAlexandria:/mnt/user/appdata/DarkflameUniverse/DarkflameServer# docker-compose exec darkflame tail -f /app/logs/*.log
tail: cannot open '/app/logs/*.log' for reading: No such file or directory
tail: no files remaining
```

**Comment by Iterator256** [comment]
Is #249 related to this at all. I assumed that the friend and team systems were broken in generall right now, but it seams that it's only broken in Docker?

**Comment by Marcono1234** [comment]
The underlying issue might be that here the variable `$CHAT_SERVER_PORT` is used, but no value for it is set:
https://github.com/DarkflameUniverse/DarkflameServer/blob/b7d7146821d8e3f0dd711b7e7f91e39745993a9f/docker/setup.sh#L34

Additionally the default ports in the `.ini` files do not match the default ports in code, e.g. the port here in the [`WorldServer` code](https://github.com/DarkflameUniverse/DarkflameServer/blob/b8c1f7629e4dc351ed24a2a8618a9c398a22d475/dWorldServer/WorldServer.cpp#L195) is different than the default one in the [`worldconfig.ini`](https://github.com/DarkflameUniverse/DarkflameServer/blob/b7d7146821d8e3f0dd711b7e7f91e39745993a9f/resources/worldconfig.ini#L12). So when in one case you provide a port through the `.ini` file, and in the other case (as seen here with chat server) leave it blank, then the servers cannot connect. I assume that might be the intended behavior by the maintainers though.

(Also unless I am overlooking something in the log files, `WorldServer` does not seem to notice the connection failure to the chat server; but that is probably unrelated to the Docker setup.)

After manually editing `worldconfig.ini` in the Docker container to specify `chat_server_port=2005`, at least friend requests seem to work. Private chat does not work for me, one of the `ChatServer` log files contained: "[ChatServer] Unknown CHAT id: 50" and "[ChatServer] Unknown CHAT id: 51" (not sure if that is related to it)
