### ISSUE TITLE
Syntax errors in 0_initial.sql

### ISSUE THREAD

**Issue by QuirkyTurtle101** [DarkflameUniverse/DarkflameServer#4]
(On windows) Attempting to run 0_initial.sql through the MySQL command line throws the following error:

`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TABLE accounts (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHA' at line 1`

Putting the contents of the file through an online MySQL syntax checker throws the same error. I have no experience with MySQL to properly troubleshoot this, but I can only assume it's an issue with the file, rather than on my end, so I'm putting it here.

**Comment by JoachimFlottorp** [comment]
Would also like to note out that MYSQL 8.0.27-0ubuntu0 does not support having a default value set to TEXT
 https://github.com/DarkflameUniverse/DarkflameServer/blob/27dace206b20006a6bfb20624374ed5731179690/migrations/dlu/0_initial.sql#L111

**Comment by cristobers** [comment]
> (On windows) Attempting to run 0_initial.sql through the MySQL command line throws the following error:
> 
> `ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TABLE accounts ( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHA' at line 1`
> 
> Putting the contents of the file through an online MySQL syntax checker throws the same error. I have no experience with MySQL to properly troubleshoot this, but I can only assume it's an issue with the file, rather than on my end, so I'm putting it here.

Try using MariaDB https://mariadb.org/ instead of MySQL. I also had this issue and switching to MariaDB worked for me.

**Comment by maxdelayer** [comment]
I had the same error, and then I removed the `OR REPLACE` from the first two tables and MySQL stopped complaining.

**Comment by diminikov** [comment]
You can also add IF NOT EXISTS in front of CREATE TABLE to replace the effect of OR REPLACE

**Comment by averysumner** [comment]
As stated above, these SQL files are only fully compatible with MariaDB. For now, opt to use MariaDB rather than MySQL.

**Comment by Pr3roxDLC** [comment]
Maybe it should be changed in the ReadMe to say MariaDB instead of MariaDB or MySQL
