### ISSUE TITLE
MySQL connection destroyed

### ISSUE THREAD

**Issue by CitrusHappy** [DarkflameUniverse/DarkflameServer#40]
Running off WSL Ubuntu. Locally hosted.

It appears something is wrong with my configs for the database. This is odd because the account manager is able to read/write to the database using the database URL. When running the server, spits out the following;
`[05-12-21 23:23:08] [Test]: Quitting
Destroying MySQL connection!`

mysql_host=localhost
mysql_database=luserver
mysql_username=root
mysql_password= some password

above is used in all the config.ini files. it this correct syntax?

**Comment by averysumner** [comment]
Are you running WorldServer individually rather than running MasterServer and allowing it to allocate instances? This means there either isn’t a MasterServer running or the MasterServer has decided that the instance isn’t needed.

**Comment by CitrusHappy** [comment]
I am running MasterServer with sudo

**Comment by Jodobofire** [comment]
Had the same problem!
Check your external IP in the ini files, mine changed and caused this problem!

**Comment by JadeShrineMaiden** [comment]
Facing the same problem, only with an Ubuntu VPS instead of WSL.

**Comment by CitrusHappy** [comment]
> Had the same problem! Check your external IP in the ini files, mine changed and caused this problem!

External IP is localhost for all three .ini files that have that field.

**Comment by CitrusHappy** [comment]
resolved with latest build

**Comment by CitrusHappy** [comment]
Above solution seemingly does not work anymore.
I've tried remaking, rebuilding, and restarting WSL and the database. Still receiving connection destroyed.

**Comment by Br3akout** [comment]
Got the same Problem, every Server I try to start gets  [Test]: Quitting
Destroying MySQL connection!

**Comment by CitrusHappy** [comment]
> Got the same Problem, every Server I try to start gets [Test]: Quitting Destroying MySQL connection!

are you also using MariaDB and WSL?

**Comment by mporto789** [comment]
I'm having the same issue, did you found a solution for it?

**Comment by Br3akout** [comment]
> > Got the same Problem, every Server I try to start gets [Test]: Quitting Destroying MySQL connection!
> 
> are you also using MariaDB and WSL?

Yes I do. But the IP address I used for the configs (and which I got from hostname -i) was 127.0.1.1 which ich a bit weird for a public address.. I think its maybe the wrong address to put there?

**Comment by QuirkyTurtle101** [comment]
I'm having this same problem, as I've stated in another issue - using WSL Ubuntu, and MariaDB. I've tried rebuilding the entire server, providing a new res folder, recreating my database, and reinstalling my Ubuntu distro as well as MariaDB. None of it seems to have helped at all, and the server throws the same exact error when starting it.

**Comment by Br3akout** [comment]
> > > Got the same Problem, every Server I try to start gets [Test]: Quitting Destroying MySQL connection!
> > 
> > 
> > are you also using MariaDB and WSL?
> 
> Yes I do. But the IP address I used for the configs (and which I got from hostname -i) was 127.0.1.1 which ich a bit weird for a public address.. I think its maybe the wrong address to put there?

My Issue is now fixed.. turned out I needed to use the inet IP from "ip addr" rather than the one form "hostname -i"
