### ISSUE TITLE
ENH: Add a command to see online players in every instance

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#403]
### Is your feature request related to a problem?

/who currently shows the online players in your instance, but there's currently no way to tell who is in every instance.

### Describe the solution you'd like

maybe a command like /who all or /everyone that shows every online player and what instance they are in.

**Comment by averysumner** [comment]
I’m not sure if this should be something available to normal gmlevel 0 players.

**Comment by NealSpellman** [comment]
Closing this since #450 goes into more detail and has been used for discussions around player count tracking.
