### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by johntor** [DarkflameUniverse/DarkflameServer#404]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that the documentation is wrong or missing on the latest version of the main branch of DarkflameServer

### Location of the documentation

https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md

### Documentation problem

After all these fixes/updates that all of you create (Thank you very much for that!), I think someone should include an update procedure for a currently working server...

Also because there are a few clients out there, I think there should be a list of all approved client files with every file's MD5/SHA256  hash. The Known good clients list that is given is very broad and the provided SHA256s are coming out of compressing with tools with many parameters and versions. ex. rar changed compression methods from v4 to v6.

THANK YOU ALL for bringing back all these happy memories!

### Suggested fix for documentation

I don't have the knowledge to make a suggestion because I haven't use project's build system before.
I can understand though that the create administrator step should be omitted and also some database steps.

**Comment by averysumner** [comment]
Please give this a clear name. We could look into packaging a manifest for valid clients in the future.

**Comment by Xiphoseer** [comment]
> I think there should be a list of all approved client files with every file's MD5/SHA256 hash

There is actually one of those in the `versions` folder of the original client. It's called trunk.txt and is simlar to a CSV file with the third column being the md5 hash of the file and the second its size. Trunk should be identical for all 1.10.64 clients, no matter how (in)complete they are. The SHA256 hash of that file is, afaik:

40787fa5aa7b3fdf61589eb9dd03f411ea4eec6f9bda033cb96b155f13df4e3c  trunk.txt

**Comment by johntor** [comment]
After Xiphoseer's info I think we can close this issue...
