### ISSUE TITLE
Issues with SQLite database

### ISSUE THREAD

**Issue by Mason-Witt** [DarkflameUniverse/DarkflameServer#41]
This is probably me because I have not worked with SQLite in the past but I am stuck on  configuring the client database.

 I turned the .fdb into a sqlite and placed it in the right folder, but when I try to open the database to read the .sql files into I get a cannot open error.

 I am trying  .open /home/User/DarkflameServer/build/res/CDServer.sqlite
and receiving Error: cannot open "/home/User/DarkflameServer/build/res/CDServer.sqlite"

**Comment by averysumner** [comment]
What are you attempting to open it with?

**Comment by Mason-Witt** [comment]
> s

I am using sqlite3

**Comment by Mason-Witt** [comment]
> What are you attempting to open it with, you’ll need some sort of editor to apply the patches.

I am using SQLite3

**Comment by averysumner** [comment]
You’re using sqlite3 incorrectly then. Closing issue as it does not relate to our codebase.
