### ISSUE TITLE
BUG: Mission #756 "It's Truly Random!" dose not gain progress from using the LEGO dice item

### ISSUE THREAD

**Issue by Sirch0** [DarkflameUniverse/DarkflameServer#412]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Mission #756 "It's Truly Random!" dose not gain progress when using the LEGO dice item, regardless of its from the inventory or from the hot bar. This makes it impossible to complete this mission.

### Reproduction steps

Collect a LEGO dice item (id 7989) and use it, then check the passport under the play tab at the bottom for the mission "It's Truly Random!", you will notice that no progress has been made towards this mission despite the die being used.

### Expected Behavior

When the LEGO dice item is used progress towards mission #756 "It's Truly Random!" should be made.

### Environment

Windows Ubuntu server.

**Comment by EmosewaMC** [comment]
Are you sure you are rolling a 6?  you need to roll a 6 to progress the mission

**Comment by Sirch0** [comment]
Yeah that's my bad, I misread the mission, after testing it works properly, although it funny because I tested rolling about 20 times to make sure it wasn't just inconsistent and apparently didn't role a 6 the whole time. I'll read more carefully next time.
