### ISSUE TITLE
BUG: "Money Magnet" item does not collect coins

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/DarkflameServer#423]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Version: 344af924feb643801d70c8c2f9bac765127bb62a

The "Money Magnet" item given as reward by Wisp Lee for the "Know Thy Enemy" mission does not seem to work. When active, it neither collects coins nor anything else.

### Reproduction steps

1. Obtain the "Money Magnet" item
2. Equip it and activate it

### Expected Behavior

It should collect coins (and powerups and items?)

### Environment

WSL 2, Docker Compose setup

**Comment by EmosewaMC** [comment]
Known bug due to missing behavior for Loot Buff and currently no known way to communicate this behavior to the client

**Comment by averysumner** [comment]
> Known bug due to missing behavior for Loot Buff and currently no known way to communicate this behavior to the client

This. It’s unknown where this buff is supposed to be serialized.

**Comment by EmosewaMC** [comment]
I have found the missing serialization to make this work.  Will be fixing later today.
