### ISSUE TITLE
BUG: Some repeatable missions are directly available again

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/DarkflameServer#424]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Version: 344af924feb643801d70c8c2f9bac765127bb62a

It appears some (or all?) repeatable missions are directly available again after completing them in some cases.
For me, after completing the missions "Brick Collection" + "A Real Hole in the Wall", "Smash and Awe" and "Creepy Crawlies" in Avant Gardens for the first time, they were immediately available afterwards again. However, after completing them a second time, they were not available. It also looks like the reward was different the second time.

### Reproduction steps

1. In Avant Gardens, complete the mission "Smash and Awe" (build 4 Satellite Beacons) for the first time
2. Get the reward for the completed mission
:x: You are offered the mission again

### Expected Behavior

There should be a delay between being offered a mission again

### Environment

WSL 2, Docker Compose setup

**Comment by EmosewaMC** [comment]
First one is a non repeatable mission, second one is the repeatable mission

**Comment by Marcono1234** [comment]
That would explain the different rewards, thanks. It feels a bit weird that you are offered the same exact mission, except with different reward; I would expect there to be some delay as well. But apparently that is [accurate to live](https://youtu.be/Amu0bL16NRI?t=57).
