### ISSUE TITLE
ENH: Clean up CMake configuration

### ISSUE THREAD

**Issue by codeshaunted** [DarkflameUniverse/DarkflameServer#427]
### Is your feature request related to a problem?

CMake configuration of this project is an abomination.

### Describe the solution you'd like

Rewrite the entire thing and make it more modular.

### Repository breaking implications

Could break CI.

**Comment by Xiphoseer** [comment]
cc #345

**Comment by Jettford** [comment]
> [](https://github.com/DarkflameUniverse/DarkflameServer/pull/345)

Should we just merge that at this point?

**Comment by Xiphoseer** [comment]
> Should we just merge that at this point?

Fine by me, as long as it still works

**Comment by Jettford** [comment]
I reverted the start of my changes because I realistically didn't have the time to actually do it

**Comment by Xiphoseer** [comment]
> I reverted the start of my changes because I realistically didn't have the time to actually do it

But it  seems like that still solved the merge conflict

**Comment by EmosewaMC** [comment]
This is finished and the CMake is more modular than before.  Closing.
