### ISSUE TITLE
BUG: "Pet Excavator" (MissionID: 505) is not tracked.

### ISSUE THREAD

**Issue by wertercatt** [DarkflameUniverse/DarkflameServer#429]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

"Pet Digs" don't progress this achievement.

### Reproduction steps

1. Go to Pet Cove (ZoneID: 1201)
2. Tame any pet
3. Walk up to a buried chest in the ground
4. Let your pet dig it up
5. Check your passport and see that no progress has been made on "Pet Excavator"

### Expected Behavior

Pet Digs are counted as progressing this achievement.

### Environment

Windows 10 x64 under Docker.

**Comment by EmosewaMC** [comment]
Known issue due to missing script.  #213 fixes this but hasn't seen a push in a while.  If there isn't an update there soon I'll take a shot at fixing this

**Comment by EmosewaMC** [comment]
#213 was merged.  This can be closed safely
