### ISSUE TITLE
BUG: Make Error

### ISSUE THREAD

**Issue by AxtonF** [DarkflameUniverse/DarkflameServer#434]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [x] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The current version throws a make error, in detail this one:
```
/usr/bin/ld: libdGame.a(CppScripts.cpp.o): in function `CppScripts::GetScript(Entity*, std::string const&)':
CppScripts.cpp:(.text+0x5402): undefined reference to `vtable for FvPassThroughWall'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/WorldServer.dir/build.make:147: WorldServer] Error 1
make[1]: *** [CMakeFiles/Makefile2:683: CMakeFiles/WorldServer.dir/all] Error 2
make: *** [Makefile:114: all] Error 2
```
I did a bisect and found this commit 828c457614b3e672e5c146e345129613c605fa23 to be the cause of the error.

### Reproduction steps

Just clone the newest version and build it.

### Expected Behavior

Not failing the compilation.

### Environment

Ubuntu 21.04 VPS

**Comment by Xiphoseer** [comment]
Did you do a clean re-build with a fresh clone as the reproduction steps suggest?

The class is missing an explicit constructor, which might be an issue on older compilers?

**Comment by AxtonF** [comment]
I actually didn't I just did a `make clean` and `make`, but a fresh clone fixed it. Sorry for the inconvenience.

**Comment by Xiphoseer** [comment]
No worries, glad it works!
