### ISSUE TITLE
BUG: Plunger Gun item erroneously acts like mainhand item

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/DarkflameServer#438]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The "Plunger Gun" item given by Dusty Holster at the Launch Area of Avant Gardens does not work properly. It is correctly equipped as offhand item, but erroneously overwrites the action of the mainhand item: The shooting action is placed on action slot 1 instead of 3.

Live behavior for reference: https://youtu.be/QwT9VQNIHxo?t=455

### Reproduction steps

1. Accept the repeatable mission from Dusty Holster at the Launch Area of Avant Gardens
2. Equip the Plunger Gun item
:x: The shooting action is placed on action slot 1 instead of 3

### Expected Behavior

The shooting action should be placed on action slot 3

### Environment

WSL 2, Docker Compose setup

**Comment by EmosewaMC** [comment]
This is likely because equip item guesses which slot to equip the item to (according to the comment block in the function at least)

**Comment by Xiphoseer** [comment]
The plunger gun is a right hand item (type 6) in the DB, while at the same time the equipment location is set to `special_l`. That seems a bit like a contradiction
