### ISSUE TITLE
BUG: Plunger Gun is not removed from inventory when completing mission again

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/DarkflameServer#439]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The "Plunger Gun" item given by Dusty Holster at the Launch Area of Avant Gardens is not removed when completing the mission a second time.
I assume the reason for this is that the following check tests for `MISSION_STATE_READY_TO_COMPLETE` twice, while one of them should probably be `MISSION_STATE_COMPLETE_READY_TO_COMPLETE`:
https://github.com/DarkflameUniverse/DarkflameServer/blob/b7d7146821d8e3f0dd711b7e7f91e39745993a9f/dScripts/NpcCowboyServer.cpp#L29

### Reproduction steps

Complete the repeatable mission given by Dusty Holster at the Launch Area of Avant Gardens a second time
:x: The Plunger Gun item remains in your inventory

### Expected Behavior

The Plunger Gun item should be removed from your inventory

### Environment

WSL 2, Docker Compose setup

**Comment by EmosewaMC** [comment]
That is the correct assumption for the fix.  Feel free to put in the PR.  If you don't want to i'll do so later

**Comment by Marcono1234** [comment]
Thanks for the confirmation! Have created #444 for this now.
