### ISSUE TITLE
BUG: Character creation fails occasionally

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/DarkflameServer#440]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Version: 1e01423a935058edb7b1bc78dca20cc34e5ca467

Occasionally character creation fails; after clicking the checkbox on all dialogs a blank dialog (no text) with a green checkbox appears and you have to enter the character name again.

The server seems to log the following:
> [UserManager] Character object id unavailable, check objectidtracker!

Trying it again with the same exact name succeeds without issue (in one case it took me 3 tries).

Feel free to close this issue in case it provides too little information, or is not important enough.

### Reproduction steps

Cannot reproduce this reliably.
Was using character name "test3" and a random temporary name ("KiwiOrangeGamer").

### Expected Behavior

Character creation should not fail

### Environment

WSL 2, Docker Compose setup

**Comment by Wincent01** [comment]
Known issue for awhile. Has to do with a miss in the server trying to keep persistent object IDs sequential. A potential fix would be for the server to keep trying to retrieve a valid ID, or at least give it a few attempts, as to not hinder the player experience.

**Comment by aronwk-aaron** [comment]
@EmosewaMC didn't you fix this?

**Comment by EmosewaMC** [comment]
Yes
