### ISSUE TITLE
BUILD: Docker fails to build LUnpack

### ISSUE THREAD

**Issue by GlobbyGlobster** [DarkflameUniverse/DarkflameServer#454]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### Platform

Windows

### Architecture

x86

### Error Logs

<details>

 => CACHED [darkflameserver-main_setup lunpack 3/4] COPY ./thirdparty/LUnpack .                                                                         0.0s
 => ERROR [darkflameserver-main_setup lunpack 4/4] RUN apk add musl-dev --no-cache && cargo build --release                                             2.7s
 => CACHED [darkflameserver-main_setup prep 2/8] RUN apk add sqlite bash --no-cache                                                                     0.0s
 => CACHED [darkflameserver-main_setup prep 3/8] WORKDIR /setup                                                                                         0.0s
 => CACHED [darkflameserver-main_setup prep 4/8] COPY resources/ resources/                                                                             0.0s
 => CACHED [darkflameserver-main_setup prep 5/8] COPY migrations/cdserver/ migrations/cdserver                                                          0.0s
 => [darkflameserver-main_account-manager internal] load build context                                                                                  0.1s
 => => transferring context: 528B                                                                                                                       0.0s
 => [darkflameserver-main_brickbuildfix 1/2] FROM docker.io/library/python:3.9.9-slim@sha256:f4efbe5d1eb52c221fded79ddf18e4baa0606e7766afe2f07b0b330a9  0.0s
 => CACHED [darkflameserver-main_brickbuildfix 2/2] WORKDIR /empty_dir                                                                                  0.0s
 => CACHED [darkflameserver-main_account-manager 2/6] WORKDIR /usr/local/share/AccountManager                                                           0.0s
 => CACHED [darkflameserver-main_account-manager 3/6] COPY ./thirdparty/AccountManager .                                                                0.0s
 => CACHED [darkflameserver-main_account-manager 4/6] ADD docker/credentials_example.py credentials.py                                                  0.0s
 => CACHED [darkflameserver-main_account-manager 5/6] ADD docker/resources_example.py resources.py                                                      0.0s
 => CANCELED [darkflameserver-main_account-manager 6/6] RUN apk add libffi-dev build-base --no-cache && pip3 install -r requirements.txt                2.4s
------
 > [darkflameserver-main_setup lunpack 4/4] RUN apk add musl-dev --no-cache && cargo build --release:
#58 0.997 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
#58 1.295 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
#58 1.747 (1/1) Installing musl-dev (1.2.2-r3)
#58 2.054 OK: 127 MiB in 27 packages
#58 2.243 error: could not find `Cargo.toml` in `/build_LUnpack` or any parent directory
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apk add musl-dev --no-cache && cargo build --release]: exit code: 101
PS C:\Users\ComputerUser69420\Downloads\DarkflameServer-main(1)\DarkflameServer-main>

</details>

When I try to "docker compose up -d ---build" this happens. Pwease help!

**Comment by luke-sparks** [comment]
This is related to this commit https://github.com/DarkflameUniverse/DarkflameServer/commit/f914799b622b707f03c214ab3ae070ed5c2cc557

Because of this change you now how to checkout the submodules as well by running these commands in the root directory of the repo.

```
git submodule init
git submodule update
```
https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by Xiphoseer** [comment]
That's not a change introduced by that PR. You always needed `--recurse-submodules` otherwise the server fails building.

**Comment by EmosewaMC** [comment]
Closing due to misconfiguration.  Please reopen if issue persists with properly pulled server source.
