### ISSUE TITLE
The DLU Server is not permanently online

### ISSUE THREAD

**Issue by Akiqes** [DarkflameUniverse/DarkflameServer#465]
Hi Guys, 
first, congratulations on the success of releasing DLU.
I'm very happy to have again a chance to play a piece of my childhood.
Many thanks for it!

_Details:_
Linux / Ubuntu 20.04 
10.3.32 MariaDB

**My request:** I want to run the MasterServer in the Background, so I was normally using "screen".
At the start, it works fine. After four Days, the Server is not any more joinable and the console shows this message up:

[23-02-22 17:58:21] [MasterServer]: Got shutdown response
[23-02-22 17:58:34] [Test]: Quitting
Destroying MySQL connection!
[23-02-22 17:58:34] [MasterServer]: A server has disconnected
[23-02-22 17:58:46] [ChatServer]: A server has disconnected, erasing their connected players from the list.
[27-02-22 07:35:04] [Server]: Lost our connection to master, shutting DOWN!
Destroying MySQL connection!
[27-02-22 07:35:05] [WorldServer]: Lost our connection to chat.
[27-02-22 07:35:05] [Server]: Lost our connection to master, shutting DOWN!
Destroying MySQL connection!
[27-02-22 07:35:07] [Server]: Lost our connection to master, shutting DOWN!
[27-02-22 07:35:28] [Test]: Quitting
Destroying MySQL connection!

**So two question:**
How can I find the reason for it? (where are the real logs)
and...
How did you guys, run your MasterServer (in the background) permanently Online.

I tried many creative things with no result. Hopefully we find a solution.

Best regards
Akiqes

**Comment by Racater** [comment]
This problem is not related to DLU.
To run the process in the background, you can also use tmux, the modern version of screen (`sudo apt-get install tmux`).
To tart a session, run `tmux`, start the server and then use ctrl+b, then d to detach the session.
To re-attach the session, simply use `tmux attach`

Please share if the problem persists.

**Comment by averysumner** [comment]
> This problem is not related to DLU. To run the process in the background, you can also use tmux, the modern version of screen (`sudo apt-get install tmux`). To tart a session, run `tmux`, start the server and then use ctrl+b, then d to detach the session. To re-attach the session, simply use `tmux attach`
> 
> Please share if the problem persists.

If you plan on running a server indefinitely, it's recommended to use the official docker container in combination with a daemon like systemd. Using screen or tmux is definitely a bandaid solution.

**Comment by DarwinAnim8or** [comment]
> > This problem is not related to DLU. To run the process in the background, you can also use tmux, the modern version of screen (`sudo apt-get install tmux`). To tart a session, run `tmux`, start the server and then use ctrl+b, then d to detach the session. To re-attach the session, simply use `tmux attach`
> > Please share if the problem persists.
> 
> If you plan on running a server indefinitely, it's recommended to use the official docker container in combination with a daemon like systemd. Using screen or tmux is definitely a bandaid solution.

(DLU ran on tmux all the time, feel free to do whatever you want lol)

**Comment by DarwinAnim8or** [comment]
As a more serious reply, DLU's test server got built every night and simply started it back up by sending it to the bg at the end of the shell script (using &), never had any issues

**Comment by averysumner** [comment]
> > > This problem is not related to DLU. To run the process in the background, you can also use tmux, the modern version of screen (`sudo apt-get install tmux`). To tart a session, run `tmux`, start the server and then use ctrl+b, then d to detach the session. To re-attach the session, simply use `tmux attach`
> > > Please share if the problem persists.
> > 
> > 
> > If you plan on running a server indefinitely, it's recommended to use the official docker container in combination with a daemon like systemd. Using screen or tmux is definitely a bandaid solution.
> 
> (DLU ran on tmux all the time, feel free to do whatever you want lol)

Doesn’t mean that should be recommended. :P

**Comment by Akiqes** [comment]
> This problem is not related to DLU. To run the process in the background, you can also use tmux, the modern version of screen (`sudo apt-get install tmux`). To tart a session, run `tmux`, start the server and then use ctrl+b, then d to detach the session. To re-attach the session, simply use `tmux attach`
> 
> Please share if the problem persists.

Thank you for your message, and also all others.
The Server is not anymore closing since I use tmux.
So, my problem is solved on my side. :)

Have a nice day!

Best regards
Akiqes
