### ISSUE TITLE
BUG: Friends show as two friends on the list

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#469]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When accepting a best friend request after a regular request, the user displays twice on the friends list. This is annoying with #468 in the equation.

![image](https://user-images.githubusercontent.com/48499798/157160338-d5aeffed-2ddb-4b57-950e-76c83b588cac.png)

### Reproduction steps

Have someone send you a friend request, accept it. Do the same for best friends, and they will appear twice on the list

### Expected Behavior

Not sure, but I know there aren't supposed to be listed twice. I'd just suggest making it so best friend requests do nothing.

### Environment

ubuntu server

**Comment by averysumner** [comment]
As far as I'm aware best friends were never actually implemented, we're probably just ignoring some best friends flag and allowing you to add someone as a friend twice.

**Comment by EmosewaMC** [comment]
This is not an issue with best friends.  This is an issue with being able to accept a request twice.  Fixed in a PR.
