### ISSUE TITLE
Invalid PK argument when starting MasterServer

### ISSUE THREAD

**Issue by H0-pe** [DarkflameUniverse/DarkflameServer#47]
When I try to run ./MasterServer on Ubuntu WSL I get this Error
![image](https://user-images.githubusercontent.com/48510733/144839827-ca8e661c-b4ee-4811-9d20-22834f5607c1.png)

The CDServer.sqlite is located in build/res/ and I have run the three scripts in migrations/cdserver

**Comment by Jettford** [comment]
This is likely due to the CDServer not existing or it being a bad SQLite file

**Comment by Landshark77** [comment]
Did you convert the cdclient.fdb file on the client to a sqlite database, then copied it and replaced it over the CDServer.sqlite file under build/res?

**Comment by H0-pe** [comment]
I copied a new version of the sqlite file now this error is gone but now I have a new one for some reason. Now without any plaintext stacktrace or error message
![image](https://user-images.githubusercontent.com/48510733/144847153-19e3cef2-1ea9-4812-8d7d-ef43ce464522.png)
