### ISSUE TITLE
BUG: Dragons/Apes can attack you from above in Caldera Mar

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#470]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When fighting in the pit below the rock platforms in Caldera Mar (Crux Prime), Dragons/Apes can often deal damage to you.

### Reproduction steps

Walk underneath the platform a mini boss is residing on. You're likely to take damage from them.

### Expected Behavior

They shouldn't even be aggressive at that distance. 

### Environment

ubuntu server

**Comment by badooga** [comment]
I can also confirm that if you're on top of a platform for long enough, a bunch of stromlings will eventually gather directly below you in an attempt to get at you. While I don't mind this, it may be part of the same issue, where perhaps enemy player detection has too much vertical range to it in general.

**Comment by aronwk-aaron** [comment]
this should be fixed with #1250
