### ISSUE TITLE
DOC: Windows native builds

### ISSUE THREAD

**Issue by johntor** [DarkflameUniverse/DarkflameServer#472]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that the documentation is wrong or missing on the latest version of the main branch of DarkflameServer

### Location of the documentation

Windows builds (native)

### Documentation problem

The setup procedure of the tools is confusing and not working.

### Suggested fix for documentation

If someone managed to make this work please provide more details how to setup the building environment. 

when I try to generate make files with 
```
C:\DarkflameServer\build> cmake ..
```

I get the following error:

```
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/DarkflameServer/build/CMakeFiles/CMakeOutput.log". 

```

I have installed [Clang](https://github.com/llvm/llvm-project/releases/) and [CMake](https://cmake.org/download/) as suggested but I think 'nmake' is a part of MSVC which is not installed.

Please provide any help!

**Comment by Jettford** [comment]
Clang is not supported in DLU as it has not been configured by anyone yet, I would attempt to use MSVC, however yes better docs are needed.

**Comment by averysumner** [comment]
> Clang is not supported in DLU as it has not been configured by anyone yet, I would attempt to use MSVC, however yes better docs are needed.

Since when does DLU not support clang? The problem here is unrelated to clang, his cmake install hasn't recognized his compiler.

**Comment by johntor** [comment]
> Since when does DLU not support clang? There's a reason I put that in the README... The problem here is unrelated to clang, his CMake install hasn't recognized his compiler. He also needs have ninja installed, but as far as I was aware that usually came packaged with CMake on Windows... We do need to add a CMakePreset for clang.

Ninja is not installed by default can you please test the procedure and provide some information? 

I think it is silly to deploy a VM just to play on my own while I can have just a few .exes to start a game!

Thank you!

**Comment by codeshaunted** [comment]
> > Since when does DLU not support clang? There's a reason I put that in the README... The problem here is unrelated to clang, his CMake install hasn't recognized his compiler. He also needs have ninja installed, but as far as I was aware that usually came packaged with CMake on Windows... We do need to add a CMakePreset for clang.
> 
> Ninja is not installed by default can you please test the procedure and provide some information?
> 
> I think it is silly to deploy a VM just to play on my own while I can have just a few .exes to start a game!
> 
> Thank you!

Apparently clang builds broke and no one decided to update the README. Your best bet is to attempt with MSVC.

**Comment by EmosewaMC** [comment]
Clang builds still work on x86 from my experience.  Can you confirm this?

**Comment by Jettford** [comment]
Clang builds do work however they don't work out of the box as they aren't configured

**Comment by EmosewaMC** [comment]
using the build.sh script on windows with msvc installed will always build the server.  Closing since we have improved the build step to fix this issue at some point.
