### ISSUE TITLE
BUG: Opening Property interface kicks client

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#482]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Just updated to the latest commit, and now opening the property interface kicks the client (to login screen). Another user is getting the same issue.

### Reproduction steps

just open the property interface

### Expected Behavior

no crashes

### Environment

ubuntu server

**Comment by aronwk-aaron** [comment]
Can reproduce, looking into it

**Comment by EmosewaMC** [comment]
investigating now

**Comment by EmosewaMC** [comment]
we found the issue.  I am a dum

**Comment by EmosewaMC** [comment]
Issue should be fixed.  Re-open this issue if it persists.

**Comment by EmosewaMC** [comment]
> Still broken :D @EmosewaMC

Did you run the new SQL migration for the mysql database?

**Comment by MustacheMan2** [comment]
didn't know until now that was a thing, and trying to figure out how now
