### ISSUE TITLE
BUG: Crashing upon claiming of Property (Repeatedly)

### ISSUE THREAD

**Issue by Defaltex** [DarkflameUniverse/DarkflameServer#486]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

I do entirely realize that this issue has been brought up before, but I don't know any better way to ask for further help.
In terms of scripting and Linux all of this, I am not fluent in any of it, so that's why I make this (while some of it may be my fault or not.)

I am crashing every time I interact with the property panel.

Here is an image of the script.
![image](https://user-images.githubusercontent.com/30538243/161191864-36b5fc39-0a93-45ad-b13c-0b61434bccbc.png)

I understand if you mark this as repetitive immediately or delete it, but please read over it first.

### Reproduction steps

Reproduction Steps:
Upon coming back (from previous crashes) and defeating the spider boss and what have you, I go through the quest to access the terminal. After I press the green checkmark, the server greets me with a "Fatal error -1" in Ubuntu, and it closes shortly after.

I am playing single player, if that helps any.

### Expected Behavior

Expected Behavior: I expect it to not crash.

Current Behavior: I crash every time.

### Environment

Environment:
Running on Windows 11 (i know, terrible)

Installed WSL (wsl --install) through command prompt, and also used Ubuntu and MariaDB.
(Followed https://www.youtube.com/watch?v=BwJG1nVuZUQ)

16 GB of ram, if that helps.

**Comment by Defaltex** [comment]
just as a reminder, i have 0 clue on what i'm doing since i followed a video 95% of the time (and refer back every time i restart the server), so idk what "check the new sql migrations to mysql" means. thanks!

**Comment by EmosewaMC** [comment]
Did you run the new migrations in the migrations/dlu folder?

**Comment by EmosewaMC** [comment]
I have tested deleting the performance_cost column from the properties table and this does cause a crash when the player interacts with the console.  Please run the migration listed above and feel free to open this back up should issues continue.
