### ISSUE TITLE
no such table: ActivityRewards

### ISSUE THREAD

**Issue by H0-pe** [DarkflameUniverse/DarkflameServer#49]
Sorry for opening another Issue I got confused last time.

I want to setup the Server on Ubuntu running in WSL. This is the Error message:

![image](https://user-images.githubusercontent.com/48510733/144851873-9ef66956-5bc2-4864-9c1e-25194e33061b.png)

These are the contents of build/res
![image](https://user-images.githubusercontent.com/48510733/144852110-90ed00a4-2537-4720-a8fa-1eff4f6fe7ed.png)

And as it seems like, the Table ActivityRewards should exist in the DB
![image](https://user-images.githubusercontent.com/48510733/144852368-bd2df44d-604d-4ebe-9b89-7b0af4632d53.png)

**Comment by DiarrAniki** [comment]
what did you do to fix it?

**Comment by Tyrobag** [comment]
@H0-pe I'm having the same issue, would you be willing to post how you solved it?

**Comment by Tyrobag** [comment]
Solved for me:
CDServer.sqlite is caps sensitive. I had used all lowercase when renaming it. Fixing that solved the issue.

**Comment by H0-pe** [comment]
I solved the issue by doing a full recompile and replacing the sqlite file with a new one. something probably got corrupted while executing the 3 scripts in migrations/cdserver.
