### ISSUE TITLE
MasterServer got an error: Access denied (using Password:NO)

### ISSUE THREAD

**Issue by Jodobofire** [DarkflameUniverse/DarkflameServer#50]
When I try to start the Masterserver: sudo ./MasterServer -a 
I get this message: [MasterServer]: Got an error while connecting to the database: Access denied for user 'root'@'localhost' (using password: NO)

Pls help :(

**Comment by Jettford** [comment]
Have you got your MySQL database setup?

**Comment by Jodobofire** [comment]
I followed this guide: https://gist.github.com/SunFlea/893fd80f39c7cf9ab31baacac284025d

So yeah i did the setup!
