### ISSUE TITLE
Quickbuilds do not bounce upon completion

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#511]
### Is your feature request related to a problem?

In live whenever a quickbuild was finished, it would bounce and do a small camera shake with the player celebrating. Shown clearly here: https://youtu.be/XtVI5429tkI?t=94

### Describe the solution you'd like

it's a missing feature that could be added.

**Comment by EmosewaMC** [comment]
Dupe of #446
