### ISSUE TITLE
BUG: UI problems for vendors that give missions

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#512]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

80a0988

### Issue Description

Two examples of what happens when interacting with vendors that give missions. This was not an issue some time ago.

https://user-images.githubusercontent.com/48499798/164038266-08a03a5c-0484-43c9-b460-58831246f91d.mp4

https://user-images.githubusercontent.com/48499798/164038283-4ceec18f-ec79-4a37-81fe-41c7f2d11175.mp4

### Reproduction Steps

This only happens once per vendor per session, then they will work as intended until you leave the world and return.

### Expected Behavior

Only what you clicked should be showing up.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
This has been an issue on dlu since launch.  Low priority since it doesn't affect anything adverse.

**Comment by EmosewaMC** [comment]
This seems to have been fixed at some point?  I cannot reproduce this on main anymore even on a world server with only 1 player and the first thing done being an interact with an NPC.  Please re-open if this is still persistent with a reproduction.

**Comment by MustacheMan2** [comment]
> This seems to have been fixed at some point? I cannot reproduce this on main anymore even on a world server with only 1 player and the first thing done being an interact with an NPC. Please re-open if this is still persistent with a reproduction.

I encountered it literally this past week as usual, so unless it coincidentally became fixed in the past day or two, it's probably still there. Will post again soon with fresh evidence.

**Comment by EmosewaMC** [comment]
Please post the charxml state just before the reproduction as well

**Comment by MustacheMan2** [comment]
Alright this does seem to be largely fixed as of recently, including on a new character and a character that's existed since DLU's release. I've observed it happen once in the span of the past few days, so take that whatever way you want.
