### ISSUE TITLE
BUG: Property mission givers are not vacuumed away

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#515]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

80a0988

### Issue Description

After completing all missions for a mission giver on a property, the npc remains there until later.

### Reproduction Steps

just complete all missions for block yard or others such as claim avant grove

### Expected Behavior

https://youtu.be/syVKfp08ibc?t=151

The npcs should be shown being vacuumed away once they are not giving missions.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
cause of this issue has been isolated.

**Comment by EmosewaMC** [comment]
Closing as the actual issue is #1222
