### ISSUE TITLE
BUG: Spinjitzu Initiate Achievement Not Working

### ISSUE THREAD

**Issue by Sc0utGuy** [DarkflameUniverse/DarkflameServer#517]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

e85cf46

### Issue Description

The "Spinjitzu Initiate" achievement on Crux Prime does not seem to work. I have tried using both Imagination and Ice Spinjitzu to smash skeletons and maelstrom enemies, however no matter what manner I try to smash them in (hitting them with a weapon or using spinjitzu) contributes towards progress for the achievement.

### Reproduction Steps

Try smashing an enemy using spinjitzu on crux prime, the result should be that no progress is gained towards the achievement.

### Expected Behavior

The way I assume the achievement is supposed to work normally is you simply smash an enemy using spinjitzu which should give you progress towards the achievement, but instead it simply does nothing and there appears to be no way of actually completing the achievement.

### Environment

Microsoft Windows 10.

**Comment by EmosewaMC** [comment]
Known issue.  Need to figure out how to track the skill source of a kill so we can progress the achievement.
