### ISSUE TITLE
Pet Cove pad at back of Lighthouse (Near Imagination brick)

### ISSUE THREAD

**Issue by leolion3** [DarkflameUniverse/DarkflameServer#52]
The pad at the back of the lighthouse (the one where the pet needs to stand above you) doesn't work.

When clicking shift the pet is supposed to stand on the pad while the player goes down to stand on the jump pad.

The pet instead decides to ignore the command and jump down with you.

**Comment by NealSpellman** [comment]
Not a bug, so please google for how things worked in Live before filling issues. This one requires someone else help you at the other position.

If you do not have another player, you can technically cheese it by jumping from the top of the lighthouse down into the overhang where the Imagination Brick is.
