### ISSUE TITLE
BUG: Friends aren't removed from friends list if they delete their character

### ISSUE THREAD

**Issue by fyreaken** [DarkflameUniverse/DarkflameServer#523]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

aca2bb1

### Issue Description

When a Friend deletes their character, they aren't completely removed from the friends list:

![unknown](https://user-images.githubusercontent.com/55700749/165375535-4e558f48-d88d-45be-8bb6-ebf926917b9f.png)

### Reproduction Steps

Add a player as a friend and have them delete their character.

### Expected Behavior

The friend should be completely removed from the friends list.

### Environment

Debian 11 Linux server

**Comment by EmosewaMC** [comment]
Didn't notice we already have an issue for this that also has a linked pr.  #267
