### ISSUE TITLE
BUG: Sound effects for powerup and token dispensers are missing in Nexus Tower

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#527]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [x] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

16b108f

### Issue Description

In the main sentinel room in NT, interacting with the dispensers for armor and health and tokens does not make any sound. Lots of other sound issues throughout the game but I likely won't be reporting them.

### Reproduction Steps

go up to the dispensers and press shift

### Expected Behavior

https://youtu.be/hJl8WvLz6rM?t=352
https://youtu.be/BPWcY_zblQY?t=2317

distinct sound effects for all dispensers

high priority

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Only the one in Nexus Tower is configured to play a sound. The Nimbus Station one is not configured to play a sound in vanilla as it does not contain a sound1 LNV key defining the sound GUID to play.
