### ISSUE TITLE
Flying and turbo-mechs in avant gardens survival

### ISSUE THREAD

**Issue by leolion3** [DarkflameUniverse/DarkflameServer#53]
The mechs in avant gardens survival run around with super speed and sometimes get stuck in mid air while running up the hill towards the player.

They also dont drop turrets (in the survival minigame) but I suppose this is the way its supposed to be.

**Comment by Jovl** [comment]
I was doing the quest where I need to build the turrets as well. Is it intended to not be in the game?

**Comment by averysumner** [comment]
Do you have CDServer.sqlite migrations applied?

**Comment by MickVermeulen** [comment]
This is related to AGS not having navmeshes, as a result their location is interpolated towards the client and therefore it might seem like they are flying. Not marking this as a bug but as an enhancement as this is the intended behavior, given the circumstances.

**Comment by leolion3** [comment]
As it is intended behaviour, one might aswell close the issue

**Comment by bytemage** [comment]
While this is not a bug, it makes the minigame unreasonably hard. Is there a way to create the navmesh for AGS? I understand that the focus is on making the server as stable as possible, but making the game "playable" is important too.
