### ISSUE TITLE
BUG: Stuck at 0% loading for Nimbus Station

### ISSUE THREAD

**Issue by Marktimus** [DarkflameUniverse/DarkflameServer#532]
So I have been playing for maybe a total of 20 hours on my main character. I went to login to Nimbus station and I am stuck loading at 0%. I have restarted the game multiple times however I continue to be stuck in an infinite 0% loading screen. When I select another character/mini-figure I am however able to play the game normally and load in properly. However I cannot play on my main which is upsetting.

**Comment by EmosewaMC** [comment]
Not enough information here.  Client logs?  Server logs?  What git hash are you using?  Please follow the BUG template when submitting issues.

**Comment by Marktimus** [comment]
I am not stuck in Nimbus Station, I basically cannot load into the game. I am stuck on the Nimbus Station Loading Screen after selecting my minifigure from the main menu as I try to enter the game.

**SERVER INFO**
SERVERNAME=0:Unofficial BZPower Darkflame Lego Universe (US),
PATCHSERVERIP=0:dlu.bzprpg.com,
AUTHSERVERIP=0:dlu.bzprpg.com,
PATCHSERVERPORT=1:80,
LOGGING=1:100,
DATACENTERID=5:150,
CPCODE=1:89164,
AKAMAIDLM=7:0,
PATCHSERVERDIR=0:luclient,
UGCUSE3DSERVICES=7:1,
UGCSERVERIP=0:dlu.bzprpg.com,
UGCSERVERDIR=0:3dservices,
PASSURL=0:dlu.bzprpg.com,
SIGNINURL=0:dlu.bzprpg.com,
SIGNUPURL=0:https://dlu.bzprpg.com/activate,
REGISTERURL=0:https://dlu.bzprpg.com/activate,
CRASHLOGURL=0:https://dlu.bzprpg.com,
LOCALE=0:en_US,
TRACK_DSK_USAGE=7:1

**Comment by EmosewaMC** [comment]
The above is not client logs. The above is your boot.cfg file.

Please provide the server side logs located in the /logs folder as well as the client located in %localappdata%/LEGO\ Software/LEGO\ universe/Log\ Foles

**Comment by EmosewaMC** [comment]
I also have to delete your above comment @Marktimus because it listed a public facing server ip.  We do not condone or endorse sharing of public facing servers.

**Comment by Marktimus** [comment]
Here is the client log and this issue is not just me, All of my friends on this server cannot access Nimbus Station


16:00:08	2		Starting client in location C:\Users\marks\Downloads\LEGO Universe (unpacked)\legouniverse.exe, currDir(C:\Users\marks\Downloads\LEGO Universe (unpacked))
16:00:09	3	RESOURCE	ResMgr could not find file: mesh\miscellaneous\Create_Frame1.NIF
16:00:09	3	RESOURCE	ResMgr could not find file: mesh\miscellaneous\Create_Frame2.NIF
16:00:09	3	RESOURCE	ResMgr could not find file: mesh\miscellaneous\Feedback2.NIF
16:00:09	3	RESOURCE	ResMgr could not find file: mesh\miscellaneous\Login.NIF
16:00:09	3	RESOURCE	Warning!  File missing [mesh\miscellaneous\Create_Frame1.NIF]
16:00:09	3	RESOURCE	Warning!  File missing [mesh\miscellaneous\Create_Frame2.NIF]
16:00:09	3	RESOURCE	Warning!  File missing [mesh\miscellaneous\Feedback2.NIF]
16:00:09	3	RESOURCE	Warning!  File missing [mesh\miscellaneous\Login.NIF]
16:00:09	4		BrickIDTable: LOT 5597 (design ID 64290) is an alias-duplicate of LOT 5308 (design ID 32525)
16:00:11	3	GUI	Error: Second parameter of Object.registerClass(wt, undefined) should be function or null
16:00:11	2	GUI	Using ScrollingList without a movie clip! BAD!A
16:00:11	2	GUI	resetting rename UI
16:00:11	2	GUI	Message 'OnItemRollout' was sent but no listeners were found.
16:00:11	2	GUI	Message 'ToggleToolTipRollover' was sent but no listeners were found.
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:11	2	GUI	WARNING! Using a MovieClipLocation without a valid MovieClip!
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:11	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 18
16:00:11	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 34
16:00:11	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 24
16:00:11	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 24
16:00:11	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 24
16:00:11	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 24
16:00:11	2	GUI	attempting to set text 'All the Gear' on undefined textField
16:00:11	2	GUI	attempting to set text 'All the Minigames' on undefined textField
16:00:11	2	GUI	attempting to set text 'All the Bricks' on undefined textField
16:00:11	2	GUI	attempting to set text 'All the Action' on undefined textField
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:11	2	GUI	WARNING! Using a MovieClipLocation without a valid MovieClip!
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:11	2	GUI	WARNING! Using a MovieClipLocation without a valid MovieClip!
16:00:11	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:16	2	GUI	Requesting Vignette...
16:00:18	2	GUI	Requesting Vignette...
16:00:20	2	GUI	Requesting Vignette...
16:00:23	2		Attempting to connect to Auth...
16:00:23	2	GUI	Sending login request...
16:00:23	2		RakNet base connection to Auth acquired.  Sending version...
16:00:23	2		Connection to Auth confirmed. (NetID 0)
16:00:23	2		Submitting Login info to Auth...
16:00:24	2		Stamp PASSPORT_AUTH_LEGOINT_RECEIVED(44) at 14000 (start+0, last+0)
16:00:24	2		Attempting to connect to World...
16:00:24	2		Auth rejected/terminated connection.
16:00:24	2		RakNet base connection to World acquired.  Sending version...
16:00:24	2		Connection to World confirmed. (NetID 1)
16:00:24	2		Submitting Validation to World... (accnt: Marktimus, key: e7eae5cd25133d39f00ac52703ffabb4)
16:00:24	2		Received Character List
16:00:24	2		A camera with ID: 0 already exists
16:00:24	2		A camera with ID: 8 already exists
16:00:24	2	GUI	Message 'ResetFreeTrialRenameUI' was sent but no listeners were found.
16:00:24	2	GUI	resetting rename UI
16:00:24	2	GUI	Message 'OnItemRollout' was sent but no listeners were found.
16:00:25	2	GUI	login playing roll out
16:00:26	2	GUI	login playing roll out
16:00:36	2	GUI	The message sent named "ShowFreeTrialMembershipDialog" had no listeners.
16:00:38	5		No boot configuration found; it's likely that the working directory is incorrect.
16:00:38	2		Sending Character Login Request...
16:00:38	2	GUI	Message 'OnItemRollout' was sent but no listeners were found.
16:00:38	3	GUI	Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
16:00:38	3	GUI	Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
16:00:38	3	GUI	Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
16:00:38	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:38	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:43	2		Received TransferToWorld (ip 52.72.255.188, port 3006)
16:00:43	2		Attempting to connect to World...
16:00:43	2		Connection to 'Unknown Server' Dropped. (ID 1, IP 52.72.255.188, Port 3003, Reason: 2)
16:00:47	3		SysAddressToNetID can't find sysAddress! 52.72.255.188:3006 
16:00:47	2		Connection to World Dropped. (ID -1, IP 52.72.255.188, Port 3006, Reason: 1)
16:00:47	2	GUI	The message sent named "FreeTrialBrowserHandler" had no listeners.
16:00:47	2	GUI	The message sent named "WebBrowserHide" had no listeners.
16:00:47	2	GUI	Message 'OnItemRollout' was sent but no listeners were found.
16:00:47	2	GUI	sendMessage: Not delivering "ToggleToolTipRollover" to widget TooltipRollover
16:00:47	2		A camera with ID: 0 already exists
16:00:47	2		A camera with ID: 8 already exists
16:00:47	3	GUI	Error: Second parameter of Object.registerClass(wt, undefined) should be function or null
16:00:47	2	GUI	Using ScrollingList without a movie clip! BAD!
16:00:47	2	GUI	Message 'OnItemRollout' was sent but no listeners were found.
16:00:47	2	GUI	Message 'ToggleToolTipRollover' was sent but no listeners were found.
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	WARNING! Using a MovieClipLocation without a valid MovieClip!
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	WARNING! Using a MovieClipLocation without a valid MovieClip!
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	Message 'DisplayTutorial' was sent but no listeners were found.
16:00:47	2	GUI	Message 'DisplayTutorial' was sent but no listeners were found.
16:00:47	2	GUI	Message 'DisplayTutorial' was sent but no listeners were found.
16:00:47	2	GUI	Message 'DisplayTutorial' was sent but no listeners were found.
16:00:47	2	GUI	Message 'DisplayTutorial' was sent but no listeners were found.
16:00:47	2	GUI	Message 'DisplayTutorial' was sent but no listeners were found.
16:00:47	2	GUI	Message 'DisplayTutorial' was sent but no listeners were found.
16:00:47	2	GUI	Message 'DisplayTutorial' was sent but no listeners were found.
16:00:47	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 18
16:00:47	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 34
16:00:47	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 24
16:00:47	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 24
16:00:47	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 24
16:00:47	2	GUI	TextResizer given an undefined TextField instance: undefined target font size: 24
16:00:47	2	GUI	attempting to set text 'All the Gear' on undefined textField
16:00:47	2	GUI	attempting to set text 'All the Minigames' on undefined textField
16:00:47	2	GUI	attempting to set text 'All the Bricks' on undefined textField
16:00:47	2	GUI	attempting to set text 'All the Action' on undefined textField
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	3	GUI	Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
16:00:47	3	GUI	Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
16:00:47	3	GUI	Missing "$LU_Boldfont" glyph ' ' (0xa0) in "_level0.loadingScreenLayer.LoadingScreenMC.firstTimeContainer.IntroDesc2".
Font has 1076 glyphs, ranges 0x20-0x7e, 0xa1-0x24f, 0x2c6, 0x2dc, 0x1e00-0x1eff (truncated).
Search log: 
   Searching for font: "$LU_Boldfont" 
      Movie resource: "$LU_Boldfont"  not found.
      Imports       : "$LU_Boldfont"  not found.
                    : "..\ingame\gfxfontlib.swf".
      Exported      : "$LU_Boldfont"  not found.
      Applying GFxFontMap: "$LU_Boldfont"  mapped to "Arial Rounded MT Bold"
      Searching GFxFontLib: "Arial Rounded MT Bold"  found.
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	2	GUI	Message 'OnItemRollout' was sent but no listeners were found.
16:00:47	2	GUI	WARNING! Using a MovieClipLocation without a valid MovieClip!
16:00:47	2	GUI	The message sent named "GFxWidgetLoaded" had no listeners.
16:00:47	3	RESOURCE	ResMgr could not find file: mesh\miscellaneous\Create_Frame1.NIF
16:00:47	3	RESOURCE	ResMgr could not find file: mesh\miscellaneous\Create_Frame2.NIF
16:00:47	3	RESOURCE	ResMgr could not find file: mesh\miscellaneous\Feedback2.NIF
16:00:47	3	RESOURCE	ResMgr could not find file: mesh\miscellaneous\Login.NIF
16:00:47	3	RESOURCE	Warning!  File missing [mesh\miscellaneous\Create_Frame1.NIF]
16:00:47	3	RESOURCE	Warning!  File missing [mesh\miscellaneous\Create_Frame2.NIF]
16:00:47	3	RESOURCE	Warning!  File missing [mesh\miscellaneous\Feedback2.NIF]
16:00:47	3	RESOURCE	Warning!  File missing [mesh\miscellaneous\Login.NIF]
16:00:48	2	GUI	resetting rename UI
16:00:52	2	GUI	Requesting Vignette...
16:00:54	2	GUI	Requesting Vignette...
16:00:57	2	GUI	Requesting Vignette...
16:01:53	2	GUI	Requesting Vignette...
16:02:01	2	GUI	Requesting Vignette...
16:02:06	2	GUI	Requesting Vignette...
16:02:38	2	GUI	Requesting Vignette...
16:02:41	2	GUI	Requesting Vignette...
16:02:45	2	GUI	Requesting Vignette...

**Comment by EmosewaMC** [comment]
I need your server logs too as specified earlier.

**Comment by EmosewaMC** [comment]
Also, what is the server information? are you running this on wsl, windows, macos, aarch64?  We need all this info

**Comment by Marktimus** [comment]
I apologize for my lack of knowledge regarding server information. Where can I locate the build/log folder? Also, I am running on Windows. I don't believe this problem is linked to me however, I'm assuming this is server wide. Everyone in this server I have talked to cannot access Nimbus Station right now

**Comment by EmosewaMC** [comment]
This is likely a misconfiguration on your end because multiple others run on windows and are able to load into nimbus just fine. The build/logs folder is in the darkflameserver/build/logs.

**Comment by EmosewaMC** [comment]
Went ahead and tested Windows Nimbus Station and can confirm I am able to load into Nimbus Station just fine the latest commit with a correctly setup server.

**Comment by Marktimus** [comment]
I'm not sure sure how I would have a network problem. I can play the game perfectly in every location except Nimbus Station. I've tried reinstalling the game for the small chance that I was missing files. However this did not work either. I'm by no means an expert when it comes to this sort of thing so I will take your word for it. Do you know any troubleshooting techniques I could try?

**Comment by EmosewaMC** [comment]
check your logs folder first.  See what the server is doing because without knowing what the server is doing you cannot diagnose the issue.  If the logs for when someone connects to a world look identical to what they would look like for others then i've no clue what else to do.  Rebuilding the server from scratch would maybe fix the issue but i cant guarantee anything or offer more help because I have not encountered this before.

**Comment by Marktimus** [comment]
What should my logs look like? and I'm sorry for not knowing how to do any of this. I'm still having difficulty locating my server logs can you give me the full directory path of where to locate this? 

Also, my friends (each have different networks) just tried to load into Nimbus Station as well and they are having same issue. If I can't get this to work I don't know how I can continue playing.

**Comment by EmosewaMC** [comment]
The full directory path is DarkflameServer/build/logs.  There is nothing I can do for getting your server to work.  This issue is not present on WSL, Windows or mac servers at the moment.

**Comment by Marktimus** [comment]
Sounds good Ill just wait until enough people have this problem

**Comment by EmosewaMC** [comment]
I have scrubbed this thread of comments that contain public ips.  Please contact your server admin for further help.
