### ISSUE TITLE
Corrupted Sentries in Return to Venture Explorer not working

### ISSUE THREAD

**Issue by Hardrocknerd** [DarkflameUniverse/DarkflameServer#54]
I just got to Return to Venture Explorer for the first time (so far everything else has been working great!) and the Corrupted Sentries are neither attacking nor attackable. They show a red (not purple!) health bar and walk around passively, but are not interactable in any way, which keeps me from doing the mission to smash 6 of them. The other enemies, both Stromlings and Spiderlings, are working as expected.
I'm running the server on WSL and the game on Windows, in case that might be relevant.

**Comment by averysumner** [comment]
Seems like an issue with object “factions” not being applied properly.

**Comment by MickVermeulen** [comment]
Update on this: I'm working on a fix.

**Comment by CloudyCrayons** [comment]
This is what I will be doing for now. 

https://github.com/DarkflameUniverse/DarkflameServer/issues/71#issuecomment-988291600
