### ISSUE TITLE
BUG: Elephants do not consume peanuts upon taming

### ISSUE THREAD

**Issue by BrieFlory** [DarkflameUniverse/DarkflameServer#540]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

427c4a8c33fdb8eca06abd49477e70816f00530b

### Issue Description

Currently, taming an elephant pet does not consume the peanuts item in your backpack. This is what would happen in live -- to tame more, you would need to purchase more peanuts from the pirate camp.

### Reproduction Steps

* Obtain peanuts
* Tame an elephant in GF
* Note that peanuts remain in your backpack

### Expected Behavior

Peanuts should be consumed upon successful taming. This behavior exists for the Earth Dragon and the Rockolate Bar.

### Environment

Windows client, Linux server

**Comment by codeshaunted** [comment]
Anyone know whether or not this is a one-off scripted behavior or not?

**Comment by EmosewaMC** [comment]
> Anyone know whether or not this is a one-off scripted behavior or not?

no clue - ill take a look at packet captures and see if theres anything in there.

**Comment by EmosewaMC** [comment]
It looks like this doesnt happen with the Earth Dragon pet either.

**Comment by codeshaunted** [comment]
Interesting, I feel like if it was in a Lua script we would've implemented
it. Maybe it's a base feature we just forgot about?

**Comment by EmosewaMC** [comment]
Potentially.  The client does not allow you to tame the pet if you don't have the items so perhaps on completion we are supposed to take the items from the inventory.

**Comment by aronwk-aaron** [comment]
> It looks like this doesnt happen with the Earth Dragon pet either.

This does happen with the earth pet, though?
The server side scripts for the earth dragon is implemented and has a precondition for taking the choco bar from the looks of it. Can test it out to be sure.

Looks like the elephant has no script components, so it may just be something in the main pet server to handle it?

**Comment by EmosewaMC** [comment]
> This does happen with the earth pet, though? 
It does not.  Just tested taming the earth dragon pet and it failed to take my rockolate bars on completion or fail.

**Comment by aronwk-aaron** [comment]
> Edit: NVM It does take them. I forgot i was GM 9.

yep, just checked as well (didn't see your comment until now lol)

**Comment by EmosewaMC** [comment]
Believe the issue here is the petComponent never checks for the preconditions for anything besides the earth dragon pet.

**Comment by aronwk-aaron** [comment]
yep, that's my exact thought, I'll see if I can find if there is a precondition for the elephant
