### ISSUE TITLE
BUG: News popup appears on every world load

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#542]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

a1a3453

### Issue Description

Every time a world is loaded (all except racing and shooting gallery), the News window pops up.

### Reproduction Steps

Simply change worlds

### Expected Behavior

https://youtu.be/FYqjZBnuBIg?t=169

Only when logging in should this appear

### Environment

ubuntu server

**Comment by aronwk-aaron** [comment]
This is most likely because each world load is a new session, related to #468

**Comment by EmosewaMC** [comment]
As aron has mentioned, this is beacuse when you go to a new world, the game treats it as a new session every time.  The ideal solution would be fixed alongside the above linked issue.

**Comment by EmosewaMC** [comment]
We have figured out the correct solution to this problem.  A fix will be coming soon.
