### ISSUE TITLE
BUG: Property performance bars are always at 0

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#543]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

a1a3453

### Issue Description

When viewing the property launchpad interface, all ping icons in the corner of the property buttons are at 0. Numbers go up when placing models/bricks, but doesn't save.

### Reproduction Steps

interact with a property launchpad

### Expected Behavior

https://youtu.be/FYqjZBnuBIg?t=118

It should display varying performance numbers based on how many models/bricks are on the property

### Environment

ubuntu server

**Comment by aronwk-aaron** [comment]
this was fixed in #479
update your server

**Comment by EmosewaMC** [comment]
This works on the lastest commit.

**Comment by MustacheMan2** [comment]
@aronwk-aaron my server is definitely updated
