### ISSUE TITLE
BUG: Beck Strongheart's Mail isn't sent when claiming Block Yard

### ISSUE THREAD

**Issue by BrieFlory** [DarkflameUniverse/DarkflameServer#548]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

427c4a8c33fdb8eca06abd49477e70816f00530b

### Issue Description

During Live, Beck would send you a congratulatory piece of mail alongside a bag of bricks when first claiming Block Yard. It looks like this was staggered somewhat from when Overbuild would send his message about Nimbus Rock.

### Reproduction Steps

* Claim Block Yard
* Check Mailbox

### Expected Behavior

https://youtu.be/syVKfp08ibc?t=25

<img width="335" alt="image" src="https://user-images.githubusercontent.com/25165624/166926647-129b200a-e8b9-4733-9fbe-81ce015fc076.png">

### Environment

Windows client, Linux server

**Comment by aronwk-aaron** [comment]
Note to self, check activities
