### ISSUE TITLE
Cutscene not loading and stuck on Re-Connect

### ISSUE THREAD

**Issue by Mezalion** [DarkflameUniverse/DarkflameServer#55]
I got the Server to work and i can connect to it. Once i try to launch with a Charakter however it doesnt load the Cuscene and only the Text in the left bottom appears. When restarting the Client it wont load into Venture Explorer, taking forever to load to 53% and then stopping. I am using MariaDB and the Client from Nexus Launcher, the Server is on a Ubuntu 20.something VPS. Changed the Buildversion in the CMakefile before building the Server. Might be a Clientproblem, but it works just fine in Uchu.

**Comment by Mezalion** [comment]
![grafik](https://user-images.githubusercontent.com/87936737/144884032-5d64d393-ed0e-4c52-985e-a5a1aa8bcc0d.png)
Dont know if this belongs to it, but since even a new client is not working and is having the same issue i thought that i maybe connected.

**Comment by NealSpellman** [comment]
Have you run the migrations we have in the repository? This looks like you haven't. Please try to do so and let us know if there's still an issue.

**Comment by dddddddd207** [comment]
Check the WorldManager logs. (There's one set of WorldManager logs for the login screen and another for the ship.) If it says something like "can't load scene: file not found", make sure you've lowercased all the files in the `res/maps` directory as described in #22. That fixed it for me.

**Comment by Mezalion** [comment]
> Check the WorldManager logs. (There's one set of WorldManager logs for the login screen and another for the ship.) If it says something like "can't load scene: file not found", make sure you've lowercased all the files in the `res/maps` directory as described in #22. That fixed it for me.

Nope, nothing like this in the Logs.

**Comment by Mezalion** [comment]
> Have you run the migrations we have in the repository? This looks like you haven't. Please try to do so and let us know if there's still an issue.
> 
> EDIT: That should at least fix the InvalidScript problems, not sure if it'll fix the overall problem. Will let someone else chime in for the rest

I thought i did. Can i verify somehow that it was succesfull?

**Comment by Mezalion** [comment]
Ok, found another thing in the Serverconsole stating Error occured during namvesh-load, but no further specification. I am going to delete my namvesh-file and my CDServer.sqlite and do those two again.

**Comment by Mezalion** [comment]
> Ok, found another thing in the Serverconsole stating Error occured during namvesh-load, but no further specification. I am going to delete my namvesh-file and my CDServer.sqlite and do those two again.

Ok, i replaced both and did their processes. The Errors are still showing up. Testet different Clients as well.

**Comment by Mezalion** [comment]
Continued in new issue since problem has been mostly identified
