### ISSUE TITLE
BUG: Fatal error -1 Game crashes

### ISSUE THREAD

**Issue by TudiUrsu** [DarkflameUniverse/DarkflameServer#550]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

This last one https://github.com/DarkflameUniverse/DarkflameServer

### Issue Description

After I defeat the Spider Queen, I need to claim the block yard from the pannel, but when I do so, the game crashes and I get in log Fatal error 1-

![Screenshot 2022-05-08 115316](https://user-images.githubusercontent.com/105149155/167289228-c65dd581-29f3-48b1-a32c-3f4448693437.png)

### Reproduction Steps

Complete all missions till Spider Queen
Defeat Spider Queen and it will ask you to claim the block yard
After that go to the pannel and press Yes and the game crashes

### Expected Behavior

It suppose to let me claim the block yard and let me start building a house or a casttle.

### Environment

I m running DarkflameServer on a Windows 10, with 16gb of ram and a 1050 4GB Nvidia Geforce , with also a 1T hdd and a 500gb ssd.

**Comment by EmosewaMC** [comment]
Please run all the migrations as specified in the README.

See #500 
Closing due to known misconfiguration.
