### ISSUE TITLE
BUG: Boom trap kits don't explode

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#556]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

a1a3453

### Issue Description

boom trap kit currently can be built and remain for a short time before breaking

### Reproduction Steps

use and build a boom trap kit

### Expected Behavior

it should explode around enemies (on contact, on being hit, after a set time? unsure)

### Environment

ubuntu server

**Comment by aronwk-aaron** [comment]
Missing Server side script `scripts\ai\ACT\L_ACT_MINE.lua `
