### ISSUE TITLE
BUG: Client Crash when finishing gnarled forest race

### ISSUE THREAD

**Issue by Kam1ni** [DarkflameUniverse/DarkflameServer#560]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

44e17ea

### Issue Description

Finishing the race in the Gnarled Forest crashes the client. 

Client logs:
[Log Files.zip](https://github.com/DarkflameUniverse/DarkflameServer/files/8743544/Log.Files.zip)

Server logs:
[logs.zip](https://github.com/DarkflameUniverse/DarkflameServer/files/8743535/logs.zip)

### Reproduction Steps

1. Go to the gnarled forest race track.
2. Start a race
3. Finish the race
4. Crash

### Expected Behavior

Not crashing and returning to the gnarled forest.

### Environment

Docker with WSL2
nexus2 client

**Comment by EmosewaMC** [comment]
Nexus 2 client is incomplete.  Please only submit bugs with complete clients.
