### ISSUE TITLE
BUG: Unsmashable mechs in Avant Gardens Survival

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#565]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

915b779

### Issue Description

Typically only one but I've seen cases with more. These cannot be damaged but can attack you. Nametags are white.
![Lego Universe Screenshot 2022 05 25 - 17 35 51 13](https://user-images.githubusercontent.com/48499798/170728460-344bf57c-5950-4ed5-b273-e72722ad6b60.png)
 

### Reproduction Steps

No clear way to reproduce this, sometimes it happens sometimes not. Likely you'll witness it if you play a few rounds of AGS.

### Expected Behavior

All mechs should remain smashable.

### Environment

ubuntu server

**Comment by BDimaurizio** [comment]
any ideas on what causes this?

**Comment by MustacheMan2** [comment]
I haven't seen instances of this happen in a long time, so I'm going to assume its fixed.
