### ISSUE TITLE
BUG: Complete Server crashes when claiming first property in Avant Block Yard

### ISSUE THREAD

**Issue by devix56** [DarkflameUniverse/DarkflameServer#569]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

66215da

### Issue Description

The Server closes due to the WorldServer crashing when claiming the first property in Avant Block Yard.

The Mission, after destroying the Spiderqueen, is to claim the property via the console on the block yard. Instead of claiming it and continuing with the game, I get send back to the login screen. 

When I looked into the console log, I get this:

./WorldServer(+0xeb03f)[0x7fb7befac03f]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c)[0x7fb7be29a38c]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3f7)[0x7fb7be29a3f7]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa6a9)[0x7fb7be29a6a9]
/home/dlu/DarkflameServer/build/_deps/mysql-src/lib64/libmysqlcppconn.so.9(+0x73a7b)[0x7fb7be4a3a7b]
./WorldServer(+0x10ce1e)[0x7fb7befcde1e]
./WorldServer(+0x2231cc)[0x7fb7bf0e41cc]
./WorldServer(+0x22bdff)[0x7fb7bf0ecdff]
./WorldServer(+0x2635e2)[0x7fb7bf1245e2]
./WorldServer(+0x24d712)[0x7fb7bf10e712]
Error: signal -1:

Everything gets safed by the server before shutting down.

### Reproduction Steps

I followed the complete tutorial from this video, on how to set up the DarkflameServer: https://www.youtube.com/watch?v=4vDFu0c_X70

So far it worked perfectly without any performance or network issues. Only this bug has occurred.

### Expected Behavior

It would be great if you can fix something in the WorldServer because I think this is a game-breaking bug because you cannot continue on with the story.

### Environment

I run Ubuntu via WSL on Windows 10 with the latest build (19043).

**Comment by leolion3** [comment]
Just out of curiosity, how did you fix this bug? Is also happening with nimbus rock when no properties were claimed prior...
