### ISSUE TITLE
WSL Bluescreen when connecting to MySQL

### ISSUE THREAD

**Issue by leolion3** [DarkflameUniverse/DarkflameServer#57]
In order to run the server under WSL one hast to execute "sudo /etc/init.d/mysql start" before executing "./MasterServer". 
Sometimes when the MasterServer attempts to connect to MySQL it causes a BSOD because of memory leaks.

**Comment by averysumner** [comment]
Unable to reproduce, please give more details on platform and circumstances.

**Comment by leolion3** [comment]
I start the database using the given command and then run the server.
Im running Windows 11 Version 21H2. WSL Version 1 running Ubuntu 20.04.3 LTS.

**Comment by averysumner** [comment]
How do you know it is memory leaks in our software causing the BSOD?

**Comment by leolion3** [comment]
Ok so it happens when you forget to set the database name, username and password in the ini files. It causes a BSOD with "Memory Management Error"

**Comment by averysumner** [comment]
Caused by improper configuration, and unable to reproduce, closing issue.
