### ISSUE TITLE
Account Manager issue

### ISSUE THREAD

**Issue by Lego458** [DarkflameUniverse/DarkflameServer#571]
Hello All, 
I have been using Elocore's guide on Youtube and have got to the part where I run the application, however when I use 'python3 app.py' and copy & paste it into google it comes up a 'refused to connect' error. I don't know whether it is a mistake that I've made whilst following the steps or whether its something that I need to amend on my desktop. 

P.S Sorry if I haven't explained this in enough detail, I'm new to this.

Thanks in advance.

**Comment by EmosewaMC** [comment]
This is not the repository to make an issue with for account manager.  Please go to that repository and open an issue there.
