### ISSUE TITLE
DLU table schema not compatible with MySQL dialect

### ISSUE THREAD

**Issue by MasterEric** [DarkflameUniverse/DarkflameServer#58]
https://github.com/DarkflameUniverse/DarkflameServer/blob/main/migrations/dlu/0_initial.sql

This file contains the command `CREATE OR REPLACE`, which is only available on MariaDB, and is not available on many other variants of MySQL servers.

To maximize compatibility and minimize issues, the syntax of this file should be reworked to be compatible with other SQL dialects.

My proposed changes are:
* Remove `OR REPLACE` from each line and add `DROP TABLE IF EXISTS 'bla'; ` before each line. `DROP TABLE` is available and usable in more dialects.
* The `ugc` table includes a default value for the `filenname`. MySQL requires parenthesis around this value for the statement to be valid.

**Comment by aronwk-aaron** [comment]
Duplicates #4

**Comment by MickVermeulen** [comment]
Fixed on main.
