### ISSUE TITLE
BUG: Monument lasers don't function 100% properly

### ISSUE THREAD

**Issue by Terrev** [DarkflameUniverse/DarkflameServer#598]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

yadda yadda

### Issue Description

already discussed extensively on discord, this is largely just a reminder

- the animation/particle effect of the player being burned plays but the knockback isn't applied
- the particle effect/anim only plays the first time you walk into a laser, all times following that you just silently take 1 damage
- special laser death anim does not play upon dying, under any circumstances i can find

### Reproduction Steps

walk into monument laser trigger w/ sensor script

### Expected Behavior

https://youtu.be/dUE7YilB_wc?t=3
https://youtu.be/dUE7YilB_wc?t=179
https://youtu.be/dUE7YilB_wc?t=207

it should be casting this skill on the player
https://explorer.lu-dev.net/skills/163
https://explorer.lu-dev.net/skills/behaviors/15714/15713
(does 1 damage, applies knockback, and includes special laser death anim)
at least that's what the old pre-freetrial version of AG did on its triggers, and available footage of live post-freetrial seems to have the exact same effect, just accomplished via lua instead of lutriggers

lcdr — Yesterday at 4:22 PM
fwiw, these are the script implementations on lcdru:
https://github.com/lcdr/luserver/blob/master/luserver/scripts/avant_gardens/laser.py
https://github.com/lcdr/luserver/blob/master/luserver/scripts/avant_gardens/laser_sensor.py
iirc i implemented them pretty much the same way they worked in live

### Environment

punchcard machine

**Comment by aronwk-aaron** [comment]
noting here for future reference, the PR #1079 will not fix the death animation issue, I _think_ that has to do with how DLU is slightly improperly handling animation priorities (and by handling, I mean not handling cause it's just hardcoded, iirc)
