### ISSUE TITLE
Can't reach nimbus station

### ISSUE THREAD

**Issue by Walygo** [DarkflameUniverse/DarkflameServer#60]
when you try to leave avant garden and enter nimbus station, it just says "your game assets don't match the server. Please logout and try again"

No error message in the console

**Comment by gobboo** [comment]
Getting this too, worked fine this morning, updated some of the server files to match here and now it isn't working, idk if its cus i messed it up or not but I havent touched anything since

**Comment by gobboo** [comment]
Turns out I fixed it by retrying, idk what was wrong though

**Comment by Walygo** [comment]
> Turns out I fixed it by retrying, idk what was wrong though

doesnt work for me yet

**Comment by averysumner** [comment]
Possibly related to #42

**Comment by averysumner** [comment]
Can you try the fix outlined in #42 @Walygo?

**Comment by averysumner** [comment]
Closing this issue as it is stale and no extra communication has occurred. Reopen it if you’re still encountering this on the latest commit.
