### ISSUE TITLE
BUG: Property crashing on claim

### ISSUE THREAD

**Issue by shaynod** [DarkflameUniverse/DarkflameServer#602]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

94e161d

### Issue Description

Clicking on the terminal to claim a property and then clicking the check mark option to confirm creation results in a white screen and being kicked out to the login page

### Reproduction Steps

Travel to Block Yard for the first time 

Defeat the Queen Spider

Attempt to claim a property using the terminal

Click the check mark to confirm that you want to claim property

### Expected Behavior

Enable me to claim/start creating a property

### Environment

All

**Comment by NealSpellman** [comment]
Can you confirm you've run all the migrations specified in the README? This seems like you missed that step. Please also make sure to give your future bug reports a title and not just "BUG: ".

**Comment by shaynod** [comment]
Apologies, I actually found a solution to this by following the steps outlined in the following comment in a different thread about the issue: 

https://github.com/DarkflameUniverse/DarkflameServer/issues/500#issuecomment-1101644632
