### ISSUE TITLE
BUG: Pet digs do not display on minimap

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#610]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

cc25ec0

### Issue Description

Pet digs do not display on the minimap when a venture vision ability is active

### Reproduction Steps

1) activate venture vision ability
2) observe that pet digs do not show up on the map

### Expected Behavior

pet digs do show up on the map

### Environment

All

**Comment by EmosewaMC** [comment]
![image](https://user-images.githubusercontent.com/39972741/177693751-5596b823-9e83-4865-bc0b-2cc054aff8b1.png)
This is a live bug and will not be fixed.  Closing

**Comment by MustacheMan2** [comment]
The screenshot appears to not be of the latest live build, there is no bar for U-Score in the top left.
