### ISSUE TITLE
BUILD: make command error 2 in compiling

### ISSUE THREAD

**Issue by WildclawAvali** [DarkflameUniverse/DarkflameServer#613]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### DarkflameServer Version

8cdb388

### Platform

Ubuntu

### Architecture

x86

### Error Logs

<details>

[  0%] Performing build step for 'mariadb_connector_cpp'
[ 24%] Built target mariadb_obj
[ 24%] Built target libmariadb
[ 26%] Built target dialog
[ 27%] Built target mysql_clear_password
[ 29%] Built target sha256_password
[ 30%] Building C object libmariadb/CMakeFiles/caching_sha2_password.dir/libmariadb/secure/openssl_crypt.c.o
In file included from /home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/libmariadb/secure/openssl_crypt.c:20:
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:74:1: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   74 | MA_HASH_CTX *ma_hash_new(unsigned int algorithm, MA_HASH_CTX *ctx);
      | ^~~~~~~~~~~
      | MA_HASH_MD5
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:74:50: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   74 | MA_HASH_CTX *ma_hash_new(unsigned int algorithm, MA_HASH_CTX *ctx);
      |                                                  ^~~~~~~~~~~
      |                                                  MA_HASH_MD5
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:83:19: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   83 | void ma_hash_free(MA_HASH_CTX *ctx);
      |                   ^~~~~~~~~~~
      |                   MA_HASH_MD5
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:96:20: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   96 | void ma_hash_input(MA_HASH_CTX *ctx,
      |                    ^~~~~~~~~~~
      |                    MA_HASH_MD5
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:108:21: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
  108 | void ma_hash_result(MA_HASH_CTX *ctx, unsigned char *digest);
      |                     ^~~~~~~~~~~
      |                     MA_HASH_MD5
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h: In function ‘ma_hash’:
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:155:3: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
  155 |   MA_HASH_CTX *ctx= NULL;
      |   ^~~~~~~~~~~
      |   MA_HASH_MD5
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:160:8: warning: implicit declaration of function ‘ma_hash_new’; did you mean ‘ma_hash’? [-Wimplicit-function-declaration]
  160 |   ctx= ma_hash_new(algorithm, ctx);
      |        ^~~~~~~~~~~
      |        ma_hash
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:160:6: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  160 |   ctx= ma_hash_new(algorithm, ctx);
      |      ^
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:161:3: warning: implicit declaration of function ‘ma_hash_input’ [-Wimplicit-function-declaration]
  161 |   ma_hash_input(ctx, buffer, buffer_length);
      |   ^~~~~~~~~~~~~
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:162:3: warning: implicit declaration of function ‘ma_hash_result’ [-Wimplicit-function-declaration]
  162 |   ma_hash_result(ctx, digest);
      |   ^~~~~~~~~~~~~~
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:163:3: warning: implicit declaration of function ‘ma_hash_free’ [-Wimplicit-function-declaration]
  163 |   ma_hash_free(ctx);
      |   ^~~~~~~~~~~~
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/libmariadb/secure/openssl_crypt.c: At top level:
/home/ubuntu/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/libmariadb/secure/openssl_crypt.c:21:10: fatal error: openssl/evp.h: No such file or directory
   21 | #include <openssl/evp.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [libmariadb/CMakeFiles/caching_sha2_password.dir/build.make:76: libmariadb/CMakeFiles/caching_sha2_password.dir/libmariadb/secure/openssl_crypt.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:311: libmariadb/CMakeFiles/caching_sha2_password.dir/all] Error 2
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [thirdparty/CMakeFiles/mariadb_connector_cpp.dir/build.make:112: mariadbcpp/src/mariadb_connector_cpp-stamp/mariadb_connector_cpp-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1433: thirdparty/CMakeFiles/mariadb_connector_cpp.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

</details>

so i followed https://gist.github.com/simondumalski/cee72d3e6244a51f70124ac86a2802e9 but like any other guide, exept the docker guide, fails with that errorlog, so i cant continue. it says, the requested file or directory is not existing, but i didnt find any solution, how to get the files or to fix that. there is nothing on the web.

**Comment by EmosewaMC** [comment]
Follow our README and if issues occur please post them.
