### ISSUE TITLE
Forbidden Valley Wind Lift not working

### ISSUE THREAD

**Issue by HorizonFade** [DarkflameUniverse/DarkflameServer#63]
![image](https://user-images.githubusercontent.com/16822185/144931757-58f8eb1f-0451-4f3a-946d-20ae575d5d22.png)

**Comment by jelimoore** [comment]
+1. Wind in forbidden valley does not work. I just fall straight down and, ironically, there is no kill box.

**Comment by jelimoore** [comment]
Also of note, wind did work for me for a while and now it does not after I ran a git pull and rebuilt the server. I don't know if the two are related or not but it is worth noting.

**Comment by HorizonFade** [comment]
![image](https://user-images.githubusercontent.com/16822185/144952013-114ed917-043e-4a55-8779-7a7466430d5e.png)
somehow this wind thing doesnt work aswell

**Comment by MichaelFedora** [comment]
I have the same issue with both Monument wind and forbidden valley wind not working. Does it have to do with the physics server?

**Comment by averysumner** [comment]
Hearing reports that it's possibly caused by #44

**Comment by jelimoore** [comment]
Going to undo the changes from 44 manually and test, will let you know how it goes

**Comment by jelimoore** [comment]
Can confirm that undoing the changes from #44 fixes wind and other physics problems.

**Comment by HorizonFade** [comment]
So what exactly do i have to do now? 😂 Is there a fixed file that you can send?

**Comment by averysumner** [comment]
#44 has been reverted. This should work now.

**Comment by HorizonFade** [comment]
Yeah im doing it after catching some sleep, im done for now

**Comment by MichaelFedora** [comment]
Tested & that change worked!
