### ISSUE TITLE
BUG: Shooting gallery minigame sometimes not initializing

### ISSUE THREAD

**Issue by Orthestral** [DarkflameUniverse/DarkflameServer#65]
Entering the shooting gallery minigame puts the player in a falling animation at the spot they're supposed to be with nothing else happening. The exit button has to be pressed to return to Gnarled Forest.

This is similar to what happens with the Avant Gardens survival with an unmodified client

Edit:
`/skip-sg` allows you to skip the captain's quest if the hook is all you want, but the underlying issue is still there

**Comment by jelimoore** [comment]
See PR#6, you may need to copy your client side res/scripts folder to the server

**Comment by averysumner** [comment]
> See PR#6, you may need to copy your client side res/scripts folder to the server

This will not accomplish anything. @Orthestral can you provide more details, platform, compiler, etc.

**Comment by Wincent01** [comment]
This has been a known issue. If you encounter this: press the X in the top right corner, and proceed to cancel the prompt, this should initialize the minigame.

**Comment by MustacheMan2** [comment]
I haven't noticed this at all.

**Comment by EmosewaMC** [comment]
> I haven't noticed this at all.

This is because its a race condition. It'll happen seemingly randomly
