### ISSUE TITLE
BUG: Brick-By-Brick saves of sufficient size do not save completely

### ISSUE THREAD

**Issue by aronwk-aaron** [DarkflameUniverse/DarkflameServer#654]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

ec4ed8fa7e37d1a9457a17580273e3db79e4e818

### Issue Description

If a BBB is large enough, not all of it's data will be saved.
Some data is saved, but it get's cut off in the middle of the file.
The data can decompress successfully, so it's not like it only saved half of the compressed part

### Reproduction Steps

make a single model that takes a property score to over 40
save
save is corrupted and no BBB can load on that property now since one is corrupted

### Expected Behavior

Save get's saved completely

### Environment

Ubuntu 20.04, have seen it happen across multiple servers

**Comment by EmosewaMC** [comment]
The solution to this has been found.  A fix will be inbound at some point
