### ISSUE TITLE
BUG: Mail is sent warning to use rank 2 armor despite possessing some

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#669]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

40a9aef

### Issue Description

When entering Forbidden Valley, mail is sent to you recommending rank 2 armor is owned, regardless of if you have some or not.

![image](https://user-images.githubusercontent.com/48499798/180622882-2b420532-d1ba-4d2f-8fb4-8e61183b7cc9.png)

### Reproduction Steps

Wear rank 2 faction gear, enter forbidden valley

### Expected Behavior

the message should only be sent if you do not own rank 2 gear

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Not a bug.  This is just an email recommending that you equip the gear before entering Forbidden Valley.
