### ISSUE TITLE
BUG: Brick Fury's firing range is wrong

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#676]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

40a9aef

### Issue Description

This must have happened fairly recently. Now Brick Fury will shoot things from too far a distance, and essentially spawn killing the Ronin. When I first noticed it I restarted the server because it was ignoring the horsemen other than one, but afterwards it was fine but shooting too far ahead as it is now.

https://user-images.githubusercontent.com/48499798/180668065-fa53d3d2-fc7d-4ae7-9329-cdd0f4dd3ca4.mp4

### Reproduction Steps

In Forbidden Valley start leading horsemen to Brick Fury. Notice how he shoots the ronin almost as soon as they spawn.

### Expected Behavior

You should be able to lead enemies very close to Brick Fury before he shoots them

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
https://www.youtube.com/watch?v=WJcOjTDSmQU&list=PL9EFB8500E625ADC7&index=67
This is how it was in live.  Please research your issues before reporting.
