### ISSUE TITLE
ENH: add NexusDashboard to docker compose setup

### ISSUE THREAD

**Issue by DAmNRelentless** [DarkflameUniverse/DarkflameServer#698]
### Is your feature request related to a problem?

I think it would be a good idea to add the nexus dashboard setup to the darkflame server docker compose setup.
One of the main issues that arises is that the dashboard requires an unpacked client while the darkflame server requires a packed client. Also, it's a bit tedious to grant the dashboard access to the database if both are running in containers without being in the same composition. Since they share a lot of config, I think this would be great.

### Describe the solution you'd like

Add the docker setup from the NexusDashboard to the docker-compoye file on this repo for easy installation.
Could also have configs in the `.env` file as well and share some of the existing ones.

### Repository breaking implications

none

### Describe alternatives you've considered

Set up both repositories with docker and allow access to the database.

**Comment by Jettford** [comment]
These are 2 separate things and should not rely on each other.

**Comment by DAmNRelentless** [comment]
A toggle option for it in the `.env` file wouldn't be a solution for this? It could be set to `false` by default.

**Comment by EmosewaMC** [comment]
That doesnt matter. Nexus Dashboard and Darkflame Universe are two separate repositories and bundling them together like that is not a good user experience.  Feel free to make your own repository where you bundle the two together but the main repository will not be bundling them together.
