### ISSUE TITLE
BUG: Brick Fury faces the wrong way

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#704]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

f80a26a

### Issue Description

This seemed to have come up in a recent update. Brick fury simply faces the walkway away from the enemies (but still shoots normally)
![Lego Universe Screenshot 2022 08 02 - 12 08 11 25](https://user-images.githubusercontent.com/48499798/182463368-d7d6ec25-a739-451f-85bd-f31204ee43b3.png)

### Reproduction Steps

just go to brick fury

### Expected Behavior

he should be facing down the pathway where the enemies are

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Does not happen on live on a fresh build of ubuntu.
