### ISSUE TITLE
BUG: Shooting gallery targets disappear

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#705]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

d2b05a1

### Issue Description

This had to have come from one of the commits when I updated from https://github.com/DarkflameUniverse/DarkflameServer/commit/f80a26a9448c661453b353d38fe5fe8480b8ed30

When playing Cannon Cove Shooting Gallery, a large amount of the targets go backwards off screen in a couple flashes. Spawns are also a bit abnormal. Makes the mini game nearly unplayable.

### Reproduction Steps

play the shooting gallery

### Expected Behavior

shouldn't happen. Targets shouldn't disappear.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Likely an issue introduced #701 was merged.

**Comment by Jettford** [comment]
Found issue, solution in PR #711, will approach required people for reviews today.

**Comment by EmosewaMC** [comment]
Resolved in #711
