### ISSUE TITLE
BUG: Taking hits forces you out of Pirate-only swing quickbuild animation

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#706]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

d2b05a1

### Issue Description

When hit after building a pirate only quickbuild, it forces the character out of the animation of swinging, however you are still sent to the top of the cliff.

https://user-images.githubusercontent.com/48499798/182682367-5e38e816-8050-4397-a96e-20a29ef1ab48.mp4

### Reproduction Steps

go to the pirate only quickbuild in gnarled forest near the elephant escarpment where the flags are on the cliff, and with the stromling pirates aggroed, build the quickbuild.

### Expected Behavior

There is footage here https://youtu.be/fII2nP02_P0?t=958 but I am unsure if they didn't aggro over there in live or they were just distracted by the other player. Even if they did go there, my assumption is that you would get fully knocked out of the swing, or at least make the swing without being knocked out of the animation.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Known issue.  _very_ low priority.
