### ISSUE TITLE
BUG: Jumping into a property Maelstrom orb rarely works first try

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#707]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

d2b05a1

### Issue Description

When you make the jump from the quickbuild lift into the maelstrom orb on unclaimed properties, oftentimes it takes a second or third try to get it to trigger properly.

https://youtu.be/o1ePjTScGLE?t=365

### Reproduction Steps

destroy the maelstrom generator on an unclaimed property and build the lift, and make the jump into the big orb. There is a great chance it won't do anything and you'll be forced to try it again.

### Expected Behavior

touching the orb should always clear the property

### Environment

ubuntu server

**Comment by Jettford** [comment]
I think this is likely related to the physics trigger being too small in the if else chain to decide sizes.
