### ISSUE TITLE
Spider Queen

### ISSUE THREAD

**Issue by Tomifier05** [DarkflameUniverse/DarkflameServer#71]
Killed spider queen but kicked, and then mission is still there but no spider queen.

**Comment by averysumner** [comment]
Unable to reproduce.

**Comment by MasterEric** [comment]
As a workaround you can use the Nexus Force bot on the LUCH discord to lookup the mission ID, then run `/completemission [id]`

**Comment by MickVermeulen** [comment]
Can you confirm whether or not the kick happened after smashing one of the spider queen pods or the spider queen itself?

**Comment by averysumner** [comment]
Closing this issue as it is stale and no extra communication has occurred. Reopen it if you’re still encountering this on the latest commit.
