### ISSUE TITLE
BUG: Most Trigger commands and events are not implemented

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#710]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

All

### Issue Description

Players do not take damage and are unaffected by some triggers, notably the "castSkill" and "repelObject" triggers.  There may be others but I am reporting what I know on the issue

### Reproduction Steps

1) Step into a torch in Nimbus Station leading to Forbidden Valley or the maelstrom gates that spawn the horsemen.
2) Observe that the player does not take damage when they should

### Expected Behavior

The player takes damage

### Environment

All

**Comment by aronwk-aaron** [comment]
see https://docs.lu-dev.net/en/latest/file-structures/lutriggers.html for trigger info

**Comment by aronwk-aaron** [comment]
The necessary ones for Live have all been implememted
