### ISSUE TITLE
BUILD: Fatal error: Killed signal terminated program ccl

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#715]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### DarkflameServer Version

4112a85

### Platform

Ubuntu

### Architecture

x86

### Error Logs

I already have had this server running quite some time without issue, but today I was unable to load a map oddly so I restarted the server and then I couldn't load any map, and crash logs were getting made. I then pulled the latest commit and started building as usual but after staying at 0% for several minutes I get this message

[  0%] Building C object thirdparty/CMakeFiles/sqlite3.dir/SQLite/sqlite3.c.o
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[2]: *** [thirdparty/CMakeFiles/sqlite3.dir/build.make:76: thirdparty/CMakeFiles/sqlite3.dir/SQLite/sqlite3.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1370: thirdparty/CMakeFiles/sqlite3.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
[05-08-22 15:27:31] [MigrationRunner] Finished running migrations

I have not made any changes recently that could affect this, so I'm stuck.

**Comment by EmosewaMC** [comment]
The server passed ci check so that means it can build properly.  Check the configuration on your end.

**Comment by MustacheMan2** [comment]
like I said, I never changed anything and it was working before

**Comment by MustacheMan2** [comment]
Update: it only gets to 30% before giving the same error (but instead is cc1plus rather than cc1)

**Comment by EmosewaMC** [comment]
We are unable to assist with build issues when CI passes.  Feel free to get assistance in LUCH but we will not be providing build help.

**Comment by Xiphoseer** [comment]
"Killed signal terminated" is essentially someone or something pressing CTRL-C.

The only things that should be running at that stage are your terminal, make, cmake and the c/++ compilers (which seem to crash), so no code specific to DLU that could reasonably cause this.

Try to make sure you're the only person using that machine and nothing else is running. Make sure you're not out of memory (RAM). If applicable check limits that apply to your hosting provider.
