### ISSUE TITLE
Forbidden Valley Energy Gate doesn't stop players

### ISSUE THREAD

**Issue by MichaelFedora** [DarkflameUniverse/DarkflameServer#72]
...from entering without a maelstrom-infused ninja hood. May be related to #63 but I'm not sure.

**Comment by averysumner** [comment]
Pretty sure this is unrelated to #63. If I recall correctly that gate is entirely client sided… Will try to reproduce.

**Comment by HorizonFade** [comment]
eventho its unrelated to #63 i have the same problem XD

**Comment by averysumner** [comment]
Can you try again with a fresh pull+build now that #44 has been reverted?

**Comment by MichaelFedora** [comment]
@averysumner it works now. I guess it was related? Lol
