### ISSUE TITLE
BUG: Cannot Move In Avant Gardens Survival Minigame

### ISSUE THREAD

**Issue by ZoeticBanter** [DarkflameUniverse/DarkflameServer#727]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

008f953

### Issue Description

When i enter the survival minigame nothing happens, i cannot move or jump just nothing happens, with only a backrgound music

Video:

https://www.youtube.com/watch?v=U5YnQ9Ix5OQ

### Reproduction Steps

Enter in avant gardens survival minigame

### Expected Behavior

Minigame Start

### Environment

Ubuntu Server 20.04.4 LTS [Virtualbox]

**Comment by EmosewaMC** [comment]
Please make sure you have made the ag survival fix in the README.
