### ISSUE TITLE
Issues with Running and Connecting to MasterServer

### ISSUE THREAD

**Issue by d2quach** [DarkflameUniverse/DarkflameServer#73]
Hey everyone,

There will be two issues presented in this thread. I appreciate all the help I can get!

[**Running MasterServer Issues**] I have seemingly been able to install the majority of the files needed to run MasterServer. When I run ./MasterServer and or sudo ./MasterServer while my external_ip is set to "localhost", MasterServer runs fine. However, when I run ./MasterServer and or sudo ./MasterServer while my external_ip is set to my WSL IP (which is what was recommended), my MYSQL connection gets destroyed. Has anyone encountered this issue and resolved it? If so, what steps would I need to fix things? Or would it be fine to have external_ip set to localhost if I am the only one playing?

[**Connecting to MasterServer**] In the advent my MasterServer runs, my client cannot seem to connect to it. This occurs even if my boot.cfg has been edited with the same value "external_ip" is set to in all the required ".ini" files per README instructions (e.g. if external_ip=localhost, and boot.cfg is modified to have localhoost, I still cannot connect). In particular, I get hit with the "Sorry, we cannot sign you in" message on the client. How might I resolve this?

Thank you in advance.

**Comment by CitrusHappy** [comment]
#40

**Comment by MickVermeulen** [comment]
Can you confirm you still have this issue?

**Comment by d2quach** [comment]
> Can you confirm you still have this issue?

Not anymore, thank you for checking in! I figured realized that (1) I was inputting the incorrect IP into my ini files and boot.cfg file given sometimes the IP provided by "ip a" may differ from "hostname -I"; (2) I realized the WSL IP can change on occasion.
