### ISSUE TITLE
Taming a pet keeps the model floating above the head (?)

### ISSUE THREAD

**Issue by MichaelFedora** [DarkflameUniverse/DarkflameServer#74]
![image](https://user-images.githubusercontent.com/13156131/144955482-73216c76-6e4f-43d0-9f41-5660df428777.png)

Dunno if this is a normal LU bug or not.

**Comment by NealSpellman** [comment]
Normal LU bug; you can fix it by hibernating the pet and bringing it back out or changing world.

**Comment by averysumner** [comment]
Known issue, probably a won’t fix unless someone can figure it out.

**Comment by MichaelFedora** [comment]
Feel free to close then, but maybe it's good to keep on record. Thanks for the clarification!

**Comment by MickVermeulen** [comment]
Changing this from wont fix to low priority as I suspect it's definitely something that can be fixed and will be reported often.

**Comment by aronwk-aaron** [comment]
@EmosewaMC This has been fixed, right?

**Comment by Racater** [comment]
Yes, I confirm that I don't have this issue in the latest version. You can close it.
