### ISSUE TITLE
BUG: Shooting Gallery does not give model rewards

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#742]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

ceb3745

### Issue Description

The Shooting Gallery should be giving random model rewards based on how many ships you destroyed. Currently nothing happens.

### Reproduction Steps

play the shooting gallery

### Expected Behavior

https://youtu.be/xilmSHk8oq8?t=438

As you destroy targets in the shooting gallery, some will cause bricks to appear on the left hand side of the deck. When the model is completed, another one is started on. Finished models are given at the end of the round.

### Environment

ubuntu server

**Comment by aronwk-aaron** [comment]
There are realted GM's around this feature that are not implemented as well, don't have the list off the top of my head, but can get it later
