### ISSUE TITLE
BUG: Explosive Cannonballs are missing explosion animation/sound in Shooting Gallery

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#743]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

ceb3745

### Issue Description

While explosive cannonballs have a landing animation, it is either incorrect or missing a secondary animation. The landing sound is also not correct.

https://youtu.be/W0vVoz6kPts?t=299

### Reproduction Steps

play the shooting gallery and gain the explosive cannonball powerup by getting enough streaks. Hit a target.

### Expected Behavior

https://youtu.be/xilmSHk8oq8?t=442

The explosion animation is much larger and firework-like, and there is an accompanying firework sound effect.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Found the issue here.  Same fix as #220
