### ISSUE TITLE
BUILD: The make command when building the server code does not work for me. Aka I am missing the file/dir to use the MasterServer -a command

### ISSUE THREAD

**Issue by KatLight333** [DarkflameUniverse/DarkflameServer#747]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### DarkflameServer Version

ceb3745

### Platform

Ubuntu

### Architecture

x86

### Error Logs

<details>

root@dlu-server:/DarkflameServer/build# make -j6
[  0%] Performing build step for 'mariadb_connector_cpp'
[  1%] Built target tinyxml2
[  3%] Built target Detour
[  4%] Built target bcrypt
[  6%] Built target Recast
[  6%] Built target sqlite3
make[3]: warning: -j1 forced in submake: resetting jobserver mode.
[  7%] Built target dZoneManager
[  6%] Built target DetourTileCache
[  8%] Built target DetourCrowd
[  9%] Built target bcrypt_test
[ 21%] Built target raknet
[ 22%] Built target DebugUtils
[ 25%] Built target dCommon
[ 26%] Built target dNavigation
[ 27%] Built target dPhysics
[ 24%] Built target mariadb_obj
[ 24%] Built target libmariadb
[ 26%] Built target dialog
[ 27%] Built target mysql_clear_password
[ 29%] Built target sha256_password
[ 30%] Building C object libmariadb/CMakeFiles/caching_sha2_password.dir/libmariadb/secure/openssl_crypt.c.o
In file included from /DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/libmariadb/secure/openssl_crypt.c:20:
/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:74:1: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   74 | MA_HASH_CTX *ma_hash_new(unsigned int algorithm, MA_HASH_CTX *ctx);
      | ^~~~~~~~~~~
      | MA_HASH_MD5
/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:74:50: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   74 | MA_HASH_CTX *ma_hash_new(unsigned int algorithm, MA_HASH_CTX *ctx);
      |                                                  ^~~~~~~~~~~
      |                                                  MA_HASH_MD5
/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:83:19: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   83 | void ma_hash_free(MA_HASH_CTX *ctx);
      |                   ^~~~~~~~~~~
      |                   MA_HASH_MD5
/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:96:20: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
   96 | void ma_hash_input(MA_HASH_CTX *ctx,
      |                    ^~~~~~~~~~~
      |                    MA_HASH_MD5
/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:108:21: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
  108 | void ma_hash_result(MA_HASH_CTX *ctx, unsigned char *digest);
      |                     ^~~~~~~~~~~
      |                     MA_HASH_MD5
/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h: In function ‘ma_hash’:
/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:155:3: error: unknown type name ‘MA_HASH_CTX’; did you mean ‘MA_HASH_MD5’?
  155 |   MA_HASH_CTX *ctx= NULL;
      |   ^~~~~~~~~~~
      |   MA_HASH_MD5
/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/libmariadb/secure/openssl_crypt.c: At top level:
/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/libmariadb/secure/openssl_crypt.c:21:10: fatal error: openssl/evp.h: No such file or directory
   21 | #include <openssl/evp.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [libmariadb/CMakeFiles/caching_sha2_password.dir/build.make:76: libmariadb/CMakeFiles/caching_sha2_password.dir/libmariadb/secure/openssl_crypt.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:311: libmariadb/CMakeFiles/caching_sha2_password.dir/all] Error 2
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [thirdparty/CMakeFiles/mariadb_connector_cpp.dir/build.make:112: mariadbcpp/src/mariadb_connector_cpp-stamp/mariadb_connector_cpp-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1566: thirdparty/CMakeFiles/mariadb_connector_cpp.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

</details>

**Comment by EmosewaMC** [comment]
Please ensure you have followed the README for updating your server.

**Comment by KatLight333** [comment]
> Please ensure you have followed the README for updating your server.

that was not the problem. I fixxed it by using the following:

sudo apt-get install libssl-dev zlib1g zlib1g-dev

cd DarkflameServer/build

make clean

cd ..

git reset --hard

./build.sh
