### ISSUE TITLE
Login screen doesn't load

### ISSUE THREAD

**Issue by jacobhilliker** [DarkflameUniverse/DarkflameServer#75]
Hello,

I haven't seen this issue mentioned anywhere else so I figured I'd bring it to your attention.

The first thing I haven't seen mentioned anywhere else is that I had to change the name of two of my client DLLs:
 - awesomium.dll -> Awesomium.dll
 - cop.dll -> COP.dll
to get the client to run.

My issue is that when I have my server set up and running, I open the client .exe and I see the minifig running icon immediately followed by an endless white screen. My cursor correctly changes to the orange LU cursor but the login screen never loads.

Did I break something by renaming the DLLs (there were error messages telling me those DLLs were missing until I renamed them), or is there something else at work here?

**Comment by NealSpellman** [comment]
This is not a server issue, this is a client issue. I suggest grabbing a different client or looking through the current client's log file to see if there's any information on what went wrong.

**Comment by jacobhilliker** [comment]
Thanks for the quick response! If I might ask a quick follow-up, where can I find the client log files? I'm not seeing a logs directory or anything of the sort in mine. It's an unpacked client and I extracted it using 7Zip

**Comment by NealSpellman** [comment]
> Thanks for the quick response! If I might ask a quick follow-up, where can I find the client log files? I'm not seeing a logs directory or anything of the sort in mine. It's an unpacked client and I extracted it using 7Zip

Should be somewhere like `...\AppData\Local\LEGO Software\LEGO Universe\Log Files`

**Comment by jacobhilliker** [comment]
Thanks! I opened it up and it looks like the issue is that my downloaded client translated all the resource file names to strictly lowercase somehow, so it can't find any assets with a capitalized letter in the name. Weird.
