### ISSUE TITLE
BUG: Possible Missing Quickbuild for Large Refinery Pipe in Forbidden Valley

### ISSUE THREAD

**Issue by slavicphilosofr** [DarkflameUniverse/DarkflameServer#757]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

3b75ecc

### Issue Description

I am not sure if this is a bug, as I did not play this portion of the original version of the game, but this seems like a bug to me.

One of the missions at the Paradox Refinery in Forbidden Valley is "The System Is Down". The mission requires one to repair three large refinery pipes (not referring to the pipe piles that you smash and rebuild into the consoles at the refinery) and have all three remain intact at the same time. On the ledge next to the refinery with the lone Maelstrom Horseman, there are two quickbuilds, each of which repairs a different broken refinery pipe (attached images 1 and 2 below). On the ledge is also what appears to be a third broken refinery pipe (attached images 3 and 4 below), but there is no quickbuild(s) to repair this broken pipe.

Should there be a quickbuild(s) to repair this third broken pipe? I cannot find any such quickbuilds in the vicinity of the area in the game.

![Broken Pipe 1](https://user-images.githubusercontent.com/44324434/187319566-ee2e2655-6ae0-4ddc-8f86-5fc47058c80e.png)
![Broken Pipe 2](https://user-images.githubusercontent.com/44324434/187319567-7f90556e-2115-40d0-ac1d-c5fee28c9f72.png)
![Broken Pipe 3 - From Above](https://user-images.githubusercontent.com/44324434/187319569-64e2facc-2564-465d-9180-6da6fb1c0c72.png)
![Broken Pipe 3 - From Below](https://user-images.githubusercontent.com/44324434/187319571-e07b6bde-99ed-423f-9c84-7ce454e4bb7b.png)
![Two Quickbuilds](https://user-images.githubusercontent.com/44324434/187319578-480c4055-2a67-49d1-8575-273b4b2d7909.png)
![No Third Quickbuild - 1](https://user-images.githubusercontent.com/44324434/187319592-ab2fb8d5-b5dc-41c2-899a-82e31abeec2c.png)
![No Third Quickbuild - 2](https://user-images.githubusercontent.com/44324434/187319593-4ee7442e-b0b8-444f-9aae-6990621bd12c.png)

### Reproduction Steps

Go to the Paradox Refinery in Forbidden Valley.
Go to the ledge next to the refinery with the lone Maelstrom Horseman.
Observer that there are two quickbuilds that each repair a different broken refinery pipe.
Observe the third broken refinery pipe, for which there is no quickbuild(s) to repair the broken pipe.

As a supplement, accept the mission "The System Is Down" and observe that it requires one to repair three refinery pipes, yet only two refinery pipes can be repaired.

### Expected Behavior

Again, I do not know if this is actually a bug, as I did not play this portion of the original version of the game, but this seems like a bug to me.

I would expect there to be a quickbuild(s) to repair a third refinery pipe, and I would expect this pipe to be the broken pipe shown in attached images 3 and 4 above.

### Environment

Windows 11 Home, version 21H2, x64.

**Comment by MustacheMan2** [comment]
There is a third quickbuild concealed in a rock smashable on the ledge by the other horsemen with the binoculars. Therefore, this is a skill issue.

**Comment by EmosewaMC** [comment]
This is not an issue on our end.  Please look around to complete the mission

**Comment by kevin-wise** [comment]
> There is a third quickbuild concealed in a rock smashable on the ledge by the other horsemen with the binoculars

Note the quickbuild is not hidden inside the rock, but it is activated by smashing the rock. You have to look around to find it.
