### ISSUE TITLE
BUG: Weird Object Above Assembly Vendor's Booth in Nimbus Station

### ISSUE THREAD

**Issue by slavicphilosofr** [DarkflameUniverse/DarkflameServer#758]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

3b75ecc

### Issue Description

In Nimbus Station, there is a weird object above the Assembly vendor's booth. This object persists regardless of one's distance to the booth. Additionally, the rotating Assembly logo that should appear above the booth when one is at sufficient distances away from the booth does not appear at those distances.

I have not observed any similar abnormalities with the three other faction booths in Nimbus Station.
![LEGO Universe - 1 10 64 2022-08-29 19_35_23](https://user-images.githubusercontent.com/44324434/187324014-36e498d0-15d3-4d66-a0cb-542967fea393.png)
![LEGO Universe - 1 10 64 2022-08-29 19_35_45](https://user-images.githubusercontent.com/44324434/187324021-913c43a6-1053-466d-ad5f-0524161102a4.png)
![LEGO Universe - 1 10 64 2022-08-29 19_36_33](https://user-images.githubusercontent.com/44324434/187324025-5a242be2-967f-49ba-8064-f1d279a6514d.png)
![LEGO Universe - 1 10 64 2022-08-29 19_36_40](https://user-images.githubusercontent.com/44324434/187324028-9b2861f9-3fca-468b-bd16-1f40601240e9.png)
![LEGO Universe - 1 10 64 2022-08-29 19_40_40](https://user-images.githubusercontent.com/44324434/187324031-1c6a5ba0-1128-4a9a-b6a1-54ee67842483.png)
![LEGO Universe - 1 10 64 2022-08-29 19_41_00](https://user-images.githubusercontent.com/44324434/187324035-949721eb-8408-4e29-a23e-8074c3601ee0.png)
![LEGO Universe - 1 10 64 2022-08-29 19_41_27](https://user-images.githubusercontent.com/44324434/187324038-c9b1576a-4cfb-44fc-8e7f-a422c7039af5.png)
![LEGO Universe - 1 10 64 2022-08-29 19_41_44](https://user-images.githubusercontent.com/44324434/187324042-b734ecf9-3963-4100-879a-22fbd4215c8a.png)
![LEGO Universe - 1 10 64 2022-08-29 19_41_55](https://user-images.githubusercontent.com/44324434/187324045-9609bb58-d5bb-4fe1-830c-c2a17cae05da.png)

### Reproduction Steps

Go to Nimbus Station.
Find and observe the Assembly vendor's booth.

### Expected Behavior

The weird object should not be present above the Assembly vendor's booth. Additionally, when one is at sufficient distances away from the booth, there should be a rotating Assembly logo.

### Environment

Windows 11 Home, version 21H2, x64.

**Comment by EmosewaMC** [comment]
Not an issue on our end.  This is a client issue from being GM level 9.
