### ISSUE TITLE
BUG: Sentinel camp bus gate raises/lowers at the wrong times in Avant Gardens

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#762]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

500b788

### Issue Description

The bus gate currently works very strangely. It rises from a distance, it lowers in front of you. It stays put. You can never tell how it will act. 

https://youtu.be/D8wfnDf9uqA?t=409
https://youtu.be/z8PlB4DxewM?t=351

### Reproduction Steps

approach the bus door at the sentinel camp in avant gardens

### Expected Behavior

the door should simply rise when players come near it and lower when they are not

### Environment

ubuntu server

**Comment by DarwinAnim8or** [comment]
Er, yeah there's some weirdness in that script it seems. There's a counter for the amount of people in it, but then it immediately sets it to 0 on each entry? Likely what's causing the bus to behave erratically.

**Comment by MustacheMan2** [comment]
Resolved with #797
