### ISSUE TITLE
BUG: Vehicle crashes have no respawn delay

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#763]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

500b788

### Issue Description

When crashing your car in a race, there should be a respawn delay (likely for balancing reasons), but currently you just respawn instantly.

### Reproduction Steps

crash into a wall in a race

### Expected Behavior

https://youtu.be/xGgYKHmgMk0?t=463

there is about a 2 second delay between crashing and respawning

### Environment

ubuntu server

**Comment by MustacheMan2** [comment]
This seems to have resolved itself somehow.

**Comment by EmosewaMC** [comment]
oh i didnt know this was an issue.  I fixed this a while ago.
