### ISSUE TITLE
Avant Gardens WorldServer pins core CPU at 100%

### ISSUE THREAD

**Issue by jelimoore** [DarkflameUniverse/DarkflameServer#77]
Expected Behavior
The Avant Gardens world server consumes a reasonable amount of CPU like the other world servers (ranges from 10 to 30%)

Current Behavior
After about an hour of uptime, the Avant Gardens worldserver pins the single core it is using at 100%. There doesn't seem to be too much world lag, and the /metrics command shows times to be relatively in-line with what I would expect. 

Possible Solution
Could be related to physics - unsure. I do not have time to dig into the codebase right now.

Steps to Reproduce
1. Clone and build
2. Copy resources into res/
3. Run MasterServer and monitor resource utilization via `top`

Your Environment
Ubuntu 20.04 LTS, 4CPU, 4GB RAM

**Comment by averysumner** [comment]
I doubt it’s related to physics, our physics engine is entirely custom and rather barebones. Is this jump in usage in relation to VE’s usage? VE is a very simple world compared to AG. Our server is also highly single threaded and may pin lower end CPUs.

**Comment by jelimoore** [comment]
Sorry it's been years since I've played the game - excuse my ignorance but you'll have to expand what VE is.

I've got 4x Xeon somethings carved out for the sever in VMware, they're E5-26xx v2s with 2.8ghz base so no slouch. Avant Gardens is the only worldserver pinning the CPU - all other world servers are sitting normally:

![image](https://user-images.githubusercontent.com/6201669/144961628-e095eab7-7844-48a7-864f-48c09f61b835.png)

**Comment by averysumner** [comment]
> Sorry it's been years since I've played the game - excuse my ignorance but you'll have to expand what VE is.
VE - Venture Explorer
AG - Avant Gardens

Hmmm.... that's odd. Are there significantly more clients connected to the AG instance than any others?

**Comment by jelimoore** [comment]
Not really - as of right now:
1100 - 100% and 7 people
1300 - 9% and 1 person
2000 - 12% and 8 people

**Comment by averysumner** [comment]
Are you still having this issue?

**Comment by jelimoore** [comment]
Yes, but I am only on commit ca287db536f47a0a3d3eab5ddea122aede2e81c2 - I have scheduled downtime for tomorrow and will update if it fixes the CPU usage or not

**Comment by jelimoore** [comment]
Still occurs as of latest commit

**Comment by jelimoore** [comment]
It looks like this is at least partially fixed by either the latest commit or moving my server VM to a higher power host. I'll close for now.
