### ISSUE TITLE
BUG: team and friend invites do not work in Docker

### ISSUE THREAD

**Issue by DAmNRelentless** [DarkflameUniverse/DarkflameServer#772]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

63af2c8

### Issue Description

Same issue like here: https://github.com/DarkflameUniverse/DarkflameServer/issues/399#issuecomment-1030998040

I am using the docker installation and I am on Debian. When accessing the darkflame server container and opening the `worldconfig.ini`, the `chat_server_port` has no value behind it. The `chatconfig.ini` has the port assigned just fine.

The chat in the game works, trading works too but no one of us is getting a notification on friend and team invites. The only thing I did was adding Nexus Dashboard to the docker compose setup.

### Reproduction Steps

- setup the server via docker
- join the game with a few people
- try to invite as friend or in a team
- see that no popup appears

### Expected Behavior

A popup should appear to accept or deny the request.

### Environment

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**Comment by EmosewaMC** [comment]
I advise switching to a Windows or wsl setup as docker is not being maintained or updated at the moment.
