### ISSUE TITLE
BUG: Windows build broken in latest commit 

### ISSUE THREAD

**Issue by HailStorm32** [DarkflameUniverse/DarkflameServer#773]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

63af2c8

### Issue Description

Running MasterServer will cause it to complain about not finding the zlib.dll

![unknown](https://user-images.githubusercontent.com/5051025/189548934-6f70445c-a786-49ca-b157-040067f2106b.png)

### Reproduction Steps

Build commit 63af2c8 on native windows, then run MasterServer

### Expected Behavior

Should run without errors

### Environment

Windows 11, native

**Comment by EmosewaMC** [comment]
Move zlib.dll to the parent directory.

**Comment by luxaritas** [comment]
Can this be closed now?

**Comment by HailStorm32** [comment]
Haven't checked since the mentioned PR was merged. Willl check tomorrow evening
