### ISSUE TITLE
BUG: Samurai Target Dummy Vanishing Bug

### ISSUE THREAD

**Issue by LU-MMChamp** [DarkflameUniverse/DarkflameServer#774]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [x] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

63af2c8

### Issue Description

When a Samurai using their Valiant Weapon spawns a Target Dummy, often times, the target dummy will quickly vanish, but keep enemies taunted. When enemies are taunted by the dummy in this way, they will not attack the dummy, but rather just stare at it, or where it was in the case when it vanishes.

### Reproduction Steps

Spawn a target dummy using the Samurai valiant weapon around Maelstrom enemies. Do so in a place where the enemies cannot attack the dummy until the dummy does its first taunt.

### Expected Behavior

The dummy should last until the Create Target Dummy power up's cool down time is almost finished or until the dummy is destroyed. Enemies should attack the dummy and the dummy should taunt periodically throughout its duration.

### Environment

Ubuntu using a Windows computer

**Comment by EmosewaMC** [comment]
This should be resolved - Can you confirm if it is on main?

**Comment by EmosewaMC** [comment]
This should be resolved on main
