### ISSUE TITLE
BUG: Enemies cannot be knocked back

### ISSUE THREAD

**Issue by LU-MMChamp** [DarkflameUniverse/DarkflameServer#775]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

63af2c8

### Issue Description

Enemies cannot be knocked back, though players can whether by Maelstrom enemies or with PvP enabled.

### Reproduction Steps

Use any ability (for instance, a flash bang) on an enemy that isn't immune to it. The enemy will just play an animation and will be stunned for a short time rather than being knocked back.

### Expected Behavior

Enemies should be displaced rather than just being stunned in one place. Certain abilities and flash bangs are greatly lessened in their fun and effectiveness from this bug.

### Environment

Ubuntu on Windows

**Comment by EmosewaMC** [comment]
Same issue as #257.
