### ISSUE TITLE
Game crashes at launch

### ISSUE THREAD

**Issue by Cars0419** [DarkflameUniverse/DarkflameServer#78]
As soon as I launch the main game, the picture of the mini-figure running comes up but then immediately disappears, Everything appears to be configured correctly, so I am not sure what the issue might be

![Annotation 2021-12-06 221145](https://user-images.githubusercontent.com/95667322/144959524-e1575596-f4bc-44e6-a876-be02aee0caff.png)
.

**Comment by averysumner** [comment]
This is a client issue, not an issue with DarkflameServer.
