### ISSUE TITLE
BUILD: The CXX compiler identification is unknown

### ISSUE THREAD

**Issue by Phantom213** [DarkflameUniverse/DarkflameServer#785]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### DarkflameServer Version

f02e9c0

### Platform

Ubuntu

### Architecture

x86

### Error Logs

<details>

-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/root/lu/DarkflameServer/build/CMakeFiles/CMakeOutput.log".
See also "/root/lu/DarkflameServer/build/CMakeFiles/CMakeError.log".
gmake: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.  Schluss.
./build.sh: Zeile 12: ./MasterServer: Datei oder Verzeichnis nicht gefunden

</details>

**Comment by EmosewaMC** [comment]
You'll need to install a c++ compiler and clear cache to allow cmake to try to find the compiler.
