### ISSUE TITLE
"Discovery" related achievements are flakey and end up broken unexpectedly

### ISSUE THREAD

**Issue by Lego6245** [DarkflameUniverse/DarkflameServer#79]
Achievements like Nimbus Station's and Pet Cove's discovery of locations, or Advent Garden's Orange Path appear to not work, while other discoveries like Green/Yellow path and the rest of the Advent Garden achievements do. Not sure how to best debug this.

**Comment by jelimoore** [comment]
Try adding scripts to your res folder, see PR #76

**Comment by Lego6245** [comment]
That did not appear to fix the issue. None of the Nimbus Station discovery achievements popped for me after adding the scripts folder from my unpacked client to the server and rebooting it.

**Comment by averysumner** [comment]
This is likely a result of the physics engine being finicky, you don't need these scripts.

**Comment by Lego6245** [comment]
Good to know. I figured as much as I know that the dScripts folder has all the (translated) scripts from a different issue.

**Comment by Lego6245** [comment]
I can confirm that as of the revert of #44 in #85, discovery related achievements work again, at least for now. Will close this issue unless I see it again. Thank you!
