### ISSUE TITLE
BUG: Locale is not extracted from a packed client

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#807]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

All

### Issue Description

The locale should be extracted from the packed client.

### Reproduction Steps

The locale is not extracted and does not exist if the server is setup using an unpacked client.

### Expected Behavior

Locale.xml exists somewhere when using a packed client and all references to it are updated for unpacked clients as well.

Ideally we just use the one in `res/local.xml` for unpacked clients and extract `locale.xml` for packed clients.

### Environment

All

**Comment by Jettford** [comment]
I know it is getting removed but
> Ideally we just use the one in res/local.xml for unpacked clients and extract locale.xml for packed clients.

The locale file is always in the client root in a folder called locale, it is never packed and never in res

**Comment by EmosewaMC** [comment]
Idk what I was on last night lol.  This is closed anyways since we're removing it
