### ISSUE TITLE
Lucky Shovel does not work

### ISSUE THREAD

**Issue by Jodobofire** [DarkflameUniverse/DarkflameServer#86]
When I try to dig up some chests, it just does not work...
My chracter digs, but the ches wont come up...

The log says:
[07-12-21 09:28:46] [Item]: Consumed (14591) / (1152921510356233322) with (0)
[07-12-21 09:28:51] [Item]: Used (14591) with (0)

**Comment by MickVermeulen** [comment]
Are you trying to dig on a property? If I recall correctly it does not work on non-properties.

**Comment by Jodobofire** [comment]
It tried to dig on several places.. expect my own property...
Soo the chest dig out, just does not work?

**Comment by MickVermeulen** [comment]
Did you try it on other people's properties? It does not work on your own property or on non-property worlds.

**Comment by Jodobofire** [comment]
I'm just stupid!

**Comment by Jodobofire** [comment]
On peoples properties it works ...
