### ISSUE TITLE
Issues while running on webserver

### ISSUE THREAD

**Issue by MajickTek** [DarkflameUniverse/DarkflameServer#9]
Information:
Status: I have built DLU and am running it. Ive opened all ports I saw in the config files as tcp and udp.

Server: a VPS running on Linode (Ubuntu 20.04).

First of all i get this error even though those referenced files do exist, just in lowercase.

`[05-12-21 16:44:51] [CppScripts]: Attempted to load CppScript for 'scripts\ai\AG\L_AG_SHIP_SHAKE.lua', but returned InvalidScript.`

Full log: https://pastebin.com/J7jimWHp (actual logs dont exist because of permission issues even though i set those properly).

when I try to connect to the server using my admin account, the client immediately crashes.

**Comment by MajickTek** [comment]
I fixed the log issue but the crashing issue still persists

**Comment by Jettford** [comment]
You can fix your logs "permissions" issues just by creating a logs folder, the server doesn't create it itself

Just run 
```
mkdir logs
```

and as for the script, this is just a non implemented script that afaik works without it.

**Comment by j-usti-n** [comment]
@MajickTek are you getting "Disconnected From World" client crash?

**Comment by MajickTek** [comment]
The client no longer crashes, i reconfigured the server to work with the correct client version and its fine now

Also since the missing script seems to be a non issue this issue can be closed

**Comment by kevin-wise** [comment]
I also see the invalid script error, on Windows

**Comment by MajickTek** [comment]
I meant to actually close this, feel free to re-open if necesary
