### ISSUE TITLE
Possible to rename & change password?

### ISSUE THREAD

**Issue by Stanlyhalo** [DarkflameUniverse/DarkflameServer#902]
Hey, is it possible to change the login username & password of an account rather than adding a new one via `MasterServer.exe -a`? Also, it says my minifig name was sent to some server for review, is that auto accepted, because it seems to be fine in-game n in-menu.

**Comment by MustacheMan2** [comment]
The username can be changed in the `accounts` table, the password theoretically can be changed there too but it's hashed. Minifig names can be approved if 1. The name is found in the chat whitelist 2. it's changed in the `charinfo` table, and the `pending_name` column set to ''. Pet names also check the chat whitelist, and can be accepted by changing the value of the `approved` column to 2 in `pet_names`. However, Nexus Dashboard does all of these things and significantly easier, although changing account information requires additional setup. TL:DR, get Nexus Dashboard [https://github.com/DarkflameUniverse/NexusDashboard](url)

**Comment by Stanlyhalo** [comment]
Where is the accounts table, I can't find it in the `CDServer.sqlite`. Also I'm having issues with the nexus dashboard and I already have an issue post there, so momentarily I'm trying to figure it out here.

**Comment by MustacheMan2** [comment]
it's in whatever you named the database when you set up the server, the CDServer is irrelevant.

**Comment by Stanlyhalo** [comment]
Ah thanks for the help, I'll continue to see if I can get the Nexus Dashboard to work.
