### ISSUE TITLE
BUG: Friend can't join on same WIFI.

### ISSUE THREAD

**Issue by Stanlyhalo** [DarkflameUniverse/DarkflameServer#903]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

latest

### Issue Description

My friend tries to login, and it seems to work, but I get this error in my console: `Got new session alert for user test2, but they're not logged in.`. And if they put in the wrong password, it seems to recognize it's incorrect, but everytime they try to login it just goes back and does the intro animation and asks them to login (intro animation as in it moving stuff to make the login screen).

### Reproduction Steps

Change the boot.cfg in the friend's version to your ip.
Have your friend join.

### Expected Behavior

Friend logins and is able to create a minifig.

### Environment

I replaced the localhost in the boot.cfg with my IP, and they are on the same WIFI, it seems to recognize them joining, but says they're not logged in, their account is made via the account manager repo.

**Comment by Stanlyhalo** [comment]
It seems to say the same message for me, but it lets me in.

**Comment by Stanlyhalo** [comment]
For me, in the WorldServer.exe, it shows 5 lines, the first being getting the transfer, second stating it's me but not logged in, third saying client received, fourth saying I'm authenticated with the correct key, and lastly it loads the xml data, for my friend, it just shows the first two and nothing else.

**Comment by EmosewaMC** [comment]
ensure your external ip is correct.  Many other servers do not report this issue.
