### ISSUE TITLE
BUG: LEGO Club floating rings don't break sometimes

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#906]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

f2fa81b

### Issue Description

Sometimes when jumping through the floating rings in LEGO Club, one or two do not break.

### Reproduction Steps

Jump through the floating rings in LEGO Club.

### Expected Behavior

All rings should break when the player goes through or lands on them.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Physics issue.  highly likely a wont fix

**Comment by EmosewaMC** [comment]
Same resolution and bug as #734
