### ISSUE TITLE
Mailbox Not working

### ISSUE THREAD

**Issue by ZackTheGuy** [DarkflameUniverse/DarkflameServer#94]
When I load into Advent Gardens I get this error message in the server console
"Attempted to load Cppscript for 'scripts\02_server\Map\General\L_MAIL_BOX_SERVER.lua' but returned InvalidScript

**Comment by averysumner** [comment]
Does the mailbox actually not work as intended or is it just that this script doesn’t load?

**Comment by ZackTheGuy** [comment]
It does not work as intended

**Comment by averysumner** [comment]
What is the problem and can you provide more information in compliance with CONTRIBUTING.md?

**Comment by ZackTheGuy** [comment]
When I try to use a mailbox. I want to compose a message to my friends. I try to put in a subject but when I do the mail icon goes red. I think its linked to issue #61 as I have that problem as well.

Running on a WLS Ubuntu

**Comment by averysumner** [comment]
Fairly sure this is the same issue as #61, wait until #91 goes through and see if that fixes it.

**Comment by averysumner** [comment]
#91 has been merged. Does the issue persist?

**Comment by BustosAndrew** [comment]
#118 still having the same issue. @averysumner

**Comment by Mar0xy** [comment]
I also can't compose messages it just turns red and I have the filter/chatplus fix applied.

**Comment by ZackTheGuy** [comment]
After reseting the server and rebuilding it with the new merge. The mailbox now works. Closing this issue.
