### ISSUE TITLE
Solution for client side bug "NIF MISSING" for Assembly Signage

### ISSUE THREAD

**Issue by MichaelFedora** [DarkflameUniverse/DarkflameServer#95]
I don't know where to put this, but maybe you could fit it the client modding guide, but optional?

Replace the `9` with a `(`, and the `Z:lwo\4_game\client\res` with `.\.,\..`. Resulting file should look like this:

![image](https://user-images.githubusercontent.com/13156131/145079179-2f93e4eb-cc00-48a4-9547-48e20d5857d4.png)

Alternatively, take the `sentinel_sign_anim_sm.kfm` and replace `Sentinel` with `Assembly`.

**Comment by averysumner** [comment]
Unrelated to DarkflameServer codebase. Closing issue.
