### ISSUE TITLE
BUILD: unknown type name 'MA_HASH_CTX' on MacOS

### ISSUE THREAD

**Issue by hbdcaulfield** [DarkflameUniverse/DarkflameServer#955]
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### DarkflameServer Version

8722707

### Platform

macOS

### Architecture

ARM

### Error Logs

Hi there. I was trying to setup the Darkflame on my system but I keep running into a number of errors that start with "error: unknown type name 'MA_HASH_CTX'". This happens at about 22% after running ./build.sh

<details>

-- Variable: PROJECT_VERSION_MAJOR = 1
-- Variable: PROJECT_VERSION_MINOR = 0
-- Variable: PROJECT_VERSION_PATCH = 4
-- Variable: LICENSE = AGPL-3.0
-- Variable: NET_VERSION = 171022
-- Variable: __dynamic = 1
-- Variable: __maria_db_connector_compile_jobs__ = 1
-- Variable: __enable_testing__ = 1
-- Variable: OPENSSL_ROOT_DIR = /usr/local/opt/homebrew/Cellar/openssl@3
-- Version: 1.0.4
-- Testing is enabled.  Fetching gtest...
-- gtest fetched and is now ready.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ditarando/Documents/LegoUniverse/DarkflameServer/build
[  1%] Built target bcrypt
[  2%] Performing configure step for 'mariadb_connector_cpp'
-- Found math lib: m
-- MariaDB Connector ODBC: INSTALL_BINDIR=bin
-- MariaDB Connector ODBC: INSTALL_LIBDIR=/mariadb
-- MariaDB Connector ODBC: INSTALL_PCDIR=/pkgconfig
-- MariaDB Connector ODBC: INSTALL_INCLUDEDIR=include/mariadb
-- MariaDB Connector ODBC: INSTALL_DOCDIR=share/doc/
-- MariaDB Connector ODBC: INSTALL_LICENSEDIR=share/doc/
-- MariaDB Connector ODBC: INSTALL_PLUGINDIR=plugin
-- Libraries installation dir: 
-- Authentication Plugins installation dir: plugin
-- Setting default value for WITH_SSL for libmariadb build to ON
-- Running C/C cmake scripts
== Configuring MariaDB Connector/C
-- MariaDB Connector C: INSTALL_LIBDIR=/mariadb
-- MariaDB Connector C: INSTALL_PCDIR=/pkgconfig
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
-- OpenSSL/LibreSSL not found
-- TLS library/version: 
-- Dynamic column API support: ON
-- MariaDB Connector/c configuration:
-- Static PLUGINS mysql_native_password;mysql_old_password;pvio_socket
-- Dynamic PLUGINS dialog;client_ed25519;caching_sha2_password;sha256_password;auth_gssapi_client;mysql_clear_password
-- CPack generation: TGZ
-- SSL support: OPENSSL Libs: 
-- Zlib support: ON
-- Installation layout: DEFAULT
-- Include files will be installed in include/mariadb
-- Libraries will be installed in /mariadb
-- Binaries will be installed in bin
-- Documentation included from 
-- Required: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/lib/libz.tbd
-- Configuring to install libmariadb to /mariadb
-- Configuring to install mysql_clear_password to plugin
-- Configuring to install dialog to plugin
-- Configuring to install client_ed25519 to plugin
-- Configuring to install sha256_password to plugin
-- Configuring to install caching_sha2_password to plugin
-- Linking Connector/C library dynamically(libmariadb)
-- Documentation installed to share/doc/
-- License file installed to share/doc/
-- Public API header files installed to include/mariadb
-- Package Name: mariadb-connector-cpp-1.0.2-src
-- License File: /Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/COPYING
-- ReadMe File: /Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/README
-- Source Package Filename: mariadb-connector-cpp-1.0.2-src.TGZ
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ditarando/Documents/LegoUniverse/DarkflameServer/build/mariadbcpp/src/mariadb_connector_cpp-build
[  2%] Performing build step for 'mariadb_connector_cpp'
[  1%] Building C object libmariadb/libmariadb/CMakeFiles/mariadb_obj.dir/mariadb_dyncol.c.o
[ 18%] Built target mariadb_obj
[ 18%] Linking C shared library libmariadb.dylib
[ 18%] Built target libmariadb
[ 19%] Built target mysql_clear_password
[ 22%] Built target dialog
[ 22%] Building C object libmariadb/CMakeFiles/client_ed25519.dir/plugins/auth/ref10/open.c.o
In file included from /Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/plugins/auth/ref10/open.c:3:
In file included from /Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/plugins/auth/ref10/crypto_hash_sha512.h:2:
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:74:1: error: unknown type name 'MA_HASH_CTX'
MA_HASH_CTX *ma_hash_new(unsigned int algorithm, MA_HASH_CTX *ctx);
^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:74:50: error: unknown type name 'MA_HASH_CTX'
MA_HASH_CTX *ma_hash_new(unsigned int algorithm, MA_HASH_CTX *ctx);
                                                 ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:83:19: error: unknown type name 'MA_HASH_CTX'
void ma_hash_free(MA_HASH_CTX *ctx);
                  ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:96:20: error: unknown type name 'MA_HASH_CTX'
void ma_hash_input(MA_HASH_CTX *ctx,
                   ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:108:21: error: unknown type name 'MA_HASH_CTX'
void ma_hash_result(MA_HASH_CTX *ctx, unsigned char *digest);
                    ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:155:3: error: use of undeclared identifier 'MA_HASH_CTX'
  MA_HASH_CTX *ctx= NULL;
  ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:155:16: error: use of undeclared identifier 'ctx'
  MA_HASH_CTX *ctx= NULL;
               ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:160:3: error: use of undeclared identifier 'ctx'
  ctx= ma_hash_new(algorithm, ctx);
  ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:160:31: error: use of undeclared identifier 'ctx'
  ctx= ma_hash_new(algorithm, ctx);
                              ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:161:17: error: use of undeclared identifier 'ctx'
  ma_hash_input(ctx, buffer, buffer_length);
                ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:162:18: error: use of undeclared identifier 'ctx'
  ma_hash_result(ctx, digest);
                 ^
/Users/ditarando/Documents/LegoUniverse/DarkflameServer/thirdparty/mariadb-connector-cpp/libmariadb/include/ma_crypt.h:163:16: error: use of undeclared identifier 'ctx'
  ma_hash_free(ctx);
               ^
12 errors generated.
make[5]: *** [libmariadb/CMakeFiles/client_ed25519.dir/plugins/auth/ref10/open.c.o] Error 1
make[4]: *** [libmariadb/CMakeFiles/client_ed25519.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [mariadbcpp/src/mariadb_connector_cpp-stamp/mariadb_connector_cpp-build] Error 2
make[1]: *** [thirdparty/CMakeFiles/mariadb_connector_cpp.dir/all] Error 2
make: *** [all] Error 2

</details>

**Comment by EmosewaMC** [comment]
Follow the README again and delete the CMakeCache.txt.

**Comment by hbdcaulfield** [comment]
This did not resolve the issue. CMakeCache.txt gets recreated when ./build.sh is run. The README does not mention this error and I followed it to a T

**Comment by EmosewaMC** [comment]
Ensure that openssl has been installed properly at the destination directory.  Then just do a git reset --hard HEAD and remove the build folder entirely.

**Comment by EmosewaMC** [comment]
You can also observe in your log files that mariadb did not find openssl in the default directory. This does not happen on a proper configuration
