### ISSUE TITLE
Stromling pirates glitching through walls, up hills and up stairs

### ISSUE THREAD

**Issue by leolion3** [DarkflameUniverse/DarkflameServer#96]
The stromling pirates (the normal and the captain ones) are glitching through everything starting with the walls at the stromling trench, up the stones to the guy/girl with the quest on top of the trench and up the stairs and platforms and through the pillars further on in gnarled forest.

**Comment by averysumner** [comment]
Do you have a navmesh in res/maps/navmeshes for Gnarled Forest?

**Comment by leolion3** [comment]
The folder was missing altogether, fixed now
