### ISSUE TITLE
Moonbase Gravity isn't lowered

### ISSUE THREAD

**Issue by MichaelFedora** [DarkflameUniverse/DarkflameServer#97]
If I recall correctly the gravity in Moonbase was lowered in the vanilla game, but it is normal with this server.

**Comment by Jettford** [comment]
Did some debugging for this.

The trigger is loaded successfully, and the PhantomPhysicsComponent does have the active flag set to true, effect set to gravity and the directional multiplier is set correctly yet nothing appears to be happening on the client.

**Comment by averysumner** [comment]
This was fixed with #151.
