### ISSUE TITLE
BUG: Surprise packs sometimes give nothing

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#972]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

cff94b6

### Issue Description

Sometimes, using a surprise pack removes the pack but gives nothing. Haven't encountered issues with other types of packages. This only happens sometimes. I've experienced it at least once in almost every playthrough.

### Reproduction Steps

Unsure, its very inconsistent. Last time it happened, I had just gotten Picky Shopper 2 and opened the surprise pack reward while moving.

### Expected Behavior

the pack should always give loot

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Happens if you are unlucky.  Won't fix

**Comment by EmosewaMC** [comment]
<img width="673" alt="Screen Shot 2023-01-25 at 4 32 16 PM" src="https://user-images.githubusercontent.com/39972741/214726499-e1e79814-7b24-4db0-b0e6-0082e21dc011.png">
had to find the package, but as you can see, this package is in now way guaranteed to give you something.
