### ISSUE TITLE
BUG: Landing animation for Return to the Venture Explorer is absent

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#975]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

cff94b6

### Issue Description

When loading into Return to the Venture Explorer, the player phases in, like how it looks to log back into a world.

### Reproduction Steps

Fly to Return to the Venture Explorer

### Expected Behavior

There should be the usual rocket landing animation, accompanied by a camera pan.

### Environment

ubuntu server

**Comment by HailStorm32** [comment]
Looks like animations in general have been borked.
see https://github.com/DarkflameUniverse/DarkflameServer/issues/974

**Comment by Jettford** [comment]
That is unrelated.

**Comment by MustacheMan2** [comment]
> Looks like animations in general have been borked. see #974

I'm not seeing any issues like that, things work fine on my build.
