### ISSUE TITLE
BUG: Can't access Block Yard normally, and after killing the Giant Spider, I cant claim the place.

### ISSUE THREAD

**Issue by mporto789** [DarkflameUniverse/DarkflameServer#978]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

cdffd5f

### Issue Description

I can't fly to block yard the game freezes. I already checked the right checksum: 0d862f71eedcadc4494c4358261669721b40b2131101cbd6ef476c5a6ec6775b.

![LEGO_Universe_2023-01-25_22-48-02](https://user-images.githubusercontent.com/95727002/214755146-db946353-41ae-458f-a470-537200623e0e.jpg)
Tried to use /testmap, to access it, it worked. I killed the boss, but when i tried to claim the place, it did not let me.
The Log when i tried to:
[25-01-23 23:13:50] [Properties] Getting property info for 1150
[25-01-23 23:13:50] [SendDownloadPropertyData] (288300748454049520) sending property data (1)
[25-01-23 23:13:50] [PropertyVendorComponent] Property vendor opening!
[25-01-23 23:13:51] [PropertyVendorComponent] FAILED TO CLAIM PROPERTY.  PLAYER ID IS 1152921508901814274
[25-01-23 23:13:56] [Properties] Getting property info for 1150
[25-01-23 23:13:56] [SendDownloadPropertyData] (288300748454049520) sending property data (1)
[25-01-23 23:13:56] [PropertyVendorComponent] Property vendor opening!
[25-01-23 23:13:58] [PropertyVendorComponent] FAILED TO CLAIM PROPERTY.  PLAYER ID IS 1152921508901814274
[logs.zip](https://github.com/DarkflameUniverse/DarkflameServer/files/10506205/logs.zip) All of my logs after i used /testmap.

As a quick note: I had a similar problem accessing the Avant Gardens Survival, After applying the old Fix it worked.
![LEGO_Universe_2023-01-25_21-54-23](https://user-images.githubusercontent.com/95727002/214755946-2ae81f60-1acb-4548-bfbc-d4fba18e1fc7.jpg)

### Reproduction Steps

Trying to use the rocket to access Block Yard, and claiming the lot.

### Expected Behavior

Me accessing the Block Yard and claim the Lot.

### Environment

Windows 10, using the https://gist.github.com/HailStorm32/169df65a47a104199b5cc57d10fa57de (Native Windows Setup) Tutorial.

**Comment by EmosewaMC** [comment]
This is an intended block to stop players from claiming properties that are not their own.  Wont fix.  Update your server and rebuild the binaries and your issues will be fixed.

**Comment by EmosewaMC** [comment]
I have pulled and tested against the main branch and none of the issues claimed here are present.  Ensure your build is updated properly to the latest version.

**Comment by EmosewaMC** [comment]
I looked into your logs and you appear to have things running on ports that dlu uses for main worlds.  You will need to change your world_port_start start number in masterconfig.ini to be higher than 3000 due to these issues
