### ISSUE TITLE
Server crashes if local directory is not the build directory

### ISSUE THREAD

**Issue by MasterEric** [DarkflameUniverse/DarkflameServer#98]
The following works:

```
./MasterServer
```

The following displays a crash with an obtuse error report:

```
~/DarkflameServer/build/MasterServer
```

**Comment by jelimoore** [comment]
Just `cd` to the directory first, it relies on the `res/` folder and other resources.

**Comment by DarwinAnim8or** [comment]
What @jelimoore commented is correct and also how the program is supposed to work-- not to mention that it'd be hard to change it to work in any other way.
