### ISSUE TITLE
BUG: Ignoring a player is unimplemented

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#985]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

d17f511

### Issue Description

Currently, attempting to block a player does nothing and the blocked players list stays empty.

### Reproduction Steps

try to block a player

### Expected Behavior

unsure on what blocking a player entailed in live

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
i have just realized the irony of labeling this issue blocked
