### ISSUE TITLE
ENH: Modularize Crafting bit for Vendors

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#993]
### Is your feature request related to a problem?

Currently, if a designer wants to add a vendor to a map with craftable items, the correct UI will not be used.
Our change should be to check the vendors' inventory for craftable items and if there are any, set the following function to true
https://github.com/DarkflameUniverse/DarkflameServer/blob/main/dGame/dComponents/VendorComponent.cpp#L46-L49

### Describe the solution you'd like

Go through each item in the vendors' inventory.  If any contain `currencyCosts` then set the bit to true.

### Repository breaking implications

None.

### Describe alternatives you've considered

Hard coding LOTs.

**Comment by aronwk-aaron** [comment]
https://lcdruniverse.org/lu_packets/lu_packets/world/gm/server/struct.RequestUse.html
Could be relevent

**Comment by EmosewaMC** [comment]
Not really - this is related to the serialization of the vendor component and its third bit which determines if this is a multicost vendor

**Comment by aronwk-aaron** [comment]
yeah, but you could use that from the interaction to know to set the bit in the vendor component, is what I was getting at

**Comment by aronwk-aaron** [comment]
this was implemented
