### ISSUE TITLE
BUG: Can't change zones past zone 1100 (Avant Gardens)

### ISSUE THREAD

**Issue by DM1NIK** [DarkflameUniverse/DarkflameServer#994]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

d138b7b

### Issue Description

The server is running and somewhat working, however, as soon as you try to change the zone (for example enter survival or enter the block yard) the server no longer responds and the game doesn't freeze but you are softlocked. 

log: 
```
==> /opt/DarkflameServer/build/logs/MasterServer_1676766748.log <==
[19-02-23 01:35:09] [MasterServer] Received zone transfer req
[19-02-23 01:35:09] [InstanceManager] Searching for an instance for mapID 1101/-97076095
[19-02-23 01:35:09] [InstanceManager] Created new instance: 1101/3/-97076095 with min/max 4/4
[19-02-23 01:35:09] [MasterServer] Instance: 0/0/0 -> 0
[19-02-23 01:35:09] [MasterServer] Instance: 1000/0/1 -> 0
[19-02-23 01:35:09] [MasterServer] Instance: 1100/0/2 -> 0
[19-02-23 01:35:09] [MasterServer] Instance: 1101/-97076095/3 -> 1
[19-02-23 01:35:09] [MasterServer] Server not ready, adding pending request 1 1101 -97076095
```

Then after a few minutes the ChatServer disconnects:

```
==> /opt/DarkflameServer/build/logs/ChatServer_1676766749.log <==
[19-02-23 01:35:12] [ChatServer] A server is connecting, awaiting user list.
[19-02-23 01:35:27] [ChatServer] A server has disconnected, erasing their connected players from the list.
```

### Reproduction Steps

Server: rhel/rocky 

Everything was done just as in the Readme described. Using a systemctl service that does the following: 

[Unit]
Description=Darkflame Server
After=mariadb.service

[Service]
User=darkflame
Group=darkflame

WorkingDirectory=/opt/DarkflameServer/build
ExecStart=/opt/DarkflameServer/build/MasterServer 

Starting the service, entering the world, and then trying to change the zone, for example start a survival mission or enter block yard is the only to reproduce this on my end. 

### Expected Behavior

The server should handle the request properly and change the zone. This does work for the tutorial (zone 0) -> Avant Gardens which makes this whole behavior even weirder than it already is.

### Environment

Server: rhel/rocky 

Everything was done just as in the Readme described. Using a systemctl service that does the following: 

[Unit]
Description=Darkflame Server
After=mariadb.service

[Service]
User=darkflame
Group=darkflame

WorkingDirectory=/opt/DarkflameServer/build
ExecStart=/opt/DarkflameServer/build/MasterServer was done

**Comment by EmosewaMC** [comment]
Change your base worldServer port start.  You have something running on ports DLU uses and as such the servers are unable to connect to each other.  Try setting the worldServer port start to 4000

**Comment by DM1NIK** [comment]
I just cleared up the firewall rules a bit and now survival works but entering the block yard is still not possible. There is nothing using 1001 or 3000 range (3***) 

Surival works now like a charm, the block yard, not so much. The readme says that for brick building I need to do some extra steps (return 404) , however, since the avant gardens regions forces me to enter the block yard. Does that mean that I also need to handle that?

**Comment by EmosewaMC** [comment]
Ignore unknown world packet warnings.  They are unrelated to this issue.

Did you happen to modify the maximum clients in sharedconfig.ini?  If so what did you set this value to?

**Comment by DM1NIK** [comment]
Yes, I set that to 5. (the maximum amount of friends that could potentially be on the server)

**Comment by EmosewaMC** [comment]
> Yes, I set that to 5.

Ah that's the issue.  We need to document that better because that limit also applied to the server RakPeer instances.  You'll want that set a bit higher, I'd say around 50 for a single player server at least and more for multiplayer

**Comment by DM1NIK** [comment]
Wow, I did not think a second about that but makes sense. It works now.
